### PR TITLE
Fixing DoDragDrop AccessViolationException

### LINKED ISSUE #7381: DoDragDrop to RichTextBox results in AccessViolationException
### .NET version

7.0

### Did it work in .NET Framework?

Yes

### Issue description

As noted in https://github.com/dotnet/winforms/pull/6576#issuecomment-1176883278, I see an `AccessViolationException` when drag-and-dropping to the `RichTextBox` and the operation fails.  I'm not yet sure if it is related to the work done in #6576 or not.

AccessViolationException

### Steps to reproduce

https://user-images.githubusercontent.com/5017479/177667691-10bb7107-eaa2-4c40-807d-46ee0ea24ec5.mp4

### PR DESCRIPTION
**Pull request by willibrandon**
Fixes #7381

I believe this issue is due to and limited to the new API work done in #6576.

## Proposed changes

- Fix the `AccessViolationException` that occurs when dropping data to `RichTextBox`, and possibly other controls.

## Customer Impact

- Alleviate the serious error.

## Regression? 

- It’s wrong right out of the gate.

## Risk

- Minimal

## Test methodology 

- Write a test to demonstrate the `AccessViolationException`.
- Fix the `AccessViolationException`.
- Verify the fix also fixes the test.
- Run unit and integration tests.

## Test environment(s) 

- 7.0.0-preview.1.22076.8

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7528)

### CODE REVIEW

**Comment by willibrandon** [comment]
Here is a test that demonstrates the issue.

**Comment by RussKie** [comment]
Kaboom!
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Interop+Ole32.<DoDragDrop>g____PInvoke|18_0(IntPtr, IntPtr, DROPEFFECT, DROPEFFECT*)
--------------------------------
   at Interop+Ole32.DoDragDrop(IntPtr, IntPtr, DROPEFFECT, DROPEFFECT ByRef)
   at Interop+Ole32.DoDragDrop(System.Runtime.InteropServices.ComTypes.IDataObject, IDropSource, DROPEFFECT, DROPEFFECT ByRef)
   at System.Windows.Forms.Control.DoDragDrop(System.Object, System.Windows.Forms.DragDropEffects, System.Drawing.Bitmap, System.Drawing.Point, Boolean)
   at System.Windows.Forms.UITests.DragDropTests+DragDropFormPictureBoxRichTextBox.PictureBoxDragSource_MouseDown(System.Object, System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.OnMouseDown(System.Windows.Forms.MouseEventArgs)
   at System.Windows.Forms.Control.WmMouseDown(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, WM, IntPtr, IntPtr)
   at Interop+User32.DispatchMessageW(MSG ByRef)
   at Interop+User32.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr, msoloop, Void*)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(msoloop, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(msoloop, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.RunDialog(System.Windows.Forms.Form)
   at System.Windows.Forms.Form.ShowDialog(System.Windows.Forms.IWin32Window)
   at System.Windows.Forms.Form.ShowDialog()
   at System.Windows.Forms.UITests.ControlTestBase+<RunFormWithoutControlAsync>d__29`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
```

**Comment by willibrandon** [comment]
First time I've had to correct an `AccessViolationException`.

**Comment by willibrandon** [comment]
We could use more actual drag and drop tests, its a blind spot.

**Review by RussKie — APPROVED** [review]

**Review by dreddy-work — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you!

**Pull request merged**
