### PR TITLE
Fix `KeyUp` event on `Listview` control

### LINKED ISSUE #8537: No call to KeyUp event handler on ListView control after upgrading from .NET6 to .NET7
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/No-call-to-KeyUp-event-handler-on-ListVi/10263887)._

---
[severity:I'm unable to use this version] [regression] [worked-in:.NET 6]
**Steps to reproduce**
- Visual Studio 17.4.4.
- Out-of-the-box Windows Forms app using .NET 7 for Windows.
- ListView control on the main form (which is given focus in Form1.Activated event handler).
- Empty KeyUp event handler on the ListView control.
- Start the app and press a key. (The ListView control has focus.)

**Expected**
A call to the ListView1.KeyUp event handler.

**Actual**
No call

---
#### Feedback Bot on 1/30/2023, 08:55 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by elachlan**
Fixes #8537

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8546)

### CODE REVIEW

**Comment by elachlan** [comment]
@lonitra I did a quick test and you are correct, it was the missing call to the `base.WndProc`.

**Comment by MelonWang1** [comment]
Hi @elachlan, Tested [private binaries](https://mlangfs1/public/Winforms/v-melonwang/PR%20testing/PR8546) built by us for PR: [8546](https://github.com/dotnet/winforms/pull/8546) based on the latest .NET 8.0 SDK build, GH issue [8537](https://github.com/dotnet/winforms/issues/8537) is fixed. No new issue found. In addition, ran migrated automation cases with no new regression issue found.

**Review by dmitrii-drobotov — COMMENTED** [review]
Looks good! Is it possible to also add a unit test?

**Comment by elachlan** [comment]
Is there an example test somewhere of sending a key?

**Comment by dmitrii-drobotov** [comment]
@elachlan there is a `KeyboardSimulator` class with this functionality, I think something like this should work:
```
using ListView control = new();
int callCount = 0;
control.KeyUp += (_, _) => callCount++;

KeyboardSimulator.KeyPress(control, Keys.Enter);

Assert.Equal(1, callCount);
```

**Comment by elachlan** [comment]
Test fails prior to change and passes after the change.

**Review by lonitra — APPROVED** [review]
Looks good! Thank you for hopping on this issue

**Review by dreddy-work — APPROVED** [review]

**Comment by dreddy-work** [comment]
backport to release/7.0

**Comment by MelonWang1** [comment]
@elachlan Verified this issue on lasted .NET 8.0 SDK build form main branch 8.0.100-preview.2.23107.33 and the daily build from 8.0.1xx-preview1 branch8.0.100-preview.1.23107.34, it is still repro. Should we change milestone from 8.0 preview1 to 8.0 preview2?

**Comment by elachlan** [comment]
@MelonWang1 So this is broken again?

**Comment by MelonWang1** [comment]
@elachlan I'm sorry, this issue is fixed in the dotnet/winforms repo. It just doesn't insert to latest .NET 8.0 SDK. @dreddy-work Should we change milestone from 8.0 preview1 to 8.0 preview2?

**Pull request merged**
