### PR TITLE
Replace Workspaces nuget packages with compiler only packages

### LINKED ISSUE #8387: Analyzer projects shouldn't have a dependency on Workspaces
They shouldn't need it, and it's problematic if types from Workspaces are used in these projects.

### PR DESCRIPTION
**Pull request by elachlan**
Fixes #8387 - Replace Workspaces nuget packages with compiler only packages

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8389)

### CODE REVIEW

**Comment by elachlan** [comment]
CC: @Youssef1313

**Comment by elachlan** [comment]
We should probably move to the compilers nuget package. But I figure the team might want the flexibility to update each on individually.

**Review by Youssef1313 — APPROVED** [review]
LGTM

**Review by dreddy-work — APPROVED** [review]

**Comment by dreddy-work** [comment]
> We should probably move to the compilers nuget package. But I figure the team might want the flexibility to update each one individually.

I am not sure how consistent they are with versioning. For now, we can keep it this way.

**Comment by elachlan** [comment]
@dreddy-work sounds good. The tests failures here are flaky.

**Pull request merged**
