### PR TITLE
Port feature/win32 branch to main

### PR DESCRIPTION
**Pull request by lonitra**
Rebased feature/win32 branch onto main

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7828)

### CODE REVIEW

**Review by RussKie — APPROVED** [review]
🎉

**Comment by RussKie** [comment]
Thank you @fernandanavamoya @lonitra @elachlan @JeremyKuhne @KlausLoeffelmann @AArnott for your efforts.
We tried our best to untangle the history and rebase the work on the main. If you spot something we missed, please let us know, and we'll port it, or send a PR with a fix to the main branch.

**Comment by RussKie** [comment]
@vladimir-krestov @dmitrii-drobotov @dkazennov @NikitaSemenovAkvelon FYI - we should not add any more pinvoke imports manuall and leverage CsWin32 capabilities instead. Please reach out, if you have any questions.

**Comment by elachlan** [comment]
CC: @kant2002

**Comment by kant2002** [comment]
@elachlan are you think that CsWin32 ready for WPF too ?

**Comment by elachlan** [comment]
We haven't finished the whole process yet. It is ongoing. I created an issue for WPF at https://github.com/dotnet/wpf/issues/7007.

I think if the work was started on it, then it might help get more people working on CsWin32/Win32Metadata and that would help a lot of different projects.

I pinged you here so you are aware of it for your work on Com wrappers and Native AOT in winforms.

**Pull request merged**
