### PR TITLE
added validation of the resource list for winforms and .Design assemblies

### PR DESCRIPTION
**Pull request by Tanya-Solyanik**
Ensure that we do not add any unexpected resources.

Removed test that validated presence of manifest because it's superseded by the test that matches available resources against the expected list.
Expected lists are dumped out from assemblies before the change that introduced regular expressions to the project files.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8393)

### CODE REVIEW

**Comment by elachlan** [comment]
LGTM! Only suggestion would be if we can maintain the lists of icons, cursors, and manifest separately. Then use them in the other tests as well as this new test. That way we reduce the duplicated data.

**Comment by Tanya-Solyanik** [comment]
>Then use them in the other tests as well as this new test. 

Thank you, good idea! This list is easier to dump and update than to match inline data to file names! This is how I tested your fix. I was going add the same to .Design assembly, where the list is generated off version before your change.

**Comment by elachlan** [comment]
LGTM! This is great!

**Review by lonitra — APPROVED** [review]
🚀

**Comment by Tanya-Solyanik** [comment]
Thank you @elachlan @lonitra!

**Pull request merged**
