### PR TITLE
Fix NRE when instantiating UserControl as ActiveX object

### LINKED ISSUE #4370: Hosting UserControl via ActiveX does not work correctly
* .NET Core Version: 5.0

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
I am experimenting with doing Office Addins without VSTO and using .NET 5. So far, I have succesfully manged to add ribbon buttons and I'm now working on a custom TaskPane, hosting a Winforms UserControl.

So far, so good. However, when instantiating the UserControl, an exception is thrown here: https://github.com/dotnet/winforms/blob/cb03d37fe73fb178d3c3827ad895bb3e7c50fe4c/src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs#L841

_inPlaceUiWindow is null here and there is no check for that case.

Comparing to .NET Framework 4.8 reference source (https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Control.cs,17065), the implementation is different and I suspect that a regression has snuck in.

**Expected behavior:**
No NullReferenceException should be thrown.

**Minimal repro:**
You can download the project here: https://1drv.ms/u/s!AkwgkpetCvCpr4JeJeZfCGlKlHs4qA?e=PeB0So
You need to manually run `regsvr32 OutlookAddinNet5.comhost.dll` in the bin folder and register the addin in outlook:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\Outlook\Addins\OutlookAddinNet5]
"CommandLineSafe"=dword:00000001
"Description"="OutlookAddinNet5 description"
"FirendlyName"="OutlookAddinNet5 name"
"LoadBehavior"=dword:00000003

```

Then Open Outlook and click the [2] button added to the ribbon.

### PR DESCRIPTION
**Pull request by 1R053**
Fixes #4370

## Proposed changes

The issue fixes some code that was probably erroneously copied & pasted when porting from .NET framework here:
https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Control.cs,17065

## Customer Impact

- quite critical, as in certain situation .NET Core is totally unusable due to this. E.g. when using Core inside Office Add-Ins, it was not possible at all to use the task pane for building addins. This is a showstopper for our go-live.

## Regression? 

- None introduced, hopefully

## Risk

- unknown

## Test methodology 

- run build and test
- sorry, this project is quite tangential for me, and it is an obvious fix, once you confirmed this successfully for the main branch, it would be awesome to backport to 5.x, let me know if I should create a PR as well for that.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/4626)

### CODE REVIEW

**Comment by dreddy-work** [comment]
Seems was introduced in one of the cleanup performed here #62826d7d550c5b8f79d7b0adce943b87e9c6e790

**Review by dreddy-work — APPROVED** [review]

**Comment by 1R053** [comment]
thanks @dreddy-work 
for backporting to 5.x should I create another PR or intend you guys to do this?

**Comment by dreddy-work** [comment]
> thanks @dreddy-work
> for backporting to 5.x should I create another PR or intend you guys to do this?
@1R053 , can you please provide a stand alone repro we could use to verify scenario and its priority in .Net core. That would help to make decision on the need for servicing.

**Comment by 1R053** [comment]
one more question - How can I set the version number for a local build? It always goes to 42.42.42.42424, which makes it not usable as a drop-in bugfix under C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\

I'd like to use the locally built file as a drop in replacement for the regularly installed file to test the changes fully in our project environment.

**Comment by RussKie** [comment]
> one more question - How can I set the version number for a local build? It always goes to 42.42.42.42424, which makes it not usable as a drop-in bugfix under C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\
> 
> I'd like to use the locally built file as a drop in replacement for the regularly installed file to test the changes fully in our project environment.

You don't. 
It is a drop-in artifact, but you need to have a correct .NET SDK installed. That is, the main is targeting .NET 6.0p3, so you need to have a recent .NET SDK available globally. Dropping the dev artifact in .NET 5.0 won't work.

There's a 6.0p3 build available at https://github.com/dotnet/installer. Alternatively, you can either copy the build from winforms/.dotnet folder, or create a global symlink to it.
Please let me know if you have troubles.

**Comment by 1R053** [comment]
Here is the Repro, instructions are in the readme
https://github.com/1R053/WinformsBugfixRepro

regarding the dropin: I have the 5.0 branch downloaded and modified for it - so I hope it would work to just replace the patched file inside the installed 5.0 SDK to see if it is working inside the main project. 
The real question is however, how can this solution get shipped to customers  as soon as possible.

Thanks for your fast responses so far!

**Comment by dreddy-work** [comment]
> Here is the Repro, instructions are in the readme
> https://github.com/1R053/WinformsBugfixRepro
> 
> regarding the dropin: I have the 5.0 branch downloaded and modified for it - so I hope it would work to just replace the patched file inside the installed 5.0 SDK to see if it is working inside the main project.
> The real question is however, how can this solution get shipped to customers as soon as possible.
> 
> Thanks for your fast responses so far!

Thanks @1R053 for the repro app. We could get this into 6.0. but servicing the fix  to 5.0 or lower would need to go through bar check. Given that ActiveX controls are not officially supported in the .NET core, I highly doubt on servicing this to lower versions. Also, 5.0 is not in LTS.

**Comment by 1R053** [comment]
@dreddy-work I understand the organisational challenge. What is your recommended suggestion to get this shipped to customers in the next 2-3 weeks? 
- wait for official 6.0 release
- roll the solution out with a locally patched 5.0 release
- backport official 5.0

**Comment by dreddy-work** [comment]
> @dreddy-work I understand the organisational challenge. What is your recommended suggestion to get this shipped to customers in the next 2-3 weeks?
> 
> * wait for official 6.0 release
> * roll the solution out with a locally patched 5.0 release
> * backport official 5.0

given your timeframe, patched version is only solution it seems.

**Comment by dreddy-work** [comment]
@1R053, our test team tried to find the exact crash scenario using your sample app but they did not see crash/behavior change before/after this. They followed exact steps provided in the readme.  Are me missing anything here? Would it be possible to make a GIF while you repro this on your end and share, just in case if we are missing anything.

**Comment by 1R053** [comment]
In my testing using a locally patched 5.0 version I have seen, that this particular crash is gone. However, since now code pieces are executed that probably have never been touched before with an active COM UserControl it runs into the next issues. They are maybe with the .NET Core COM framework that creates the comhost shim for this component. I have not yet figured out the exact issue(s) here. But imo this is why you don't see a behaviour change in the repro solution after this issue is fixed.

**Comment by RussKie** [comment]
I bisected it, and the regression was introduced in early .NET 5.0 in https://github.com/dotnet/winforms/pull/1868.
I'm happy to take it in 6.0 as is, but without a reproducible sample it is hard to meet the servicing bar.

**Comment by RussKie** [comment]
Thank you @1R053.

Btw, it is an anti-pattern to work off branches you don't own (e.g. working off main, master, etc. branches). You open yourself to the world of pain when the remote/main moves, and you need to pull the latest changes.

**Comment by 1R053** [comment]
Thanks @RussKie

The repro imo should work, once all UserControl COM issues are solved. This appears to have been only one step, as we now run into the next issues related to this. Maybe you know better who can have a look at the repro and figure out the next crash site.

**Comment by RussKie** [comment]
If you can get us a stable repro, we can investigate it deeper.

It is worth noting, that there is no official VSTO or Office integration support at this stage. We're aware of the gap and the community desire for this gap to be closed, but there is no additional information that can shared at this stage.

**Comment by 1R053** [comment]
The issue is, that with .NET Core there is no stable repro yet, as COM UserControl has never worked so far apparently. At the moment we have to go back to .NET Framework (which unfortunately has no own generic COM shimming) for our solution.

This project imo would be a stable solution, after all COM UserControl issues are fixed (though the name is probably not optimal now)
https://github.com/1R053/WinformsBugfixRepro

For example, after this fix the generated comhost.dll does not even register successfully anymore with regserv32 in my environment. This should not happen and probably points to issues that are to be solved in the comhost shim coding or some winforms coding that gets called by the comhost shim.

**Pull request merged**
