### PR TITLE
Rewrite MAUI tests

### LINKED ISSUE #3617: MAUI tests fail frequently and aren't easily diagnosable
These are an attempt to shim in the old internal tests (note that MAUI here is an old internal test framework). The old tests worked quite differently and don't fit in well with the current test infrastructure. We're getting [frequent intermittent failures](https://dev.azure.com/dnceng/public/_build/results?buildId=737706&view=ms.vss-test-web.build-test-results-tab&runId=22844842&resultId=100000&paneView=history) like so:

```
System.Windows.Forms.Maui.IntegrationTests.WinformsMauiButtonTests.MauiButtonTest(scenarioName: \"Hotkey_Fires_OnClick\")

Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: Pass\r\nActual:   Fail\r\n          ↑ (pos 0)

Stack trace
   at System.Windows.Forms.Maui.IntegrationTests.MauiTestHelper.ValidateScenarioPassed(String projectName, String scenarioName) in /_/src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/MauiTestHelper.cs:line 90
   at System.Windows.Forms.Maui.IntegrationTests.WinformsMauiButtonTests.MauiButtonTest(String scenarioName) in /_/src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiButtonTests.cs:line 35
``` 

This doesn't really help you much and it isn't obvious as to what you can do to move forward. In addition, the MAUI infrastructure sources aren't available so it is difficult to understand how the whole system works.

My recommendation (and current POR):

1. Disable the MAUI tests for now
2. Make them more xUnit-like and have any shim code in the repo
3. If we can make the tests plug in as a "normal" xUnit test then re-enable them for the CI, otherwise leave them for manual runs

cc: @AdamYoblick, @RussKie 

Failed with #3600

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #3617

## Proposed changes

- Rewrite the UI tests infrastructure using the foundation laid by @sharwell in https://github.com/dotnet/winforms/compare/main...sharwell:sample-test.
- Amalgamate all tests from all MAUI test projects into the new UI test projects.
- Remove all MAUI tests.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/6091)

### CODE REVIEW

**Comment by RussKie** [comment]
@sharwell @richlander I'd appreciate your help in correctly attributing the test infra authorship/origin in THIRD-PARTY-NOTICES.TXT.

**Comment by RussKie** [comment]
@sharwell I'd really appreciate your review for the 1st commit where I'm porting the infra from NUnit to XUnit.

**Comment by sharwell** [comment]
@RussKie did you see my internal message on this subject (on Teams)?

**Comment by RussKie** [comment]
@sharwell I ended up ultimately taking your original code, and enabled porting the MAUI tests to use the new infra.

**Comment by sharwell** [comment]
> @sharwell I ended up ultimately taking your original code, and enabled porting the MAUI tests to use the new infra.

Exciting!

**Comment by RussKie** [comment]
@Danil-Andrianov, I'm waiting for the remainder of the MonthCalendar tests from you, and we can merge this.

**Pull request merged**
