### PR TITLE
Restore back ComWrappers for DoDragDrop

### LINKED ISSUE #7864: IDataObject.GetData with non-serializable type returns null
### .NET version

.NET 7 RC1

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, up to and including .NET 6.

### Issue description

Hello,

My name is Norton, and I'm writing on behalf of the WinForms team at DevExpress.

Our customers who were testing our controls with the .NET 7 RC1 runtime reported issues when using our controls' drag-drop capabilities. Upon further research, we found what seems to be a breaking change in .NET 7: whenever an instance of a non-serializable class is used with the [`Control.DoDragDrop`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.dodragdrop) method, calling [`IDataObject.GetData`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.idataobject.getdata) with that class as a parameter afterwards returns `null` rather than the dragged object.

We could not find any issues/PRs or MSDN articles documenting this change. Could you have a look and let us know if this change is intended?

### Steps to reproduce

I attached a sample application. To replicate this behavior, run the project and start dragging anywhere on the form. The [`Debugger.Break`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debugger.break) method is called to indicate that the `GetData` method returned `null`.

If the type of the dragged object is made serializable (e.g. by modifying the `using` statement in `Form1.cs`), this behavior no longer takes place.

[DXApplication1.zip](https://github.com/dotnet/winforms/files/9674453/DXApplication1.zip)

### PR DESCRIPTION
**Pull request by kant2002**
Fixes #7864

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7869)

### CODE REVIEW

**Comment by kant2002** [comment]
Also test with project mentioned here https://github.com/dotnet/winforms/issues/7518#issuecomment-1203643595 no regressions

**Comment by willibrandon** [comment]
I tested this PR using the test provided in the issue description and confirmed it fixes the issue.

Before
https://user-images.githubusercontent.com/5017479/193437723-0525b074-007e-4415-8d51-c1133d4cb8f8.mp4

After
https://user-images.githubusercontent.com/5017479/193437729-a14c2fab-7ec1-4dfb-8a34-10b4f6e653a8.mp4

I can write the regression test if you would like.

**Comment by kant2002** [comment]
@willibrandon if you can, please write regression test. We definitely need this kind of things

**Comment by willibrandon** [comment]
@kant2002 - I'm not sure your current project status, but I can provide test support, and sooner or later we'll have all of the cases covered :smile: As we have found, drag and drop could use more tests, and I'm in a good spot to write those now.

**Comment by willibrandon** [comment]
I’ve written a UI regression test that reproduces the issue and confirms the fix.

**Comment by kant2002** [comment]
Send PR with test. let it fail, and you can cherry pick this commit so we would check that it fixed your new test.

**Review by JeremyKuhne — APPROVED** [review]
Thanks for the quick turnaround here.

**Comment by RussKie** [comment]
Thank you @kant2002!

**Pull request merged**
