### PR TITLE
Fixing EditTextBox AO position in the PropertyGrid tree (port 6.0)

### LINKED ISSUE #5656: Accessibility: PropertyGrid: An onscreen element must not have a null BoundingRectangle property
* .NET Core Version: 
.Net SDK 6.0.100-preview.7.21379.14

* Have you experienced this same bug with .NET Framework?: 
Yes

**Minimal repro:**
1. Open attached application in VS,  with PropertyGrid control 
[WinFormsApp15.zip](https://github.com/dotnet/winforms/files/7087962/WinFormsApp15.zip)
2. Build and run it
3. In AccessibilityInsight or Inspect to detect propertyGrid 

**Actual behavior:**
1. AccessibilityInsight detects an error about "An onscreen element must not have a null BoundingRectangle property" for Text property
image
2. In Inspect, for Text property, there is missing BoudingRectangle property, and other properties are incorrect for Role, State, Value, Value.Value.
image

**Expected behavior:** Following results are gotten when clicking text edit area, then use accessibility tools to detect
1. AccessibilityInsight detects no error:
image
2. In inspect, it has BoudingRectangle property, and other properties: Role, State, Value, Value.Value are correct:
image

### PR DESCRIPTION
**Pull request by vladimir-krestov**
Fixes #5656 

(cherry picked from commit 28e4b7d4ea6a4fb21bc777b83b36e7765e44bd49 and then additional changes were added)

This is a port from #5724. Please see its description for details.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/5725)

### CODE REVIEW

**Comment by vladimir-krestov** [comment]
Testers approved the fix ✔️

**Comment by dreddy-work** [comment]
@vladimir-krestov , this port has more changes compared to cherry-picked commit.  Also, PR into main has some test failures and labelled for "Waiting for testing".  Can you explain the discrepancies and update labels if validations complete?

**Comment by vladimir-krestov** [comment]
> @vladimir-krestov , this port has more changes compared to cherry-picked commit. Also, PR into main has some test failures and labelled for "Waiting for testing". Can you explain the discrepancies and update labels if validations complete?

@dreddy-work, I have synced the PRs, I just forgot to add an additional check for 7.0 PR. This branch (6.0) was tested by CTI, they approved the fix. PR #5724 is not tested yet - so has waiting-for-testing label.

**Review by dreddy-work — APPROVED** [review]
LGTM>

**Pull request merged**
