### PR TITLE
disable test signing while arcade is looking into issue

### PR DESCRIPTION
**Pull request by AdamYoblick**

### CODE REVIEW

**Comment by AdamYoblick** [comment]
Merging this in without a review because it's blocking our official build.

**Comment by AdamYoblick** [comment]
The arcade issue is at https://github.com/dotnet/core-eng/issues/4734

**Comment by JohnTortugo** [comment]
Looks like your release build [isn't doing signing](https://dnceng.visualstudio.com/internal/_build/results?buildId=55404&view=logs&jobId=16ce49ee-8d0d-5a76-4958-88f78392b71f&taskId=206012c0-0eaa-56aa-8172-665f354177dc&lineStart=26&lineEnd=26&colStart=922&colEnd=930). Looks like the value assigned to $_Sign on line 33 isn't being used on the [release leg](https://dnceng.visualstudio.com/internal/_build/results?buildId=55404). I'm no expert on the build config, @chcosta can you take a peek?

**Comment by chcosta** [comment]
Signing property variables are not being defined in the build_release leg of the matrix https://github.com/dotnet/winforms/blob/2dd090d83b3cfbf2c02ab6167477564f60765fb6/eng/ci.yml#L89

**Comment by AdamYoblick** [comment]
Hi Chris,

This doesn't make any sense to me. I've defined these variables before the matrix and overridden some values only in Debug. Real signing worked just fine before I added these debug overrides.

Does overriding the values in the Debug leg of the matrix mean I HAVE TO override them in the release leg as well? If so, that seems like a silly constraint of yaml?

**Comment by chcosta** [comment]
Fair point, that's what I get for trying to get you unblocked and not digging deeply into your code.

Looks like you have a typo

https://github.com/dotnet/winforms/blob/2dd090d83b3cfbf2c02ab6167477564f60765fb6/eng/ci.yml#L34

```
        - name: _Sign
          vale: true
```

I happened upon this when I looked at "Download all logs" -> "initializepipeline.txt" and noticed that the "_Sign" variable was getting resolved as...

```
  variables:
  - name: _TeamName
    value: DotNetCore
  - name: _SignType
    value: test
  - name: _SignArgs
    value: ''
  - name: _Sign
    value: ''
```

… which is consistent with what is being seen on the release leg.

**Comment by AdamYoblick** [comment]
Well shit. Thanks for the catch. :)

Really wish the yaml parser would catch syntax errors like this.


________________________________

**Comment by chcosta** [comment]
This is because the current implementation of yaml doesn't allow us to define a schema so we can't be explicit about required properties.  The result is that we end up hiding this syntax error [here](https://github.com/dotnet/arcade/blob/master/eng/common/templates/job/job.yml#L100).  We don't have a way to say that any other property of "variable" is invalid.  Azure DevOps is considering other implementations which would help us with this scenario but I wouldn't expect to see anything in the immediate future.

**Comment by AdamYoblick** [comment]
Yeah I didn't expect Arcade to catch the error, AzDO should. Any "-name" without an associated "value" should blow up. :)

**Pull request merged**
