### PR TITLE
 Reset the owner of ListViewSubItem when removing from ListViewSubItemCollection

### LINKED ISSUE #373: ListViewSubItemCollection.Remove should set the item's owner to `null`
```cs
[Fact]
public void IListRemove_ListViewSubItem_Success()
{
    var item = new ListViewItem();
    IList collection = new ListViewItem.ListViewSubItemCollection(item);
    var subItem = new ListViewItem.ListViewSubItem();
    collection.Add(subItem);

    collection.Remove(subItem);
    Assert.Empty(collection);
    Assert.Same(item, subItem.owner);

    // Remove again.
    collection.Remove(subItem);
    Assert.Empty(collection);
    Assert.Same(item, subItem.owner);
}
```

The owner remains even though the item has been removed

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #373

### CODE REVIEW

**Comment by zsd4yr** [comment]
Why?

**Comment by hughbe** [comment]
If a ListViewSubItem is removed from a `ListViewSubItemCollection` it no longer belongs to the `ListViewItem` associated with the `ListViewSubItemCollection`.

Therefore, we can get into strange situations if the `ListViewSubItem` is removed
- The connection from the parent `ListViewItem` to the child `ListViewSubItem` is severed
- The connection from the child `ListViewSubItem` to the parent `ListViewItem` is *not* severed

This gives strange situations where a `ListViewSubItem` can inherit things like background color and foreground color from a parent that no longer owns it... Practically I wouldn't expect it to have any display effect as the owner is overriden when the `ListViewSubItem` is added to another parent

**Comment by zsd4yr** [comment]
@Tanya-Solyanik @dreddy-work does this feel intentional to you?

**Comment by hughbe** [comment]
Added more tests, some of which failed before this change, namely what happens when you remove a subItem from its owner item

**Comment by dreddy-work** [comment]
> @Tanya-Solyanik @dreddy-work does this feel intentional to you?

Looks reasonable to me.

**Comment by dreddy-work** [comment]
@zsd4yr , if no one else object, take this in.

**Comment by hughbe** [comment]
Good to merge?

**Pull request merged**
