### PR TITLE
Reduce sharing of disposable objects across MemberData sets

### LINKED ISSUE #3487: Reduce sharing of disposable objects across MemberData sets
**.NET Core Version:**
master

**Have you experienced this same bug with .NET Framework?:**
no

**Problem description:**
During investigation of flaky unit tests it was noticed that sharing disposable objects between multiple yields of MemberData sets is not advisable. It works but relies on the undocumented fact that xunit disposes member data after all tests have run. If it were to dispose between test runs it would break those tests.

Its better style to have each set of test data be independent. This also reduces risk of undesired interaction between data sets.

**Expected behavior:**
Each set of (disposable) test data returned by MemberData functions should be independent

**Minimal repro:**
Source code review for shared member data

### PR DESCRIPTION
**Pull request by weltkante**
Contributes to #3487

## Proposed changes

Use factory methods instead of sharing disposable objects across MemberData sets

Sharing disposable objects relies on undocumented behavior of xunit (it does not guarantee that disposal happens after all tests are run, it could just as well dispose each set individually after running it). It also introduces hidden dependencies between tests that may lead to undesired interaction between tests.

## Customer Impact

none

## Regression? 

no

## Risk

none

### Before

sometimes disposable objects were shared between MemberData sets

### After

disposable objects should not be shared between MemberData sets

## Test methodology

code review

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3488)

### CODE REVIEW

**Comment by RussKie** [comment]
Few tests are failing:
```
    System.Windows.Forms.Tests.ScrollableControlTests.ScrollableControl_OnLayout_Invoke_CallsLayout(autoScroll: True, eventArgs: null, expectedCallCount: 1, affectedControl: null) [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ScrollableControlTests.cs(1407,0): at System.Windows.Forms.Tests.ScrollableControlTests.ScrollableControl_OnLayout_Invoke_CallsLayout(Boolean autoScroll, LayoutEventArgs eventArgs, Int32 expectedCallCount, Control affectedControl)
    System.Windows.Forms.Tests.ScrollableControlTests.ScrollableControl_OnLayout_Invoke_CallsLayout(autoScroll: False, eventArgs: null, expectedCallCount: 1, affectedControl: null) [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ScrollableControlTests.cs(1407,0): at System.Windows.Forms.Tests.ScrollableControlTests.ScrollableControl_OnLayout_Invoke_CallsLayout(Boolean autoScroll, LayoutEventArgs eventArgs, Int32 expectedCallCount, Control affectedControl)
```

**Comment by weltkante** [comment]
Rebased since you already added some of these fixes in another PR. The test failure was a mistake on my part, should be fixed.

**Comment by RussKie** [comment]
I'm happy to take as is, or wait a little more, if you're still iterating.

**Comment by weltkante** [comment]
I'm happy with the state of the files in the PR so far, won't get around to more this week anyways so you can get this reviewed and merged if you want. I've changed the PR description to not auto-close the issue.

I'll continue looking for more instances to fix over the next weeks and either close the issue or open another PR if there is more sharing of MemberData that needs to be fixed.

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
