### PR TITLE
Enable IDE0170 (simplify property pattern) analyzer and fix occurrences

### PR DESCRIPTION
**Pull request by elachlan**
Enables IDE0170 analyzer and fix occurrences

Related: #7887

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7917)

### CODE REVIEW

**Review by RussKie — APPROVED** [review]
Nice!

**Comment by elachlan** [comment]
Test failures. I will look into it.

**Comment by dreddy-work** [comment]
> Test failures. I will look into it.
> 
> Edit: Are they flaky tests?

Seems so. Reset them. Lets see.

**Pull request merged**
