### PR TITLE
Update branding to 6.0.12

### PR DESCRIPTION
**Pull request by vseanreesermsft**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8091)

### CODE REVIEW

**Comment by dreddy-work** [comment]
cmake version being used is not compatible with VS 2019?  @vseanreesermsft , do you see similar failure in any other repo?

**Comment by RussKie** [comment]
@jonfortescue @MattGal any guidance?

**Comment by jonfortescue** [comment]
looks like the cmake version is pinned in the branch that this is building from (see [here](https://github.com/vseanreesermsft/winforms/blob/branding-6.0.12-2022-11-01-1420/global.json#L24)). That needs to be changed to `latest` or `3`; we took cmake 3.22.6 in October which means 3.22.5 is no longer available on the machines.

**Comment by dreddy-work** [comment]
> looks like the cmake version is pinned in the branch that this is building from (see [here](https://github.com/vseanreesermsft/winforms/blob/branding-6.0.12-2022-11-01-1420/global.json#L24)). That needs to be changed to `latest` or `3`; we took cmake 3.22.6 in October which means 3.22.5 is no longer available on the machines.

@jonfortescue , do you mind pushing that change? Seems i do not have permissions to push your branch.

**Review by dreddy-work — APPROVED** [review]

**Pull request merged**
