### PR TITLE
Add Control dialog/input/key/menu tests

### PR DESCRIPTION
**Pull request by hughbe**
## Proposed Changes
- Add more Control tests
- Add more related ContextMenu/MainMenu/Menu tests

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/2139)

### CODE REVIEW

**Comment by zsd4yr** [comment]
Looks like legit failures

**Comment by RussKie** [comment]
The builds failures are red herrings, please make the PR up.

**Comment by hughbe** [comment]
> The builds failures are red herrings, please make the PR up.

Build now working!

**Pull request merged**
