### PR TITLE
Use CodeAnalysis.test.globalconfig only for overrides

### PR DESCRIPTION
**Pull request by sharwell**
All duplicate items have been removed, leaving only the unique configuration for tests. The specific configuration behavior is not changed.

### CODE REVIEW

**Comment by gpetrou** [comment]
@sharwell we are following what the runtime repository does. I see that https://github.com/dotnet/runtime/blob/e26e33f98a3c24640c48f35a1b183abe6aff37e7/eng/CodeAnalysis.test.globalconfig has not changed. Is the plan to change that as well?

**Review by RussKie — COMMENTED** [review]
👍 

Is this all manually reviewed and changed, or is there some tool that automates the de-duplication process?

**Review by dreddy-work — APPROVED** [review]

**Comment by sharwell** [comment]
> Is this all manually reviewed and changed, or is there some tool that automates the de-duplication process?

I just used Beyond Compare and removed lines that were identical.

**Comment by sharwell** [comment]
> Is the plan to change that as well?

I wasn't planning to (or aware of the similarity), but it could certainly be done.

**Pull request merged**
