### PR TITLE
Align wording with .NET Framework templates

### LINKED ISSUE #3905: A syntax error in description of .Net Core VB and C# Windows Forms Control Library templates
* .NET Core Version: 5.0.100-rc.2.20464.10
* Have you experienced this same bug with .NET Framework?: No

**Minimal repro:**
1.	Check the preview feature "Show all .Net Core templates in the New project dialog(required restart)" in Tools->Options->Environment->Preview Features
2.	Launch VS and click 'New Project'
3.	In 'Create a new project' dialog, search 'Winforms control library' 
4.	Look at the description for .Net Core VB and C# Windows Forms Control Library templates

**Actual behavior:**
A syntax error in description about 'A controls'
image

**Expected behavior:**
It should be 'Controls'

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #3905 
## Proposed changes

- Align wording with the existing templates
image
- Fix typo as pointed in https://github.com/dotnet/winforms/pull/3631#discussion_r478543774

## Customer Impact

- A more consistent UX

## Regression? 

- Yes / No

## Risk

- None

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3808)

### CODE REVIEW

**Comment by Pilchie** [comment]
Approved for RC1 pending code review, as long as it is merged by 10am Pacific Time on 2020-09-01.

**Comment by Pilchie** [comment]
Removing approval label, since we're passed the deadline for RC1 approvals, and still discussing whether we want to take this.

**Comment by RussKie** [comment]
@phenning would this change affect VS?

**Comment by phenning** [comment]
> @phenning would this change affect VS?

Sort of. Let me explain.

In the current non-preview GA experience in Visual Studio, these strings are coming from the vstemplate stub file.

I believe these are authored here for WinForms (unless they have been moved somewhere else)
https://github.com/dotnet/templates/blob/master/src/Templates/DotnetCore/Microsoft.NetCore.CSharp.ProjectTemplates.Desktop/Winforms.vstemplate

In the new preview experience in 16.8 preview 3 and later, the vstemplate file is not used and the names and descriptions would come from the template itself which your change targets.

**Comment by RussKie** [comment]
> In the new preview experience in 16.8 preview 3 and later, the vstemplate file is not used and the names and descriptions would come from the template itself which your change targets.

Thank you, so we will be showing the text from our templates.

@merriemcgaw @OliaG I think we need to consider this change.

**Comment by merriemcgaw** [comment]
@Pilchie would love your thoughts on this issue for RC2.

**Comment by Pilchie** [comment]
ASP.NET Core has taken several template updates to prepare for this VS change. (see https://github.com/dotnet/aspnetcore/pull/25630) for example. I'm okay with also bringing this if we're in alignment on what the strings should be.

**Comment by merriemcgaw** [comment]
@OliaG we probably need your thumbs up on the strings that @russkie proposes.

**Review by OliaG — APPROVED** [review]
Looks good!

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann is going to take the template rewording and get loc enabled for the new experience.

**Comment by RussKie** [comment]
Obsoleted by #4056

**Pull request closed without merging**
