### PR TITLE
Fixing issue 10213 by adding missed class StyleCollectionEditor

### LINKED ISSUE #10213: Unable to add columns/rows via the Edit Rows and Columns window of the TableLayoutPanel control in the DemoConsole application
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it doesn't work in .Net 8.0 from Release/8.0 branch of Winforms repo

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, unable to add columns/rows via the Edit Rows and Columns window of the TableLayoutPanel control.

**Actual result** in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app:

https://github.com/dotnet/winforms/assets/94418985/8734d29d-5db7-4674-8065-339b38f22e35

**Expected result**:
Columns/rows can be added via the Edit Rows and Columns window of the TableLayoutPanel control. But the column and row will not be refreshed in TableLayoutPanel after click the 'X' to close the Column and Row Styles dialog. Has known issue: [2508](https://github.com/microsoft/winforms-designer/issues/2508).

https://github.com/dotnet/winforms/assets/94418985/ff614d04-d333-4894-9030-d9692b25a8ed

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

### PR DESCRIPTION
**Pull request by LeafShi1**
Fixes #10213 

## Proposed changes

- Adding class StyleCollectionEditor，NavigationalTableLayoutPanel.cs and StyleEditorForm.cs

## Cause of this issue:

- Due to the missing StyleCollectionEditor, rows and columns cannot be added to the TableLayoutPanel control normally.

## Risk
- minimal

### Before

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, unable to add columns/rows via the Edit Rows and Columns window of the TableLayoutPanel control.

https://github.com/dotnet/winforms/assets/94418985/8734d29d-5db7-4674-8065-339b38f22e35

### After

AfterChange

## Test methodology 

- Manually

## Test environment(s) 

- .net 9.0.0-alpha.1.23559.1

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/10271)

### CODE REVIEW

**Comment by LeafShi1** [comment]
The fix not yet completed
1. Need to enable nullable in StyleEditorForm.cs
2. This page does not layout properly on high-resolution displays

**Review by Epica3055 — COMMENTED** [review]
looks good 👍

**Review by SimonZhao888 — DISMISSED** [review]

**Review by Tanya-Solyanik — COMMENTED** [review]
Looks good, I added minor styling comments

**Review by Tanya-Solyanik — APPROVED** [review]
Nice cleanup, thank you!

**Pull request merged**
