### PR TITLE
Enhance code to use Span<byte>

### PR DESCRIPTION
**Pull request by raffaeler**
This pull request includes a couple of overloads taking Span<byte> in addition to byte[], and a couple of optimizations to avoid copying memory (thanks to Span<byte>).

### CODE REVIEW

**Comment by AdamYoblick** [comment]
Closed by accident, one sec please

**Comment by AdamYoblick** [comment]
@raffaeler please reopen this, I closed and thought I could reopen.

**Comment by AdamYoblick** [comment]
Actually I think you need to re-push from your fork and you should be able to re-open this, sorry for the inconvenience.

**Comment by raffaeler** [comment]
In theory I should be able to reopen after commenting ... let's see

**Comment by raffaeler** [comment]
@AdamYoblick looks like I have to create a new one, but I can't see how to do it since this is already in place. Do you have any suggestions please?

**Comment by zsd4yr** [comment]
Searching on Google. There doesn't appear to be a way to do this. Should probably just open a new PR and link to this one at the beginning --so sorry about that @raffaeler

**Comment by raffaeler** [comment]
@zsd4yr It looks like my forked repo "lost" the status of forked so I cannot create a pull request anymore.
Did you orphaned the forked repositories in some way?
I guess I should now create a new fork and the push the files from my local files ... and this will require some times. Does it sounds the correct path to you?

**Comment by AdamYoblick** [comment]
@karelz Are you able to provide guidance here? I closed this with the intention of reopening it (since the name of our CI build changed and the PR was blocked), but now I can't reopen and neither can raf.

**Comment by raffaeler** [comment]
@AdamYoblick I had to re-fork the repo because my previous fork got orphaned.
I now re-submitted the changes I had locally and re-created the pull request.
Crossing fingers :)

**Comment by KlausLoeffelmann** [comment]
Without really having taken a deeper look here: Would adding/refactoring things to Span<t> (and its kind) in general impact the ability to consume APIs from Visual Basic?

**Pull request closed without merging**
