### PR TITLE
Simplify flag paths in codecov.yml

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by zsd4yr** [comment]
It may need to be **, not sure

**Comment by sharwell** [comment]
Looks like this change did not work. The file seemed to validate correctly, but the uploads aren't rendering correctly.

**Comment by zsd4yr** [comment]
not sure if it's an artifact of the documentation, but https://docs.codecov.io/docs/path-regexp seems to add dots

**Comment by sharwell** [comment]
@zsd4yr From the validate tool, it seemed correct. However, when I reviewed the coverage report itself the flags were not correctly applied. Since the current form works well I just closed this and didn't look further.

**Pull request closed without merging**
