### PR TITLE
Add VisualStyleElement tests

### PR DESCRIPTION
**Pull request by hughbe**

### CODE REVIEW

**Comment by danmosemsft** [comment]
Nice coverage improvement. For the implementation formatting, instead of 
```c#
                public static VisualStyleElement Normal
                {
                    get
                    {
                        if (normal == null)
                        {
                            normal = new VisualStyleElement(className, part, 1);
                        }

                        return normal;
                    }
                }
```
what do you think of
```c#
                public static VisualStyleElement Normal
                {
                    get => normal = normal ?? new VisualStyleElement(className, part, 1);
                  }
```
That would make these substantially shorter without being less readable, I think.

**Comment by danmosemsft** [comment]
My suggestion: remove the implementation changes from the PR, and submit them after the tests. That makes it simpler and it's also obvious that the tests pass against the existing implementation before it's changed.

**Comment by weltkante** [comment]
Saw this recently on another pull request in winforms I think, might be applicable here as well:
```C#
public static VisualStyleElement Normal
{
    get => normal ??= new VisualStyleElement(className, part, 1);
}
```

**Comment by hughbe** [comment]
Now a test only PR

**Comment by RussKie** [comment]
> ```cs
> public static VisualStyleElement Normal
> {
>     get => normal ??= new VisualStyleElement(className, part, 1);
> }
> ```

It is surely shorter, but is it more readable?

**Comment by hughbe** [comment]
Unrelated failure:
> System.Windows.Forms.Tests.BindingContextTests.BindingContext_Contains_DataSource_ReturnsExpected(context: [System.Collections.DictionaryEntry], dataSource: DataSource { Property = 0 }, expected: True)

Likely an issue with `WeakReference` (test bug). Any ideas how to fix

**Comment by zsd4yr** [comment]
> Unrelated failure:
> 
> > System.Windows.Forms.Tests.BindingContextTests.BindingContext_Contains_DataSource_ReturnsExpected(context: [System.Collections.DictionaryEntry], dataSource: DataSource { Property = 0 }, expected: True)
> 
> Likely an issue with `WeakReference` (test bug). Any ideas how to fix

@AdamYoblick thoughts?

**Comment by AdamYoblick** [comment]
I'm not sure, was this test working before?

**Comment by hughbe** [comment]
Yes, it is flakey I think because the implementation uses WeakReferences. I think i have a fix and have submitted a PR

**Pull request merged**
