### PR TITLE
Accessibility: NRE announcing changed item in `PropertyGrid`

### LINKED ISSUE #1997: Application crash on submitting new value to PropertyGrid item
**Note:** Issue can be reproduced in case PropertyGrid is recreated on the moment of submitting new cell value.

**Repro steps:**
1. Create .NET Core Winforms app with PropertyGrid control.
2. Bind data value changing with PropertyGrid recreating.
3. Run the app and try access some properties.

**Actual:** application crash with null-reference exception.
**Expected:** no crash.

DevDiv bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/962676

### PR DESCRIPTION
**Pull request by M-Lipin**
Fixes #1997 

## Proposed changes

- Adding test for null before announcement changed item details as changed item can be disposed in case Property grid is recreated on new value submit.
- Announcement is not broken and this case is rare. It is ok to not announce the value of disposed and recreated PropertyGrid.

## Customer Impact

- Customers will not experience application crash in case the PropertyGrid control can be recreated in Form lifecycle.

## Regression? 

- Yes (before introducing announcements for PropertyGrid value updates there was no issue)

## Risk

- None (just one additional null value test)

### Before

Crash stack:
```cs
  System.Windows.Forms.dll!System.Windows.Forms.PropertyGridInternal.PropertyGridView.GridViewEdit.ProcessDialogKey(System.Windows.Forms.Keys keyData) Line 6808 C# Symbols loaded.
  System.Windows.Forms.dll!System.Windows.Forms.PropertyGridInternal.PropertyGridView.GridViewEdit.OnKeyDown(System.Windows.Forms.KeyEventArgs ke) Line 6693 C# Symbols loaded.
  System.Windows.Forms.dll!System.Windows.Forms.Control.ProcessKeyEventArgs(ref System.Windows.Forms.Message m) Line 10649 C# Symbols loaded.
  System.Windows.Forms.dll!System.Windows.Forms.Control.ProcessKeyMessage(ref System.Windows.Forms.Message m) Line 10695 C# Symbols loaded.
  System.Windows.Forms.dll!System.Windows.Forms.Control.WmKeyChar(ref System.Windows.Forms.Message m) Line 13328 C# Symbols loaded.
```

### After

No crash.

## Test methodology 

- Manual testing.
- Automation testing (to be run)
- Unit tests (to be implemented)

## Test environment(s) 

.NET Core SDK (reflecting any global.json):
Version: 3.1.100-preview1-014044
Commit: dca04e7030
Runtime Environment:
OS Name: Windows
OS Version: 10.0.18362
OS Platform: Windows

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/1998)

### CODE REVIEW

**Comment by merriemcgaw** [comment]
Approved in tactics

**Comment by zsd4yr** [comment]
@msftbot please merge after 24 hours

**Comment by zsd4yr** [comment]
@msftbot nevermind.

Tactics has technically not opened the 3.1 gate yet

**Comment by RussKie** [comment]
@zsd4yr we're still waiting for QA sign off, so we shouldn't be merging it just yet

**Comment by merriemcgaw** [comment]
@Vino-Wang has CTI picked up this PR yet?

**Comment by Vino-Wang** [comment]
@merriemcgaw, we got it today, will test it and update test results in Teams thread.

**Comment by M-Lipin** [comment]
Rebased on top of release/3.1 to get all new fixes in the feature branch.

**Comment by M-Lipin** [comment]
Fix passed QA verification.

**Pull request merged**
