### PR TITLE
Ensure application is idle before sending mouse input.

### PR DESCRIPTION
**Pull request by dreddy-work**
draft

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8993)

### CODE REVIEW

**Comment by sharwell** [comment]
This _shouldn't_ make a difference because the messages are going to get queued whether or not the application is ready to receive them. Interested to see the results though.

**Comment by dreddy-work** [comment]
> This _shouldn't_ make a difference because the messages are going to get queued whether or not the application is ready to receive them. Interested to see the results though.

What i see in one of the screenshots is, a circling mouse pointer and mouse is not on the location expected. Test failed. Wanted to check if this was happening before sending mouse input or after.

15 28 34-ButtonTests Button_Anchor_ResizeOnWindowSizeWiderAsync-TrueException

**Comment by dreddy-work** [comment]
My hunch is right. WaitForIdle might be looking for application Idle but not the system Idle? @sharwell. What do you think waiting on Cursor state little longer when required?  

System.Exception: Timed out and Cursor is still busy.
   at System.Windows.Forms.UITests.ControlTestBase.WaitForIdleAsync() in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 172
   at System.Windows.Forms.UITests.SendInput.SendAsync(Form window, Action`1 actions) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/SendInput.cs:line 83
   at System.Windows.Forms.UITests.ControlTestBase.MoveMouseAsync(Form window, Point point, Boolean assertCorrectLocation) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 205
   at System.Windows.Forms.UITests.ListViewTests.<>c__DisplayClass1_0.<<ListView_CheckBox_DoubleClick_WorksExpectedAsync>b__0>d.MoveNext() in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs:line 35
--- End of stack trace from previous location ---
   at System.Windows.Forms.UITests.ControlTestBase.<>c__DisplayClass31_0`1.<<RunFormAsync>b__0>d.MoveNext() in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 316

**Pull request closed without merging**
