### PR TITLE
Add more combinations of REFLECT with other values in WM enum

### PR DESCRIPTION
**Pull request by gpetrou**
## Proposed changes

- Add more combinations of REFLECT with other values in WM enum.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3448)

### CODE REVIEW

**Comment by gpetrou** [comment]
In CheckedListBox, we currently have:
WM.REFLECT | WM.CHARTOITEM
WM.REFLECT | WM.VKEYTOITEM
Does this need to change instead?

**Comment by weltkante** [comment]
These are special, you cannot combine arbitrary window messages and expect working results. At the end of the file someone started coding those as combined constants instead, see `REFLECT_NOTIFY = REFLECT + NOTIFY`. Thats the approach I'd be taking, but I'll leave it up for @JeremyKuhne to comment further on this.

Just wanted to put on a warning that turning this enum into "flags" is counterproductive because the debugger will assume you can combine arbitrary messages and when seeing an unknown message it'll try to "guess" that its a combination of unrelated messages (which it isn't)

**Comment by JeremyKuhne** [comment]
> At the end of the file someone started coding those as combined constants instead

I'd follow this pattern for clarity and consistency. We can't do this for registered messages as they can't be put in the enum, so those would be the only exceptions (I think we have a few that we reflect).

Closing this PR as `[Flags]` isn't correct in this case.

**Comment by RussKie** [comment]
Thank you @gpetrou, but a better approach would be introduce new enum members, e.g. `User32.WM.REFLECT | User32.WM.DRAWITEM` -> `User32.WM.REFLECT_DRAWITEM => REFLECT + DRAWITEM`.

**Comment by RussKie** [comment]
You're welcome to update the PR, or close and raise a new one.

**Pull request merged**
