### PR TITLE
Add DataGridViewHeaderCell tests

### PR DESCRIPTION
**Pull request by hughbe**
## Proposed Changes
- Add DataGridViewHeaderCell tests
- Add parameter names to ArgumentExceptions

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3375)

### CODE REVIEW

**Comment by hughbe** [comment]
@weltkante @RussKie looking at https://dev.azure.com/dnceng/public/_build/results?buildId=666511&view=ms.vss-test-web.build-test-results-tab we have a bunch of (related) and runrelated failures
image
image
image


Do you have any idea why these would all crash? Could it be something to do with `Application.EnableVisualStyles` being called?

**Comment by weltkante** [comment]
> Could it be something to do with Application.EnableVisualStyles being called?

Well, yeah, you need to do that for the whole application or not at all, its not something you can do on a random thread. This is a process wide setting (static variable). To be honest I'd have expected that to already be turned on for the whole process, but I guess it isn't.

**Comment by hughbe** [comment]
I don't! Basically there are loads of different scenarios for each one as the code is super complicated! But most tests follow a similar pattern.

I do have a bunch of code snippets that generate templates :)
```cs
"DataColumn": {
    "prefix": "datacolumn",
    "body": [
        "using var control = new DataGridView();",
        "using var cellTemplate = new SubDataGridViewCell();",
        "using var column = new DataGridViewColumn",
        "{",
        "    CellTemplate = cellTemplate",
        "};",
        "control.Columns.Add(column);",
    ]
},
"DataRow": {
    "prefix": "datarow",
    "body": [
        "using var control = new DataGridView",
        "{",
        "    ColumnCount = 1,",
        "    RowCount = 1",
        "};",
        "DataGridViewRow row = control.Rows[0];",
    ]
},
"SharedDataRow": {
    "prefix": "shareddatarow",
    "body": [
        "using var control = new DataGridView",
        "{",
        "    ColumnCount = 1,",
        "    RowCount = 1",
        "};",
        "DataGridViewRow row = control.Rows.SharedRow(0);",
    ]
},
"CellWithDataGridView": {
    "prefix": "cellwithdatagridview",
    "body": [
        "using var cellTemplate = new SubDataGridViewCell();",
        "using var column = new DataGridViewColumn",
        "{",
        "    CellTemplate = cellTemplate",
        "};",
        "using var control = new DataGridView();",
        "control.Columns.Add(column);",
        "DataGridViewCell cell = control.Rows[0].Cells[0];"
    ]
},
"CellWithColumn": {
    "prefix": "cellwithcolumn",
    "body": [
        "using var column = new DataGridViewColumn();",
        "using var cell = new DataGridViewColumnHeaderCell();",
        "column.HeaderCell = cell;"
    ]
},
"CellWithRow": {
    "prefix": "cellwithrow",
    "body": [
        "using var row = new DataGridViewRow();",
        "using var cell = new SubDataGridViewCell();",
        "row.Cells.Add(cell);"
    ]
},
```

etc which speeds it up a lot

**Comment by RussKie** [comment]
Ripper!
You need to do a blog post or a brown bag on how you do this.

**Pull request merged**
