### PR TITLE
[Translation] Adding default DataGridView cells ToolTip text to resources

### PR DESCRIPTION
**Pull request by vladimir-krestov**
&#x1F53A; **_Needs review translation!_** &#x1F53A;

## Proposed changes

- Add default DataGridView cell ToolTip text to the translations will be ready for release 3.0. 
Then these resources will be used in PR #1681.

## Customer Impact

- No

## Regression? 

- No

## Risk

- No

## Gif
Defaults

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/1836)

### CODE REVIEW

**Comment by zsd4yr** [comment]
@jkotas

**Comment by zsd4yr** [comment]
@vladimir-krestov I don't think this meets the bar for 3.0 at this point. Can you complete PR #1681 without this change?

**Comment by zsd4yr** [comment]
@RussKie I think it is too late to take these kinds of changes.

**Comment by vladimir-krestov** [comment]
It was decided that these changes will be added with #1681 in release 3.1.

**Pull request closed without merging**
