### PR TITLE
Prep'ing for 3.0.1 set the next patch release to 3.0.1

### PR DESCRIPTION
**Pull request by RussKie**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/1969)

### CODE REVIEW

**Comment by RussKie** [comment]
@mmitche we don't have `StabilizePackageVersion` prop set at all, is it critical?

**Comment by vatsan-madhavan** [comment]
> @mmitche we don't have `StabilizePackageVersion` prop set at all, is it critical?

That’s odd - do you treat your project template package as a shipping package?

**Comment by mmitche** [comment]
Nope, everything in this repo is non-stabilized.  Leave as is.

**Comment by RussKie** [comment]
> do you treat your project template package as a shipping package?

No, we mark them slightly differently. @mmitche did it in #1841

**Comment by vatsan-madhavan** [comment]
Do you produce project template packages with 4.8.0 prefix ?

**Comment by RussKie** [comment]
> Do you produce project template packages with 4.8.0 prefix ?

No. Should we?

**Comment by vatsan-madhavan** [comment]
> > Do you produce project template packages with 4.8.0 prefix ?
> 
> No. Should we?

No, you're doing fine. How are you updating the prefix for project templates to 3.0.1 then?

**Comment by vatsan-madhavan** [comment]
It turns out that your project templates do have a version prefix of 4.8.0 - so there is nothing to be done there either for now. 

This is what your package names would look like in release/3.0: 

```
Microsoft.Dotnet.WinForms.ProjectTemplates.4.8.0-servicing.19475.1
Microsoft.Private.Winforms.4.8.0-servicing.19475.1
```

You really didn't need `4.8.0` prefix for `Microsoft.Dotnet.WinForms.ProjectTemplates`, but it makes sense for `Microsoft.Private.Winforms` (and only that - for .NET Framework compatibility). `Microsoft.Dotnet.WinForms.ProjectTemplates` probably could just use `3.0.x` prefix to indicate that it is part of .NET Core 3.x product... 

I wouldn't change this now (esp. not in release/3.0, which is short-lived). You can consider updating it in release/3.1 at your discretion. Given these are transport packages, I'm not convinced that changing anything is absolutely essential. That said, the change is likely as simple as adding `<VersionPrefix>3.0.1</VersionPrefix>` in the corresponding `.csproj`. 

/cc @ericstj

**Comment by ericstj** [comment]
Don't go backwards if you've already used 4.x.  Fix it in 5.0

**Pull request merged**
