### PR TITLE
Refactor `ControlCollection.AddRange` to use `params` keyword

### LINKED ISSUE #8938: [API Proposal]: Allow ControlCollection.AddRange to use params keyword.
### Background and motivation

Currently [Control.ControlCollection.AddRange](https://github.com/dotnet/winforms/blob/a37c1817d3f965d9a8bdd3d89fd0b98609715e84/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs#L153) method is accepting an array of `Control`, this means each time that we want to add multiple controls at once, we have to make a new array. By using `params` keyword using this method will become easier.

### API Proposal

- Add `params` keyword to all collection `AddRange` methods that don't already have it.

```csharp
namespace System.Windows.Forms;

public class Control
{
    public class ControlCollection
    {
        public virtual void AddRange(params Control[] controls);
    }
}
```

Likewise we want to update our other collections that have an [`AddRange`](https://github.com/dotnet/winforms/pull/8928#issuecomment-1495242738):

``` C#
// Note that parameter names are left as they currently are.

System.ComponentModel.Design.DesignerActionListCollection.AddRange(params DesignerActionList[] value)
System.Windows.Forms.AutoCompleteStringCollection.AddRange(params string[] value)
System.Windows.Forms.ComboBox.ObjectCollection.AddRange(params object[] items)
System.Windows.Forms.Design.Behavior.BehaviorServiceAdornerCollection.AddRange(params Adorner[] value)
System.Windows.Forms.Design.Behavior.GlyphCollection.AddRange(params Glyph[] value)
System.Windows.Forms.ImageList.ImageCollection.AddRange(params Image[] images)
System.Windows.Forms.ListBox.IntegerCollection.AddRange(params int[] items)
System.Windows.Forms.ListBox.ObjectCollection.AddRange(params object[] items)
System.Windows.Forms.ListView.ListViewItemCollection.AddRange(params ListViewItem[] items)
System.Windows.Forms.ListView.ColumnHeaderCollection.AddRange(params ColumnHeader[] values)
System.Windows.Forms.ListViewGroupCollection.AddRange(params ListViewGroup[] groups)
System.Windows.Forms.ListViewItem.ListViewSubItemCollection.AddRange(params ListViewSubItem[] items)
System.Windows.Forms.ListViewItem.ListViewSubItemCollection.AddRange(params string[] items)
System.Windows.Forms.TabControl.TabPageCollection.AddRange(params TabPage[] pages)
System.Windows.Forms.ToolStripItemCollection.AddRange(params ToolStripItem[] toolStripItems)
System.Windows.Forms.ToolStripPanel.ToolStripPanelRowCollection.AddRange(params ToolStripPanelRow[] value)
System.Windows.Forms.TreeNodeCollection.AddRange(params TreeNode[] nodes)

```

### API Usage

```csharp
this.Controls.AddRange(this.BtnControl1, this.BtnControl2);
```

### Risks

No known risks.

### Will this feature affect UI controls?

- No, VS Designer doesn't need to support this feature.
- The impact will be easier use of this method by users.
- No, this feature doesn't need to be localized.

### PR DESCRIPTION
**Pull request by elachlan**
Add `params` keyword to arguments of `ControlCollection.AddRange` method.

Fixes #8938

Based on: #8928

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/9620)

### CODE REVIEW

**Comment by elachlan** [comment]
CC: @dreddy-work

**Comment by dreddy-work** [comment]
build failed.

**Comment by elachlan** [comment]
@dreddy-work I think there is a flaky test?
```
xUnit.net Console Runner v2.4.2+f110e5bee5 (32-bit .NET 8.0.0-rc.1.23381.1)
  Discovering: System.Windows.Forms.Tests
  Discovered:  System.Windows.Forms.Tests
  Starting:    System.Windows.Forms.Tests
    System.Windows.Forms.Tests.TabPageTests.TabPage_BackColor_GetVisualStyles_ReturnsExpected [SKIP]
      Crash with AbandonedMutexException. See: https://github.com/dotnet/arcade/issues/5325
    System.Windows.Forms.Tests.TabPageTests.TabPage_BackColor_GetVisualStylesWithParent_ReturnsExpected [SKIP]
      Crash with AbandonedMutexException. See: https://github.com/dotnet/arcade/issues/5325
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.Thread.get_CurrentThread()
   at System.Windows.Forms.Application.ThreadContext.OleRequired() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 801
   at System.Windows.Forms.Application.OleRequired() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1079
   at System.Windows.Forms.Application.ThreadContext.<get_ComponentManager>g__GetExternalComponentManager|42_0() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 178
   at System.Windows.Forms.Application.ThreadContext.get_ComponentManager() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 148
   at System.Windows.Forms.Application.ThreadContext.FormActivated(Boolean activate) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 683
   at System.Windows.Forms.Application.FormActivated(Boolean modal, Boolean activated) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 931
   at System.Windows.Forms.Form.WmActivate(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 6109
   at System.Windows.Forms.Form.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 6627
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 64
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 113
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 373
--- End of stack trace from previous location ---
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception ex) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 848
   at System.Windows.Forms.Application.OnThreadException(Exception t) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1085
   at System.Windows.Forms.Control.WndProcException(Exception e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 13285
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 58
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 387
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.Thread.get_CurrentThread()
   at System.Windows.Forms.Application.ThreadContext.OleRequired() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 801
   at System.Windows.Forms.Application.OleRequired() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1079
   at System.Windows.Forms.Application.ThreadContext.<get_ComponentManager>g__GetExternalComponentManager|42_0() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 178
   at System.Windows.Forms.Application.ThreadContext.get_ComponentManager() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 148
   at System.Windows.Forms.Application.ThreadContext.FormActivated(Boolean activate) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 683
   at System.Windows.Forms.Application.FormActivated(Boolean modal, Boolean activated) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 931
   at System.Windows.Forms.Form.WmActivate(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 6109
   at System.Windows.Forms.Form.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 6627
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 64
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 113
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 373
--- End of stack trace from previous location ---
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception ex) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 848
   at System.Windows.Forms.Application.OnThreadException(Exception t) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1085
   at System.Windows.Forms.Control.WndProcException(Exception e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 13285
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 58
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 387
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.Thread.get_CurrentThread()
   at System.Windows.Forms.Application.ThreadContext.OleRequired() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 801
   at System.Windows.Forms.Application.OleRequired() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1079
   at System.Windows.Forms.Application.ThreadContext.<get_ComponentManager>g__GetExternalComponentManager|42_0() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 178
   at System.Windows.Forms.Application.ThreadContext.get_ComponentManager() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 148
   at System.Windows.Forms.Application.ThreadContext.FormActivated(Boolean activate) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 683
   at System.Windows.Forms.Application.FormActivated(Boolean modal, Boolean activated) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 931
   at System.Windows.Forms.Form.WmActivate(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 6109
   at System.Windows.Forms.Form.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 6627
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 64
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 113
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 373
--- End of stack trace from previous location ---
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception ex) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 848
   at System.Windows.Forms.Application.OnThreadException(Exception t) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1085
   at System.Windows.Forms.Control.WndProcException(Exception e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 13285
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 58
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 387
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.Thread.get_CurrentThread()
   at System.Windows.Forms.Application.ThreadContext.OleRequired() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 801
   at System.Windows.Forms.Application.OleRequired() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1079
   at System.Windows.Forms.Application.ThreadContext.<get_ComponentManager>g__GetExternalComponentManager|42_0() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 178
   at System.Windows.Forms.Application.ThreadContext.get_ComponentManager() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 148
   at System.Windows.Forms.Application.ThreadContext.FormActivated(Boolean activate) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 683
   at System.Windows.Forms.Application.FormActivated(Boolean modal, Boolean activated) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 931
   at System.Windows.Forms.Form.WmActivate(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 6109
   at System.Windows.Forms.Form.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 6627
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 64
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 113
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 373
--- End of stack trace from previous location ---
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception ex) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 848
   at System.Windows.Forms.Application.OnThreadException(Exception t) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1085
   at System.Windows.Forms.Control.WndProcException(Exception e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 13285
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 58
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 387
```

**Comment by dreddy-work** [comment]
yes. https://github.com/dotnet/winforms/issues/9379

**Comment by elachlan** [comment]
@dreddy-work are you happy with this pr? any feedback?

**Review by dreddy-work — APPROVED** [review]
LGTM.

**Comment by elachlan** [comment]
@dreddy-work I think this is causing failures in the branch:
https://github.com/dotnet/winforms/pull/9703/checks?check_run_id=15769872416
```
src\System.Windows.Forms\src\System\Windows\Forms\TreeNodeCollection.cs(212,25): error RS0036: (NETCORE_ENGINEERING_TELEMETRY=Build) Symbol 'virtual System.Windows.Forms.TreeNodeCollection.AddRange(params System.Windows.Forms.TreeNode![]! nodes) -> void' is missing nullability annotations in the declared API (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md)
```

**Comment by elachlan** [comment]
@Tanya-Solyanik can you please have a look at the failure above? I think this is why no PRs are automerging for .net9 branch.

**Pull request merged**
