### PR TITLE
Fix RichTextBox Rtf encoding

### LINKED ISSUE #3032: RichTextBox Rtf property wrong converting non ascii chars
* .NET Core Version: 3.1.2

* Have you experienced this same bug with .NET Framework?: **No**

**Problem description:**
After assigning to `richTextBox.Rtf` some rtf code with nonbreaking space (160 char code), RichTextBox converts it to `\'c2\~` insted of `\~`.
Snipaste_2020-04-02_15-01-27

Due to the fact that, number formatting like `:N` using nonbreaking space for thousand separators (in appropriate cultures) this lead to huge problems :((((

**Expected behavior:**
Nonbreaking space must be properly converted to `\~`.

Windows 7 x64.

**Minimal repro:**
[WinFormsCoreTest2.zip](https://github.com/dotnet/winforms/files/4420952/WinFormsCoreTest2.zip)

### PR DESCRIPTION
**Pull request by JeremyKuhne**
.NET Core Encoding.Default gets UTF-8, not the default code page. Change our code to get the code page as we're sending
data to the control as ASCII.

Ultimately we should remove all non-Unicode codePaths in RichTextBox. This should be possible as we're force loading the latest RichEdit.

Fixes #3032

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3100)

### CODE REVIEW

**Comment by weltkante** [comment]
> Ultimately we should remove all non-Unicode codePaths in RichTextBox. This should be possible as we're force loading the latest RichEdit.

I have been wondering if thats possible, the [docs](https://docs.microsoft.com/en-us/windows/win32/controls/em-streamin) look like it isn't (it says `SF_UNICODE` only should be combined with `SF_TEXT`, but loading RTF requires using `SF_RTF`). I'm not entirely sure whether RTF is a binary format or a text format, if its only a binary format that happens to support roundtrip via text this means encoding is part of the header (wordpad certainly saves an encoding in the RTF header but I don't know what it is used for). Since the RTF is user provided you can't change the header without touching the rest of the data and I don't think WinForms wants to parse and reencode the RTF stream. I'd be happy to be mistaken though in case RTF is not only a binary format but also a text format (i.e. its code points are not restricted to bytestreams and its just badly documented).

**Comment by JeremyKuhne** [comment]
Release build test run timed out- I can't find anything in the logs / artifacts that clue me into where it might have hung up. @AdamYoblick or @RussKie any ideas on info I might be missing?

**Comment by RussKie** [comment]
Very much related to https://github.com/dotnet/winforms/issues/3095 and others (e.g. https://github.com/dotnet/winforms/issues/3090, https://github.com/dotnet/winforms/issues/3062, https://github.com/dotnet/winforms/issues/2192 and https://github.com/dotnet/winforms/pull/3064)

**Pull request merged**
