### PR TITLE
Fix a stray apostrophe

### LINKED ISSUE #198: Strange Encoding Issues
When cloning and opening the code base for the first time, on macOS 10.14.1, strange encoding issues appear. A few were fixed in another PR, but here's a list of the others I found.

screen shot 2018-12-06 at 9 56 24 am

#155 @Tanya-Solyanik

### PR DESCRIPTION
**Pull request by RussKie**
Convert the file from UTF-8 to UTF-8-BOM

contributes to #198

### CODE REVIEW

**Comment by zsd4yr** [comment]
@RussKie should something be done to .editorconfig to ensure newly edited files do not create more of this issue?

**Comment by sharwell** [comment]
@zsd4yr It's already done. Someone just needs to update the existing files in the repository. I have a script if you want me to send a PR.

**Comment by zsd4yr** [comment]
Thanks you @RussKie

**Comment by sharwell** [comment]
📝 This encoding mistake was caused in 15cda680cff86c1d7654f8dd675249733d002b94 when an editor incorrectly opened an ANSI-encoded file as UTF-8.

**Comment by RussKie** [comment]
Made obsolete by #487

**Pull request closed without merging**
