### PR TITLE
Extract AxHost nested classes

### PR DESCRIPTION
**Pull request by hughbe**
Pull them out into their own files

Diff is a bit weird sadly

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/2179)

### CODE REVIEW

**Comment by RussKie** [comment]
Just to confirm - no functional changes, just cut-n-paste verbatim?

**Comment by hughbe** [comment]
Correct :)

**Comment by zsd4yr** [comment]
@msftbot please merge if @RussKie approves

**Comment by RussKie** [comment]
Looks like a test is failing:

```
xUnit.net Console Runner v2.4.1 (64-bit .NET Core 5.0.0-alpha1.19524.4)
  Discovering: System.Windows.Forms.Tests
  Discovered:  System.Windows.Forms.Tests
  Starting:    System.Windows.Forms.Tests
    System.Windows.Forms.Tests.ApplicationTests.Application_VisualStyleState_Set_ReturnsExpected [SKIP]
      Deadlock, see: https://github.com/dotnet/winforms/issues/2192
Process terminated. Assertion Failed
must have the ocx
   at System.Windows.Forms.AxHost.GetOleObject() in C:\Development\winforms\src\System.Windows.Forms\src\System\Windows\Forms\AxHost.cs:line 3985
   at System.Windows.Forms.AxHost.DoVerb(Int32 verb) in C:\Development\winforms\src\System.Windows.Forms\src\System\Windows\Forms\AxHost.cs:line 2396
   at System.Windows.Forms.Tests.AxHostTests.<>c__DisplayClass67_0.<AxHost_DoVerb_InvokeWithoutHandle_ThrowsNullReferenceException>b__0() in C:\Development\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\AxHostTests.cs:line 949
   at Xunit.Assert.RecordException(Action testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Record.cs:line 28
   at Xunit.Assert.Throws[T](Action testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 27
   at System.Windows.Forms.Tests.AxHostTests.AxHost_DoVerb_InvokeWithoutHandle_ThrowsNullReferenceException(Int32 verb) in C:\Development\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\AxHostTests.cs:line 949
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 150
   at Xunit.Sdk.UITestInvoker.<>c__DisplayClass4_0.<InvokeTestMethod>b__1()
   at Xunit.Sdk.ExecutionTimer.Aggregate(Action action) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 31
   at Xunit.Sdk.UITestInvoker.<>c__DisplayClass4_0.<InvokeTestMethod>b__0()
   at Xunit.Sdk.ExceptionAggregator.Run(Action code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 73
   at Xunit.Sdk.UITestInvoker.InvokeTestMethod(Object testClassInstance)
   at Xunit.Sdk.UITestInvoker.<>c__DisplayClass2_0.<RunAsync>b__1()
   at Xunit.Sdk.ExceptionAggregator.Run(Action code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 73
   at Xunit.Sdk.UITestInvoker.<RunAsync>b__2_0()
   at Xunit.Sdk.UITestInvoker.<>c__DisplayClass3_0.<RunOnSTA>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

=== COMMAND LINE ===
"C:\Development\winforms\.dotnet\dotnet.exe" exec --depsfile "C:\Development\winforms\artifacts\bin\System.Windows.Forms.Tests\Debug\netcoreapp5.0\System.Windows.Forms.Tests.deps.json" --runtimeconfig "C:\Development\winforms\artifacts\bin\System.Windows.Forms.Tests\Debug\netcoreapp5.0\System.Windows.Forms.Tests.runtimeconfig.json"  "C:\Users\igveliko\.nuget\packages\xunit.runner.console/2.4.1/tools/netcoreapp2.0/xunit.console.dll" "C:\Development\winforms\artifacts\bin\System.Windows.Forms.Tests\Debug\netcoreapp5.0\System.Windows.Forms.Tests.dll" -noautoreporters -xml "C:\Development\winforms\artifacts\TestResults\Debug\System.Windows.Forms.Tests_netcoreapp5.0_x64.xml" -html "C:\Development\winforms\artifacts\TestResults\Debug\System.Windows.Forms.Tests_netcoreapp5.0_x64.html"  > "C:\Development\winforms\artifacts\log\Debug\System.Windows.Forms.Tests_netcoreapp5.0_x64.log" 2>&1
```

**Comment by hughbe** [comment]
Derp, didn't fix the merge conflicts properly

**Pull request merged**
