### PR TITLE
Enabling NRT for SWF (no API changes yet)

### PR DESCRIPTION
**Pull request by Logerfo**
Work for #1107.
Refers to #2678.
Relates to #2676.

---
## Changes
- Added `<Nullable>enable</Nullable>` to `System.Windows.Forms.csproj`.
- Added `#nullable disable` to every `src/System.Windows.Forms/src/**/*.cs` file header.

## Next steps
- First we have to make sure this PR implies no API changes. (#2705)
- After merging this one, then multiple PRs can be issued annotating few scoped and targeted API changes at a time.

---
cc @Russkie @sharwell @hughbe

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/2702)

### CODE REVIEW

**Comment by Logerfo** [comment]
I just did a full eye-check on the API and found a couple of changes: one for a file I had considered as safe and the other one for a file I forgot to edit.
I don't think their changes were relevant (only `[NullableContext(1)][Nullable(0)]` at class site), but "[reverted](34119a4a6555b90a4fbc81f0fdc4e14f03aa35fa)" them anyway, just for the sake of it.
I'd call the PR API-changeless, but I'd rather be sure with some sort of currently lacking automated API-diffing.

**Comment by RussKie** [comment]
I will need to get #2705 before this can go in.

**Comment by Logerfo** [comment]
Oh, I didn't know about that txt files feature. That's exactly what I needed for the API diff. While rebasing, I removed that change from this branch and also filed #2708. After merged, this branch (and #2676) can be rebased again and the diagnosis will tell us if we have any undesired API changes (my local merge tells me we don't).

**Comment by Logerfo** [comment]
@RussKie rebasing didn't throw any warning, I guess we're good to go.

**Comment by RussKie** [comment]
Let's breaking it up in two:
- the first PR adds `#nullable disable` (the commits 1 and 2), and 
- the second one - removed decorations where safe (the commit 3 and 4). 

Right now commit 53bac09def1dc10c0674e5bdd39636e3c476dd92 undo changes made in dfd4820ab5f5947d0efc9784a74e9bc9096b69f8.

**Comment by Logerfo** [comment]
@RussKie done. This PR is acting as the first one you mentioned. I'm ready to send the other one once this one is merged.

**Comment by Logerfo** [comment]
Missed a new file from 9dc2a1d01e1f7b2383acd232665307d9adec50b3. It's an internal class, so it didn't show up in the API diff.

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
