### PR TITLE
Use generic lists in MonthCalendar

### PR DESCRIPTION
**Pull request by gpetrou**
## Proposed changes

- Use generic lists in MonthCalendar.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3483)

### CODE REVIEW

**Comment by gpetrou** [comment]
Is it OK to change the NotSame asserts in tests or I should use Clone instead of just ToArray in the affected properties?

**Comment by RussKie** [comment]
I see that few tests failed:
```
    System.Windows.Forms.Tests.MonthCalendarTests.MonthCalendar_MonthlyBoldedDates_SetWithHandle_GetReturnsExpected(value: null, expected: []) [FAIL]
      Assert.NotSame() Failure
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\MonthCalendarTests.cs(1522,0): at System.Windows.Forms.Tests.MonthCalendarTests.MonthCalendar_MonthlyBoldedDates_SetWithHandle_GetReturnsExpected(DateTime[] value, DateTime[] expected)
```

And it appears the fail on this line:
https://github.com/dotnet/winforms/blob/7a54b537d0c3a495bab705a546717dffa048084c/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs#L1522

I'm a little surprised that multiple calls to `List<T>.ToArray()` are returning the same object (there's probably a logical explanation to it). 

I'd start with a little experiment to confirm this:
```cs
var a1 = calendar.MonthlyBoldedDates;
var a2 = calendar.MonthlyBoldedDates;
Assert(a1 == a2);
a1[0] = DateTime.Parse(2020, 1, 1);
a2[0] = DateTime.Parse(2020, 2, 1);
Assert(a1[0] == DateTime.Parse(2020, 1, 1));
```

**Comment by gpetrou** [comment]
As per my previous question, I wasn't sure what to do. Looking at your comment, looks like I should leave the tests as they are and make a copy of the array instead every time that the property is called? This seems a bit inefficient, but I guess it is a breaking change to not to do so?

**Comment by RussKie** [comment]
First I'd like to verify the strange observations.
Both `Clone` and `ToArray` will (supposed to) allocate new block of memory, so they both are inefficient. A better implementation would be to use something like a `ReadOnlyCollection` but that would be  a breaking change.

**Comment by gpetrou** [comment]
Looks like the arrays are empty both in master and the PR. Perhaps ToArray returns the same empty array while the current master always creates an empty array. Should I change the assert in that case?

**Comment by JeremyKuhne** [comment]
Yes, `List<T>.ToArray()` returns the [same static empty array](https://source.dot.net/#System.Private.CoreLib/List.cs,1030).

**Comment by RussKie** [comment]
> Yes, `List<T>.ToArray()` returns the [same static empty array](https://source.dot.net/#System.Private.CoreLib/List.cs,1030).

...only if it empty. Thank you

@gpetrou are the tests that fail, fail for empty arrays? If so, we need to fix the tests, else - we need to dig deeper.

**Comment by gpetrou** [comment]
Yes, the problem was empty arrays. I already did some changes and the tests pass now.

**Comment by RussKie** [comment]
Thank you, I should have noticed it was failing for the empty array 🤦‍♂️

**Pull request merged**
