### PR TITLE
Fix nested/User control scaling.

### LINKED ISSUE #6381: Anchors of user control don't work when scaling on high DPI
* .NET Core Version: 
6.0

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

When components are inside a user control, their anchors work incorrect when scaling. It affects a project a lot, because using docking instead of anchors for components inside a user control is difficult in some cases.
Scale 100%
scale100
Scale 150%
scale150

**Expected behavior:**
Anchors works well like it was on classic .NET.

**Minimal repro:**
Sample app is attached. Run it when screen is scaled 150% to reproduce the bug.
[ControlScalingBug.zip](https://github.com/dotnet/winforms/files/7756538/ControlScalingBug.zip)

### PR DESCRIPTION
**Pull request by dreddy-work**
Fixes #6381.

Nested controls are disabled for scaling once their parent layout is finished.
However, Parent might be reparented and could go through a new layout based on
 its parent's scale dimensions.

We are maintaining multiple flags around scaling here and can be cleaned but require full testing. Making a scoped fix here to limit the risk.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/6971)

### CODE REVIEW

**Review by JeremyKuhne — APPROVED** [review]
Looks ok. Presumably you'll give CTI a heads up on this one.

**Review by RussKie — COMMENTED** [review]
👍

**Review by Tanya-Solyanik — APPROVED** [review]

**Comment by dreddy-work** [comment]
Testing found that nested controls inside `TabControl` still has issues. Investigatin.

**Comment by dreddy-work** [comment]
Anchoring inside user control needs bigger change and can not make it to this release.  Taking this PR as-is.

**Pull request merged**
