### PR TITLE
change agent pools to deal with recent build delays

### PR DESCRIPTION
**Pull request by AdamYoblick**
No customer impact

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/1657)

### CODE REVIEW

**Comment by AdamYoblick** [comment]
Yep, its correct. The hosted pool has no child pool names. I had the exact same question when the change was made in the other repo 😆

**Comment by AdamYoblick** [comment]
Hi Igor, I'm not sure this needs a tell-mode label, I don't think shiproom even cares about it. This is a build infra change that has no bearing on the shipping bits, so it won't affect customers at all. There's zero risk since our other repo already made this change.

**Comment by RussKie** [comment]
My understanding all intra changes come as "tell-mode", whilst all prod-code changes comes as "ask-mode".

@Zach<mailto:Zachary.Danz@microsoft.com> can you please confirm?

E.g. the same in CoreFx - https://github.com/dotnet/corefx/pull/40380#issuecomment-522146053


________________________________

**Comment by RussKie** [comment]
Ah you could be right then. Zach will have to confirm. I just figured since it doesn’t affect the shipping bits at all, it’s not really a change they care about.

But I definitely could be wrong :)

________________________________

**Pull request merged**
