### PR TITLE
Global usings and file scoped namespaces

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Get more consistent with global usings and use file scoped namespaces through the repo.

Done with auto-fixers.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/9023)

### CODE REVIEW

**Review by merriemcgaw — APPROVED** [review]
This was done via autoamted tooling and we're confident of the change.

**Comment by JeremyKuhne** [comment]
@microsoft-github-policy-service

**Comment by JeremyKuhne** [comment]
@microsoft-github-policy-service agree

**Comment by JeremyKuhne** [comment]
Apologies for any conflict resolution needed from this. Now we're consistent though and should start always using file-scoped namespaces. It reduces nesting a level, which helps comprehension. We'll continue to work on reducing nesting complexity to make the code easier to understand and maintain.

**Pull request merged**
