### PR TITLE
Cannot find the RichEdit control of the "Text" property in UIA structure of a PropertyGrid control

### LINKED ISSUE #2704: Accessibility [Inspect]: Cannot find the RichEdit control of the "Text" property in UIA structure of a PropertyGrid control
* .NET Core Version: 

.NET Core 5.0.0-alpha.1.19564.1 (also reproduces in earlier versions of .NET Core WinForms.

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**

The issue is that RichEdit control is not shown in the UIA hierarchy of PropertyGrid control children.

image

**Expected behavior:**
RichEdit control (when shown) should appear in the PropertyGrid control's children hierarchy.

**Minimal repro:**
* Create WinForms app with PropertyGrid and Button control.
* Associate the button with PropertyGrid as a selected object.
* Run the app, type something in the RichEdit control control (this is a button's text input control) and inpsect the button with the Inspect tool. Observe that the input is not in the UIA hierarchy.

### PR DESCRIPTION
**Pull request by SergeySmirnov-Akvelon**
Adding PropertyGrid DropDown control holder and its child edit control to the UIA hierarchy of the PropertyGrid.

Fixes #2704

## Proposed changes
- Adding accessible object for PropertyGrid's DropDownControlHolder;
- Implementing accessible navigation to find DropDownControlHolder pane and its child edit control in UIA hierarchy in PropertyGrid.
- Adding resource to announce DropDownControlHolder pane accessible name to inform users that the currently edited RichEdit control or another edit control is hosted in PropertyGrid's DropDown control holder.

## Customer Impact
- Customers will be able to distinguish the dropped down control from another form controls if using Narrator or another screen reader.

## Regression? 

- No

## Risk
- Minimal

## Test methodology 
- Manual testing
- Unit tests
- UI tests
- CTI

## Test environment(s) 
- Microsoft Windows [Version 10.0.18363.900]
- .NET Core SDK 5.0.100-rc.1.20420.14

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3849)

### CODE REVIEW

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
@Pilchie: seeking permission to merge

**Comment by RussKie** [comment]
CTI approved

**Comment by Pilchie** [comment]
Approved for .NET 5 RC2.

**Pull request merged**
