### PR TITLE
[CSY] ‘Details’ and ‘Continue’ have the same hotkey "P" in unhandled exception

### LINKED ISSUE #6496: [CSY] ‘Details’ and ‘Continue’ have the same hotkey: P in unhandled exception dialog
.NET Core Version: 

- .NET SDK 7.0.100-alpha.1.22060.5 

Have you experienced this same bug with .NET Framework?: 

- No

**Problem description:**
‘Details’ and ‘Continue’ have the same hotkey: P
image

**Expected behavior:**
The hot key should be unique.
image

**Minimal repro:**
1.	Create a Winforms core project.
2.	Add a button control on Form designer.
3.	Double click the button and add following code: `throw new Exception("");` in `button_click` event handler.
4.	Run the project via pressing `Ctrl + F5`.
5.	Press `Alt` keyboard, then observe the hot key.
Or use the sample project with changing the target to 7.0.
[UnhandledExceptionDialog.zip](https://github.com/dotnet/winforms/files/7859386/UnhandledExceptionDialog.zip)

**More info:**
This issue can’t reproduce with ENU, CHS, CHT, DEU, ESN, FRA, JPN, ITA, KOR, PLK, PTB, RUS, TRK languages.

### PR DESCRIPTION
**Pull request by elachlan**
Fixes #6496

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8487)

### CODE REVIEW

**Comment by dreddy-work** [comment]
@jonfortescue, can we make changes like these, or this is something that loc team should aware and do it in automated process?

**Comment by jonfortescue** [comment]
@dreddy-work this is something the loc team needs to fix on their side for sure. You can file an issue with them here: https://aka.ms/ceLocBug

**Comment by dreddy-work** [comment]
> @dreddy-work this is something the loc team needs to fix on their side for sure. You can file an issue with them here: https://aka.ms/ceLocBug

If we take this change and then file an issue at loc repo, does loc process override this in the meanwhile?

**Comment by dreddy-work** [comment]
Open loc issue. Lets see if it overrides.

**Review by dreddy-work — APPROVED** [review]

**Comment by elachlan** [comment]
@dreddy-work I do not have access to it. Could you please raise that issue if you haven't already?

**Comment by dreddy-work** [comment]
> @dreddy-work I do not have access to it. Could you please raise that issue if you haven't already?

I raised and linked on issue.

**Comment by jonfortescue** [comment]
It will override it in the meantime, yes.

**Pull request merged**
