### PR TITLE
Adding Form subtype in templates

### LINKED ISSUE #3510: Windows Forms templates should carry proj.user with SubType already set
**Problem description:**

To detect that a Forms is openable by the designer (and gets the icon), Roslyn asynchronously reads the attributes of a type's base types and pushes a "SubType" if the right attribute is present to the project system. Which in turn, causes the designer paths to light up.

This is a slow and asynchronous process and cannot be blocked on, and causes additional evaluations and design-time builds to kicked off after Roslyn sets the subtype.

 To side step this whole process, and improve the speed for opening the designer and to reduce the number of design-builds that are needed for File -> New, the templates should carry this information and have the project system automatically recognize that this project contains a designable file.

To do that, carry a UTF8-with BOM file alongside the project called "[Project].csproj.user"

``` XML
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Compile Update="Form1.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>
</Project>
```

### PR DESCRIPTION
**Pull request by Shyam-Gupta**
Fixes #3510 

1. Added *.user files to add Form subtype.
2. By default template engine removes *.user files. 
    To override it, I have added sources in template.json to remove *.user from "exclude"
3. Fixed a typo in readme.md

Verified that:
- **.user file gets dropped on creating new project from dotnet CLI
- It works when project gets created from VS. Now Form1.cs opens directly in designer
- **.user files have BOM (0xEF, 0xBB, 0xBF) characters in the beginning and the files have UTF 8 encoding
- On adding a new Form to an existing project, the new Form opens directly in designer

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3527)

### CODE REVIEW

**Comment by RussKie** [comment]
> 2\. By default template engine removes *.user files.
>     To override it, I have added sources in template.json to remove *.user from "exclude"

Non blocking question, could we have used the `include` node to include `*.user` instead of defining the `exclude`?

**Comment by Shyam-Gupta** [comment]
> Non blocking question, could we have used the `include` node to include `*.user` instead of defining the `exclude`?

It doesn't work that way. With `include` node, it only copies *.user file and exclude others which causes it to throw error while restoring packages. Even if we use `**.*user` in addition to `**/*`, the exclude list overrides `*.user` files.

**Comment by RussKie** [comment]
Thank you

**Comment by Shyam-Gupta** [comment]
@merriemcgaw Should we consider this change for 3.1 servicing ?

**Comment by merriemcgaw** [comment]
Have we verified how this impacts the load time in the designer If this is a noticeable, measurable amount then definitely service!

**Comment by Shyam-Gupta** [comment]
In order to load the designer, user needs to either double click on the Form icon or open it through Shift + F7. Both these options  are not available to the user for several seconds (>10 sec) after creating a new project. Sometimes the icon just doesn't appear at all. During this time user is completely blocked to load the designer.

**Pull request merged**
