### PR TITLE
Re-categorize runtime dependencies as Product

### PR DESCRIPTION
**Pull request by mmitche**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3517)

### CODE REVIEW

**Comment by RussKie** [comment]
Looks good 👍. Please resolve the MC and then merge at will.

What's the difference? Is this documented anywhere to read up on it?

**Comment by mmitche** [comment]
The deal here is that these dependencies are (I think) not just for testing purposes.

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
