### PR TITLE
Switch to non-stable

### PR DESCRIPTION
**Pull request by RussKie**
Contributes to #2387

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/2386)

### CODE REVIEW

**Comment by RussKie** [comment]
@mmitche our yml is set to `release/*`. Do we need to change to `release/3.*`?
https://github.com/dotnet/winforms/blob/release/3.0/azure-pipelines.yml#L13-L21

**Comment by mmitche** [comment]
> @mmitche our yml is set to `release/*`. Do we need to change to `release/3.*`?
> https://github.com/dotnet/winforms/blob/release/3.0/azure-pipelines.yml#L13-L21

No, release/* is fine.

**Comment by RussKie** [comment]
Updated packages as well, while I am at it.

**Comment by RussKie** [comment]
Updating packages terminally breaks the build, reverting the change.
image

@mmitche any ideas?

**Comment by mmitche** [comment]
> Updating packages terminally breaks the build, reverting the change.
> image
> 
> @mmitche any ideas?

Probably because it's stable inside those zip files.  You should be able to change it to "3.0.1" after this morning.

**Pull request merged**
