### PR TITLE
Restore assembly-level CLSCompliant true & remove method-level instances of false CLS Compliance

### PR DESCRIPTION
**Pull request by Shyam-Gupta**
1. Changed ClsCompliant to true at assembly level for all 3 implementation assemblies
2. (1) caused some compile time errors for instances in System.Windows.Forms where we have declared ClsCompliant to false at some methods and class levels. I removed those instances as all of them were in internal classes.

After this change there are no compile time errors and both unit tests and integration test passes.

I am not sure if there can be any runtime implications because of this change.

### CODE REVIEW

**Comment by zsd4yr** [comment]
passed internal: https://dnceng.visualstudio.com/internal/_build/results?buildId=124586&view=logs

**Comment by sharwell** [comment]
> Changed ClsCompliant to true at assembly level for all 3 implementation assemblies

Why is this needed?

> (1) caused some compile time errors for instances in System.Windows.Forms where we have declared ClsCompliant to false at some methods and class levels. I removed those instances as all of them were in internal classes.

I'm really curious about this. I expected the use of CLSCompliant(true) at the assembly level to *resolve* these warnings, not *cause* them. Can you give an example of the type of warning you saw?

**Comment by zsd4yr** [comment]
DN-T build passed as well https://devdiv.visualstudio.com/DevDiv/_build%2Fresults?buildId=2498082&_a=summary

**Comment by Shyam-Gupta** [comment]
@sharwell 

On removing CLSCompliant attribute from implementation assemblies, I get lots of errors like:

System\Windows\Forms\AxHost.cs(4657,32): error CS3021: 'AxHost.GetColorFromOleColor(uint)' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [C:\gnew\winforms\src\System.Windows.Forms\src\System.Windows.Forms.csproj]
System\Windows\Forms\AxHost.cs(4667,31): error CS3021: 'AxHost.GetOleColorFromColor(Color)' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [C:\gnew\winforms\src\System.Windows.Forms\src\System.Windows.Forms.csproj]
System\Windows\Forms\ComponentModel\COM2Interop\_CTLBLDTYPE.cs(11,20): error CS3021: '_CTLBLDTYPE' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [C:\gnew\winforms\src\System.Windows.Forms\src\System.Windows.Forms.csproj]
C:\gnew\winforms\src\Common\src\UnsafeNativeMethods.cs(8347,28): error CS3021: 'UnsafeNativeMethods.IAccessibleEx' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [C:\gnew\winforms\src\System.Windows.Forms\src\System.Windows.Forms.csproj]
C:\gnew\winforms\src\Common\src\UnsafeNativeMethods.cs(8466,26): error CS3021: 'UnsafeNativeMethods.IRawElementProvider
Simple' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [C:\gnew\winforms\src\System.Windows.Forms\src\System.Windows.Forms.csproj]
C:\gnew\winforms\src\Common\src\UnsafeNativeMethods.cs(8546,26): error CS3021: 'UnsafeNativeMethods.IRawElementProviderFragment' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [C:\gnew\winforms\src\System.Windows.Forms\src\System.Windows.Forms.csproj]

All errors are in System.Windows.Forms only.

**Comment by sharwell** [comment]
> Error CS3021: 'AxHost.GetColorFromOleColor(uint)' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute 

@Shyam-Gupta This means this change is not adding `[CLSCompliant(true)]`, it's simply removing `[CLSCompliant(false)]`. I need to look into the targets tomorrow and figure out why it's not working correctly.

**Pull request merged**
