### PR TITLE
Rename Config to config

### LINKED ISSUE #1304: Dependencies are not getting updated
Dependency updates seem to have stalled on dotnet/winforms. 

The last update was 14 days ago, approximately. See https://github.com/dotnet/winforms/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Fdotnet-maestro. 

Triggering subscriptions manually doesn't seem to have any effect either. 

/cc @merriemcgaw, @AdamYoblick, @RussKie 
/cc @wtgodbe

### PR DESCRIPTION
**Pull request by jcagme**
Fixes #1304 
https://github.com/dotnet/core-eng/issues/6868#issuecomment-509375608

## Proposed changes

- Rename "NuGet.Config" to "NuGet.config"

With https://github.com/dotnet/arcade-services/pull/477 we started consuming "NuGet.config". Since git is case sensitive we look for this exact name.

### CODE REVIEW

**Comment by jcagme** [comment]
Could you guys please port this change to other 3.0 branch you have subscriptions created for (if any)?

**Comment by vatsan-madhavan** [comment]
- [dotnet/winforms-designer](https://github.com/dotnet/winforms-designer) has the right casing. 
- I also checked [dotnet/wpf](https://github.com/dotnet/wpf) and [dotnet-wpf-int](https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int) - both repos have the right casing for `Nuget.config`

These need to be fixed: 

- [dotnet/winforms-datavisualization](https://github.com/dotnet/winforms-datavisualization) **needs to be fixed.**
- We have an internal [test repo](https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test) which has incorrect casing and needs to be fixed. @ojhad - would you mind renaming `Nuget.Config` to `Nuget.config` in `dotnet-wpf-test` ?

**Comment by merriemcgaw** [comment]
Thanks @vatsan-madhavan and @jcagme! We'll put an issue to update the subscription into the datavisualization repo.

**Comment by jcagme** [comment]
> * [dotnet/winforms-designer](https://github.com/dotnet/winforms-designer) has the right casing.
> * I also checked [dotnet/wpf](https://github.com/dotnet/wpf) and [dotnet-wpf-int](https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int) - both repos have the right casing for `Nuget.config`
> 
> These need to be fixed:
> 
> * [dotnet/winforms-datavisualization](https://github.com/dotnet/winforms-datavisualization) **needs to be fixed.**
> * We have an internal [test repo](https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test) which has incorrect casing and needs to be fixed. @ojhad - would you mind renaming `Nuget.Config` to `Nuget.config` in `dotnet-wpf-test` ?

https://github.com/dotnet/winforms-datavisualization/pull/20

**Comment by vatsan-madhavan** [comment]
`dotnet-wpf-test` has been fixed with https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-test/pullrequest/2013

**Comment by RussKie** [comment]
You could do it from cli:
```
git mv -f name.java Name.java
```
https://stackoverflow.com/a/1793757

**Pull request merged**
