### PR TITLE
Correct icon

### LINKED ISSUE #3460: The icon is the same for both ListBox & CheckedListBox controls in Toolbox window
* .NET Core Version: 
5.0 Preview 7 5.0.100-preview.7.20316.3

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
The icon is the same for ListBox & CheckedListBox controls.
Same

**Expected behavior:**
The icon should not be the same.
NotSame

**Minimal repro:**
1. Create a winforms core project.
2. Type 'listBox' words in Toolbox's search box.
3. Observe the controls' icon.

### PR DESCRIPTION
**Pull request by RussKie**
Resolves #3460

## Customer Impact

- VS Designer toolbox only will display correct icon for `ListBox` control

## Regression? 

- Yes

## Risk

- Minimal, VS Designer toolbox only

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/4087)

### CODE REVIEW

**Review by dreddy-work — APPROVED** [review]
Did you get chance to verify in toolbox as well?

**Comment by RussKie** [comment]
Converting to draft until we can verify. @dreddy-work need you help with it.

**Comment by dreddy-work** [comment]
FYI - this does not fix the toolbox icon  issue. We have an issue being fixed in the private designer repo. expect it to be fixed in upcoming VS preview release.

**Pull request merged**
