### PR TITLE
replaced end of sentence dot followed by 2 spaces with a dot with a single space

### PR DESCRIPTION
**Pull request by Tanya-Solyanik**
I ran this regex on all projects, and hanges only xml doc comments. Remaining double spaces are in .resx files and in build warning that will be eventually visible to the users.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/winforms/pull/12635)

### CODE REVIEW

**Review by merriemcgaw — APPROVED** [review]
lgtm

**Comment by paul1956** [comment]
@merriemcgaw While I think removing double space in resx files is a great idea, when in was proposed previously it was rejected because it was a considered a breaking change.

If that's changed it should be done to VB files as well.

**Comment by merriemcgaw** [comment]
@paul1956, yes I think we ought to do it now.

**Comment by paul1956** [comment]
@merriemcgaw I did all the VB comments already. Some of the tests depend on the space and would need to be fixed at the same time as ResX, @Tanya-Solyanik might have done it as part of this PR but 3rd party core would break.

**Comment by paul1956** [comment]
@Tanya-Solyanik I only found 1 instance of this left in VB, do you want to fix? There is no test to be changed.
Winforms\src\Microsoft.VisualBasic.Forms\src\Resources\SR.resx

**Comment by Tanya-Solyanik** [comment]
@paul1956 thank you for the reminder that decided to not touch user-visible strings. I changed only source files.

**Comment by Tanya-Solyanik** [comment]
@KlausLoeffelmann 
>Paul - can you point me to cases where correcting the wording of a message in the RESX-Files would regress a test?

Tests wouldn't be a problem - tests can read the resx content  and can do regex match of the text. The push back was about users who expect the exact match in the resx string. We can revisit that later. These changes are about the source code only

**Review by merriemcgaw — APPROVED** [review]

**Review by KlausLoeffelmann — APPROVED** [review]
LGTM!

**Pull request merged**
