### PR TITLE
Fix string interpolation in ScrollBar

### PR DESCRIPTION
**Pull request by ycanardeau**
Just fixed string interpolation in ScrollBar.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3752)

### CODE REVIEW

**Comment by RussKie** [comment]
Thank you. Can you please add a test for the change?

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=3752) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=3752) before we can accept your contribution.<br/><br/>:x: ycanardeau [sign now](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=3752)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/winforms?pullRequest=3752) it.</sub>

**Comment by ycanardeau** [comment]
Added a test for the change.

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you!

**Pull request merged**
