### PR TITLE
Fixed issue #2931

### PR DESCRIPTION
**Pull request by dehghani-mehdi**
I just changed few characters in doc section.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/2953)

### CODE REVIEW

**Comment by weltkante** [comment]
master is already working on 5.0 so I'm not sure why this should be turned back to netcoreapp3.0 just to match a screenshot? Won't this cause problems when .NET Core 5.0 is released and the docs and screenshot still say to use 3.0?

**Comment by dehghani-mehdi** [comment]
I think the code and screenshot should match in either way (both 5.0 or 3.0 or ...) and because of this" comment: https://github.com/dotnet/winforms/issues/2931#issuecomment-595512430, I changed the code.

**Comment by weltkante** [comment]
Yeah I understand why you made the PR, I just want to highlight the conflict so the responsible people can think about it again.

**Comment by RussKie** [comment]
Thank you, but I am not convinced this change is _really_ necessary. It is a little inconsistent, but I don't think it is hard to understand what's been set.
In few months when the Designer is ready the whole page will be deprecated.

**Pull request closed without merging**
