### PR TITLE
Repopulate owner HWNDs correctly

### LINKED ISSUE #8803: Metroframework library worked in .NET 6 and Framework -- Crashes on .NET 7
### .NET version

7.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Worked on .NET 6

### Issue description

I was updating documentation on how to upgrade from .net 4 to .NET 6, updating the steps to .NET 7. The app I was using worked fine on .NET 6, but on .NET 7 it crashes unable to create the starting window.

I'm using a 3rd party library from NuGet that was made for .NET Framework, I chose it so that I could demonstrate upgrading NuGet packages. The bug is most certainly from the usage of that library, but the library hasn't been updated in a decade. But, like I was saying, it was written for .NET Framework, worked fine on .NET Core 3.1/.NET 5/.NET 6, but no longer with .NET 7. The designer seems to be fine.

The library is this: [Metroframework (thielj.github.io)](https://thielj.github.io/MetroFramework/)
NuGet: [NuGet Gallery | MetroFramework 1.2.0.3](https://www.nuget.org/packages/MetroFramework/)

### Steps to reproduce

[MatchingGame_Net7.zip code](https://github.com/dotnet/winforms/files/10972846/MatchingGame_Net7.zip)

Here is a sample project. If you change the TFM to .NET 6, it works fine. When you keep it as .NET 7, you get this crash

image

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Should be storing the child, not the parent.

Fixes #8803

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8870)

### CODE REVIEW

**Comment by dreddy-work** [comment]
port to release/7.0

**Review by dreddy-work — APPROVED** [review]

**Comment by kirsan31** [comment]
Thank you @JeremyKuhne 
I hope it will be in 7.0.**5**?

**Comment by dreddy-work** [comment]
> Thank you @JeremyKuhne I hope it will be in 7.0.**5**?

Yes @kirsan31, it is being pushed to next servicing of 7.0.

**Comment by dreddy-work** [comment]
> > Thank you @JeremyKuhne I hope it will be in 7.0.**5**?
> 
> Yes @kirsan31, it is being pushed to next servicing of 7.0.

@kirsan31, FYI, this didn't make to April release. It will be in May servicing release.

**Comment by kirsan31** [comment]
> FYI, this didn't make to April release. It will be in May servicing release.

We wanted to wait with the transition to 7.0 until the release of this fix, but now it looks like we'll have to take a chance :) ...

**Pull request merged**
