### PR TITLE
Fix xmldoc

### PR DESCRIPTION
**Pull request by RussKie**
Fixes #

## Proposed changes

- Purely cosmetic change that increases xml-doc spacing to 2 after `///`.  
The increased spacing makes it slightly easier to read the comments in the code.
The change is done in VS using regex `///\s([^< ])` -> `///  $1`
- Fix and add xml-doc

## Customer Impact

- None

## Regression? 

- No

## Risk

- None

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/1591)

### CODE REVIEW

**Comment by sharwell** [comment]
> increases xml-doc spacing to 2

Oh what has happened 🤕

**Comment by sharwell** [comment]
> The increased spacing makes it slightly easier to read the comments in the code.

I would suggest changing the color of XML elements in documentation comments instead of changing to a non-standard and non-maintainable layout. I use the following in my vssettings:

```
<Item Name="xml doc comment - name" Foreground="0x0067A8C7" Background="0x02000000" BoldFont="No"/>
<Item Name="xml doc comment - entity reference" Foreground="0x004E8B60" Background="0x02000000" BoldFont="Yes"/>
<Item Name="xml doc comment - delimiter" Foreground="0x0067A8C7" Background="0x02000000" BoldFont="No"/>
<Item Name="xml doc comment - attribute name" Foreground="0x006968A6" Background="0x02000000" BoldFont="No"/>
```

image

**Comment by RussKie** [comment]
> > increases xml-doc spacing to 2
> 
> Oh what has happened 🤕

https://github.com/dotnet/winforms/issues/1489 guideline:2



> I use the following in my vssettings:

Thank you Sam. 
However a number of our contributors do not use VS, and thus these settings won't work for everyone.

**Comment by weltkante** [comment]
> The change is done in VS using regex `///\s([^< ])` -> `/// $1`

You might want to anchor the regex at the start of the line, allowing only whitespace up to the comment, otherwise you'll also update triple slashes inside strings (even with anchoring it could still be a multiline string though).

**Pull request merged**
