### PR TITLE
[WIP] Get ApiCompat working in winforms

### PR DESCRIPTION
**Pull request by hughbe**
## Proposed Changes
- We're missing a reference to `Microsoft.DotNet.ApiCompat` so cannot run ApiCompat on winforms against .NET Framework
- Reference this library and also add a list of exclusions for attributes, taken from corefx

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/1944)

### CODE REVIEW

**Comment by hughbe** [comment]
@RussKie unfortunately this PR keeps getting merge conflicts every time we update arcade packages. If you could give some comments I can address them before rebasing etc :)

**Comment by RussKie** [comment]
> If you could give some comments I can address them before rebasing etc :)

Sorry it is taking time to get around looking at this.
Can we please put this on ice, until I can find out what the vision is for this file?

**Comment by hughbe** [comment]
> Can we please put this on ice, until I can find out what the vision is for this file?

Sure I can wait. I think that either we should take this PR or gut all the existing ApiCompat files. Our current situation is somewhere in the middle and doesn't achieve anything

**Comment by RussKie** [comment]
I had a chat with @ericstj and we need to do the following:

### release/3.0
- generate an API compat report .NET Framework -> .NET Core 3.0 (this becomes a baseline)

### release/3.1
- generate an API compat report .NET Framework -> .NET Core 3.1
- generate an API compat report .NET Core 3.0 -> 3.1 <-- there must not be any warnings here, otherwise we have breaking changes

### master
- generate an API compat report .NET Framework -> .NET 5.0
- generate an API compat report .NET Core 3.1 -> 5.0 <-- there must not be any warnings here, otherwise we have breaking changes

As of now I have no further information to share, as I ma still digesting this.

/cc: @zsd4yr @AdamYoblick

**Comment by hughbe** [comment]
Closing in favor of https://github.com/dotnet/winforms/pull/2092

**Pull request closed without merging**
