### PR TITLE
Move all Clipboard related tests to a new class and remove SkipOnArchitecture label

### PR DESCRIPTION
**Pull request by LeafShi1**
Related #11227

## Proposed changes

- Move all Clipboard related tests to a new class and remove SkipOnArchitecture label
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/winforms/pull/11606)

### CODE REVIEW

**Comment by paul1956** [comment]
As part of the VB Runtime there are clipboard access functions and a ClipboardProxy class. There are very few existing tests and they have the some issue you are trying to resolve. As part of my Code Cleanup PR, I added 100% code coverage for the VB Runtime but that will conflict/clash with this PR. Sent from my iPhoneI apologize for any typos Siri might have made.(503) 803-6077On Jun 27, 2024, at 11:58 PM, codecov[bot] ***@***.***> wrote:﻿
Codecov Report
All modified and coverable lines are covered by tests ✅

Project coverage is 96.97886%. Comparing base (b3b877e) to head (c78800e).

Additional details and impacted files
@@                 Coverage Diff                  @@
##                main      #11606          +/-   ##
====================================================
+ Coverage   74.56266%   96.97886%   +22.41620%     
====================================================
  Files           3040        1069        -1971     
  Lines         629551      344373      -285178     
  Branches       46854        4983       -41871     
====================================================
- Hits          469410      333969      -135441     
+ Misses        156784        9694      -147090     
+ Partials        3357         710        -2647     



Flag
Coverage Δ





Debug
96.97886% <100.00000%> (+22.41620%)
⬆️


integration
?



production
?



test
96.97886% <100.00000%> (+0.02177%)
⬆️


unit
?




Flags with carried forward coverage won't be shown. Click here to find out more.

**Review by Tanya-Solyanik — APPROVED** [review]
Thank you!

**Comment by Tanya-Solyanik** [comment]
@paul1956  - could you please describe the conflict? 

>but that will conflict/clash with this PR.

**Comment by paul1956** [comment]
Sent from my iPhoneI apologize for any typos Siri might have made.(503) 803-6077On Jun 28, 2024, at 11:03 AM, Tanya Solyanik ***@***.***> wrote:﻿
@paul1956  - could you please describe the conflict?

but that will conflict/clash with this PR.I will merge your changes and see what happens then I will know more.  What I know now is none of the new and existing Visual Basic Runtime Clipboard/ClopboardProxy tests are in your new project and most are written in VB.

**Comment by LeafShi1** [comment]
> Sent from my iPhoneI apologize for any typos Siri might have made.(503) 803-6077On Jun 28, 2024, at 11:03 AM, Tanya Solyanik ***@***.***> wrote:﻿ @paul1956 - could you please describe the conflict? but that will conflict/clash with this PR.I will merge your changes and see what happens then I will know more.  What I know now is none of the new and existing Visual Basic Runtime Clipboard/ClopboardProxy tests are in your new project and most are written in VB. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Ok, I will keep this PR open.

**Comment by Tanya-Solyanik** [comment]
>and existing Visual Basic Runtime Clipboard/ClopboardProxy tests are in your new project and most are written in VB.

@paul1956  - I don't think this is a problem, we are not synchronizing tests from different assemblies in this PR. This PR adds some clipboard related tests to the synchronized collection within a single test assembly. There might be some other tests that we hadn't added yet, for example in the datagridview area.

**Comment by paul1956** [comment]
@Tanya-Solyanik I looked into this more and I handle "synchronizing tests from different assemblies" for the VB tests. I will test to verify issue is fixed once you merge. 
Thanks.

**Pull request merged**
