### PR TITLE
fix bug The code generated by the ListBox control is not consistent with Framework

### LINKED ISSUE #4463: The code generated by the ListBox control is not consistent with Framework
* .NET Core Version: 
3.1+

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

The generated code for ListBox1 have extra code: this.listBox1.ItemHeight = 15;
image

**Expected behavior:**
The generated code for ListBox1 should not have this code: this.listBox1.ItemHeight = 15;
image

**Minimal repro:**
1. Create a Core winforms application.
2. Add a **ListBox** control to **form**.
3. Double click the **Form1.Designer.cs** file in Solution Explorer.
4. Observe the generated code of the **ListBox**.
Result: The generated code for ListBox1 should not have this code: this.listBox1.ItemHeight = 15;

Note from Dustin: ListBox.ItemHeight property. 
dotnet/winforms@4bca5b3/src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs#L596-L616
It has a `[DefaultValue(DefaultItemHeight)]` attribute and DefaultItemHeight is 13.
Note from Tanya: Our default value is not accurate anymore due to the default font change. 13 is the default for Microsoft Sans Serif, 8.25pt, 15 is what comctl32 listbox calculates for Segoe UI, 9pt. To confirm - change the parent control's font.

### PR DESCRIPTION
**Pull request by Epica3055**
Fixes #4463

## Proposed changes

- 
-  when `DrawMode` is `DrawMode.Normal `, the ItemHeight can not be set to ListBox. So, ItemHeight should not be serialized.
- 
https://github.com/dotnet/winforms/blob/5234e14330d5379bab230817df65bb4d8c1af28c/src/System.Windows.Forms/src/System/Windows/Forms/DrawMode.cs#L6-L28
https://github.com/dotnet/winforms/blob/5234e14330d5379bab230817df65bb4d8c1af28c/src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs#L582-L622

## Before
The generated code for ListBox1 have extra code: this.listBox1.ItemHeight = 15;
image

## After

https://github.com/dotnet/winforms/assets/135201996/73544c63-e0cf-4c06-a829-56bfc5d09ebb

## Regression? 

- Yes / No

## Risk

- minimal

## Test methodology 

- 
- Manually 
-

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/10142)

### CODE REVIEW

**Comment by Tanya-Solyanik** [comment]
@Epica3055, I will take a look at this issue in a couple of weeks, there are several related fixes that should be approached together

**Comment by Epica3055** [comment]
> @Epica3055, I will take a look at this issue in a couple of weeks, there are several related fixes that should be approached together

OK, I will take a look at them.

**Comment by lonitra** [comment]
This PR has not had any activity in a while. Should this still be kept active?

**Comment by Epica3055** [comment]
@lonitra 
> This PR has not had any activity in a while. Should this still be kept active?
Maybe I need to talk about it with @Tanya-Solyanik

**Comment by Tanya-Solyanik** [comment]
@Epica3055  - your approach looks good. Please make sure to test the design time scenario with both OwnerDrawn and Normal list items.
To test design time code generation, build your own winforms runtime assemblies and copy them over to C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\9.0.0-alpha.????. If you don't have NET9 in your %ProgramFiles% folder, install it from https://github.com/dotnet/installer#installers-and-binaries. If you are building the latest main, you would need all assemblies that you build, that are layered below winforms, due to the recent refactoring of common statics from Jeremy
System.Drawing.Common
System.Private.Windows.Core
System.Windows,Forms
System.Windows.Forms.Primitives
Create a Net9 application and experiment with code generation for ListBoxes

**Comment by RussKie** [comment]
You may find this script useful: https://gist.github.com/RussKie/bb11e213f04729603e533856865922c1

**Pull request merged**
