### PR TITLE
Issue 2053861 fix combo box flickering issue

### PR DESCRIPTION
**Pull request by LeafShi1**
Fixes #[2053861]( https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2053861)

## Proposed changes

- Separate `DrawPopUpCombo `from `DrawFlatCombo `method，draw the outer black border only when the ComboBox mouse is over

## Customer Impact

- Combobox no longer flickers when hovering over it

## Regression? 

- No

## Risk

- Minimal

### Before
Combo box flashes when you move the mouse over it
BeforeChange

### After
Combo boxes no longer flicker when you move the mouse over them
AfterChange

## Test methodology 

- Manually

## Test environment(s) 

- .net 9.0.0-preview.6.24305.2

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/winforms/pull/11529)

### CODE REVIEW

**Comment by Tanya-Solyanik** [comment]
This link - https://devdiv.visualstudio.com/DevDiv/_queries/edit/2053861/?queryId=7c94b3b5-6b84-4f3d-9f76-ff1a7a7b7581 does not work, please fix it.

Had you tested this change at different themes and RtL applications? 

The change looks reasonable.

**Comment by LeafShi1** [comment]
> This link - https://devdiv.visualstudio.com/DevDiv/_queries/edit/2053861/?queryId=7c94b3b5-6b84-4f3d-9f76-ff1a7a7b7581 does not work, please fix it.
> 
> Had you tested this change at different themes and RtL applications?
> 
> The change looks reasonable.

Test in RTL app:
RTL

Test in different theme:
ThemeAquatuc
ThemeDesert

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - How do the high contrast themes look before your changes, did it get better or worse with the fix?
FYI @merriemcgaw

**Comment by LeafShi1** [comment]
Before the modification, the Popup state was not obvious, and only a black border was displayed when the mouse entered the control 
white
black

**Comment by merriemcgaw** [comment]
This is definitely not worse from my perspective. @Tanya-Solyanik?

**Comment by Tanya-Solyanik** [comment]
> This is definitely not worse from my perspective. @Tanya-Solyanik?

The new behavior looks more intentional, i.e. we are adding a border when mouse is hovering. I don't mind taking this fix.

**Comment by Tanya-Solyanik** [comment]
@Olina-Zhang - could you please test this fix?

**Comment by Tanya-Solyanik** [comment]
@LeafShi1 
>But I am not sure if we can remove this directly, @Tanya-Solyanik What do you think?

No, we shouldn't do that. I agree. To fix that we would have to redesign the look, maybe add a prominent border in the state when the mouse is not above the control

**Comment by LeafShi1** [comment]
> @LeafShi1
> 
> > But I am not sure if we can remove this directly, @Tanya-Solyanik What do you think?
> 
> No, we shouldn't do that. I agree. To fix that we would have to redesign the control look, maybe add a prominent border in the state when the mouse is not above the control

Do we need to redesign the controls appearance now?

**Review by ricardobossan — COMMENTED** [review]
All LGTM

**Comment by Tanya-Solyanik** [comment]
>@Tanya-Solyanik Do we need to redesign the controls appearance now?

No

**Review by Tanya-Solyanik — APPROVED** [review]

**Comment by Syareel-Sukeri** [comment]
Verified this issue on 9.0.100-preview.7.24371.4 with dlls built from winforms repo of main branch, it was fixed.  Flickering effect is no longer there when hovering over ComboBox. Results are as below:

**PopupStyle**

https://github.com/user-attachments/assets/fff6c129-6890-4203-9618-4ac17b8dfcab

**FlatStyle**

https://github.com/user-attachments/assets/eaaf3e8c-c057-4076-b47d-5f294e5ba9e9

**Different Themes**


https://github.com/user-attachments/assets/4c248269-c303-4a0b-a790-faf412703505


https://github.com/user-attachments/assets/3c7111d8-e452-49f8-ba89-080e463f9ae4

https://github.com/user-attachments/assets/bd6a23f1-5c09-4b9a-9d9e-69c7ebce47a7


https://github.com/user-attachments/assets/22d15301-8eda-4926-b7a4-d2abcf8949f2

**Comment by Olina-Zhang** [comment]
Verified this PR fixing in .NET 9.0.100-preview7.24402.8 test pass build from provided VS VAL build, it was fixed for ComboBox flickering issue when setting this control's FlatStyle == PopUp. But still repro for ComboBox's FlatStyle == Flat case. These are same as the testing result we tested before.

https://github.com/user-attachments/assets/b85553d6-0cdb-43a4-919c-3e25781be169

**Pull request merged**
