### PR TITLE
Add more Control/ListView related tests

### PR DESCRIPTION
**Pull request by hughbe**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/1967)

### CODE REVIEW

**Comment by hughbe** [comment]
Great! Tests fixed to account for Accessibility Level 3 enabling in .NET Core.

@russkie for my own personal use in writing tests against netfx, how can I enable .NET Framework Accessibility Level 3 improvements ?

**Comment by RussKie** [comment]
> how can I enable .NET Framework Accessibility Level 3 improvements ?

@M-Lipin @vladimir-krestov are you able to help?

**Comment by hughbe** [comment]
> how can I enable .NET Framework Accessibility Level 3 improvements ?

I mean for a .NET Framework project - that doesn't block this PR :)

**Comment by vladimir-krestov** [comment]
In .Net Core Accessibility improvements are enabled always.
In .Net Framework you can use Accessibility switches to managing Accessibility improvements.
You need to change the App.config file:
https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility

If you need to enable .NET Framework Accessibility Level 3 improvements you should add this code to App.config file:
```
<runtime>
        <AppContextSwitchOverrides value="Switch.UseLegacyAccessibilityFeatures=false;Switch.UseLegacyAccessibilityFeatures.2=false;Switch.UseLegacyAccessibilityFeatures.3=false;Switch.System.Windows.Forms.UseLegacyToolTipDisplay=false"/>-->
</runtime>
```

For example, if you need to use only Accessibility Level 1 improvements, then add this code:
```
<runtime>
    <AppContextSwitchOverrides value="Switch.UseLegacyAccessibilityFeatures=false;Switch.UseLegacyAccessibilityFeatures.2=true;Switch.UseLegacyAccessibilityFeatures.3=true;Switch.System.Windows.Forms.UseLegacyToolTipDisplay=true"/>
</runtime>
```

**`true` means disable features.**

**Pull request merged**
