### PR TITLE
fix issue #11450 scenario  2. Color contrast ratio of focus indicator over 'toolStripSplitButton1' is 1.247:1 which is less than 3:1: A11y_.NET CoreWinforms_StripControls_Toolstripwithmenuitem_NonTextContrast

### LINKED ISSUE #11450: Color contrast ratio of focus indicator over 'toolStripSplitButton1' is 1.247:1 which is less than 3:1: A11y_.NET CoreWinforms_StripControls_Toolstripwithmenuitem_NonTextContrast
### .NET version

dotnet-sdk-9.0.100-preview.5.24258.1

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

_No response_

### Issue description

GitHub Tags:
#A11yMAS; #A11yTCS; #A11ySev2; #BM_.NET Core[Winforms]_Win32_May2024; #.NETCore; #WCAG1.4.11; #DesktopApp; #Win11; #FTP; #NonTextContrast;

### Environment Details:
App name: .NET Core Winforms
Window Version: Win 11
OS Build: 22621.3085

### Repro Steps:

1. Launch the "Accessibility core app".
2. Main Form screen would appear.
3. TAB to "MenuToolbars_Controls:Testing the controls under Menu Toolbars Tab" and hit ENTER key.
4. TAB to StripControls button and hit ENTER key.
5. TAB to 'toolStripSplitButton1' present at below section of the screen.
6. Observe the issue.

### Actual Result:
Color contrast ratio of focus indicator over 'toolStripSplitButton1' is 1.247:1 which is less than 3:1.

**Similar issue is also observed in below scenario:
Issue 1: ToolStripContainer**

1. Launch the "Accessibility core app".
2. Main Form screen would appear.
3. TAB to "MenuToolbars_Controls:Testing the controls under Menu Toolbars Tab" and hit ENTER key.
4. TAB to ToolStripContainer button and hit ENTER key.
5. TAB to 'toolStripSplitButton2' present at below section of the screen.
6. Observe that color contrast ratio over "toolStripSplitButton2" is failing.

**Issue2: PrintingTesting_PrintPreview:**

1. Launch the "Accessibility core app".
2. Main Form screen would appear.
3. TAB to "Printing_Controls:Testing the controls under Printing Tab" and hit ENTER key.
4. TAB to Preview button and hit ENTER key.
5. Print Preview Screen would appear.
6. Navigate to "Zoom" button using TAB key and observe that color contrast ratio over "Zoom" is failing.

### Expected Result:
Color contrast ratio of focus indicator over 'toolStripSplitButton1' should be greater than or equal to 3:1

### User Impact:
Low vision users will not be able to identify where the focus is and will not be able to interact with the control.

### Attachment
11450_A11y_ NET CoreWinforms_StripControls_Toolstripwithmenuitem_NonTextContrast

### PR DESCRIPTION
**Pull request by Epica3055**
Fixes #11450
 
 
## Proposed changes
 
- 
- Remove RenderMode
-
 

 
 
### Before
 
image 

### After
 
image

### CODE REVIEW

**Review by Tanya-Solyanik — APPROVED** [review]
Looks good, but please get it tested in High Contrast mode

**Comment by Epica3055** [comment]
@Tanya-Solyanik 
This is what it looks in Night Sky high contrast mode.
Do you think this is correct?
image

**Comment by Tanya-Solyanik** [comment]
@Epica3055  - the border between the drop down button and the "search" icon does not look to be contrasting enough.

**Comment by Epica3055** [comment]
@Tanya-Solyanik 
image

It seems that all ToolStrip have this problem. Do you we should fix it in this PR?

**Comment by Tanya-Solyanik** [comment]
>It seems that all ToolStrip SplitButton have this problem. Do you we should fix it in this PR?

This is unfortunate. Open a new bug to track that. But first search if we already have one.

**Review by Tanya-Solyanik — APPROVED** [review]

**Pull request merged**
