### PR TITLE
Enable Stable Branding .NET 9 GA

### PR DESCRIPTION
**Pull request by LeafShi1**
N/A
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/winforms/pull/12325)

### CODE REVIEW

**Comment by lonitra** [comment]
error: 
```
error NU5104: (NETCORE_ENGINEERING_TELEMETRY=Build) Warning As Error: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.Win32.SystemEvents [9.0.0-rtm.24511.16, )" or update the version field in the nuspec.
```
Looks like we need to wait for runtime flow fyi @mmitche

**Comment by mmitche** [comment]
> error:
> 
> ```
> error NU5104: (NETCORE_ENGINEERING_TELEMETRY=Build) Warning As Error: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.Win32.SystemEvents [9.0.0-rtm.24511.16, )" or update the version field in the nuspec.
> ```
> 
> Looks like we need to wait for runtime flow fyi @mmitche

You can also temporarily disable that warning if you want to make progress.

**Comment by mmitche** [comment]
@lonitra @LeafShi1 System.Drawing.Common resets `WarningsNotAsErrors` rather than appending to it. That needs to be fixed.

**Review by lonitra — APPROVED** [review]

**Comment by lonitra** [comment]
Thank you @mmitche for the help here!

**Pull request merged**
