### PR TITLE
Using `NameOf` when throwing exceptions

### PR DESCRIPTION
**Pull request by raffaeler**
This pull request is a refactoring on all the argument exceptions specifying the name of the argument as hardcoded strings. All of them have been replaced with nameof(argumentname).

### CODE REVIEW

**Comment by AdamYoblick** [comment]
oh what the hell, i closed it and wanted to reopen to trigger the CI build check again, and the reopen button isn't there....

**Comment by AdamYoblick** [comment]
Will reopen, one sec...

**Comment by AdamYoblick** [comment]
Ah looks like I can't reopen this PR because it's from a fork. That's a shame. @raffaeler Please reopen this.

**Comment by AdamYoblick** [comment]
Actually I think you need to re-push from your fork and you should be able to re-open this, sorry for the inconvenience.

**Comment by karelz** [comment]
BTW: It is weird we cannot reopen the PR -- I haven't encountered it before, moreover we were able to close & reopen this particular PR 19h ago: https://github.com/dotnet/winforms/pull/115#event-2002946450
... looks like some GitHub hiccup ...

**Comment by dotMorten** [comment]
I'm guessing because the fork was made while the repo was private, the work was private, and still is private.

**Comment by raffaeler** [comment]
@AdamYoblick @karelz I finally did it. As it was on a different branch it was harder to get back the changes and so it took some more time than the other PR.

**Comment by karelz** [comment]
@dotMorten ha, that's a good explanation. Thanks!

**Comment by karelz** [comment]
@raffaeler just curious: You didn't see 'Reopen' button either?

**Comment by raffaeler** [comment]
@karelz no way. My fork also went lost (orphaned) when this repo went public

**Comment by karelz** [comment]
OK, thanks for explanation. That makes sense.

**Pull request closed without merging**
