### PR TITLE
Structify REQRESIZE

### PR DESCRIPTION
**Pull request by hughbe**
## Proposed Changes
- Structify REQRESIZE
- Move to Richedit namespace

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/2079)

### CODE REVIEW

**Comment by zsd4yr** [comment]
LGTM @msftbot please merge if @RussKie approves

**Comment by weltkante** [comment]
@zsd4yr I think the bot wasn't adressed correctly

**Comment by zsd4yr** [comment]
@msftbot please merge if @RussKie approves

**Comment by zsd4yr** [comment]
> @zsd4yr I think the bot wasn't adressed correctly

wow pretty fragile looks like it has to be named before everything? lol

**Pull request merged**
