### PR TITLE
Update dependenices

### PR DESCRIPTION
**Pull request by vatsan-madhavan**
Update dependencies manually - temporary workaround for https://github.com/dotnet/winforms/issues/1304

This change was generated by running `darc update-dependencies --channel ".Net Core 3 Dev"`

### CODE REVIEW

**Comment by vatsan-madhavan** [comment]
This change was generated by running `darc update-dependencies --channel ".Net Core 3 Dev"`

**Comment by RussKie** [comment]
@vatsan-madhavan is this still required?

**Comment by merriemcgaw** [comment]
@RussKie I don't think this is required any more - we've gotten several successful dependency updates since this PR was created

**Pull request closed without merging**
