### PR TITLE
Enable nullability in DataGridViewColumnHeaderCell

### PR DESCRIPTION
**Pull request by gpetrou**
## Proposed changes

- Enable nullability in DataGridViewColumnHeaderCell.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/10127)

### CODE REVIEW

**Comment by gpetrou** [comment]
@lonitra any thoughts on this one?

**Review by SimonZhao888 — DISMISSED** [review]

**Review by lonitra — DISMISSED** [review]

**Comment by lonitra** [comment]
@gpetrou Could you fix conflicts here so we can get this merged

**Comment by gpetrou** [comment]
@lonitra I rebased it, but it looks like we have a problem with `InputLanguage_FromCulture_SupplementalInputLanguages_Expected` test. Perhaps something changed with regards to `nqo` in Windows? @DJm00n maybe has a suggestion since he worked on that.

**Comment by DJm00n** [comment]
@gpetrou do you have exact test failure message?

`InputLanguage_FromCulture_SupplementalInputLanguages_Expected` test installs `nqo` locale that should also install  [N’Ko keyboard](https://learn.microsoft.com/en-us/globalization/keyboards/kbdnko) (KLID: `00090C00`). `InputLanguage.FromCulture()` should also extract `InputLanguage` having `nqo` `CultureInfo`.

It could be somewhat unstable since Windows can have up to 4 installed locals without LCID (they are using `0C00` as LCID) simultaneously.

**Comment by halgab** [comment]
> @lonitra I rebased it, but it looks like we have a problem with `InputLanguage_FromCulture_SupplementalInputLanguages_Expected` test. Perhaps something changed with regards to `nqo` in Windows? @DJm00n maybe has a suggestion since he worked on that.

I also see this failing in all my PRs, even without rebasing. It looks like it's not something that changed in the source code, but more infra related

**Comment by lonitra** [comment]
Failure: 
```
    System.Windows.Forms.Tests.InputLanguageTests.InputLanguage_FromCulture_SupplementalInputLanguages_Expected(languageTag: "nqo", layoutId: "00090C00", layoutName: "N’Ko") [FAIL]
      Assert.Equal() Failure: Strings differ
                  ↓ (pos 1)
      Expected: "N’Ko"
      Actual:   "Nâ€™Ko"
                  ↑ (pos 1)
      Stack Trace:
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageTests.cs(184,0): at System.Windows.Forms.Tests.InputLanguageTests.VerifyInputLanguage(InputLanguage language, String languageTag, String layoutId, String layoutName)
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageTests.cs(152,0): at System.Windows.Forms.Tests.InputLanguageTests.InputLanguage_FromCulture_SupplementalInputLanguages_Expected(String languageTag, String layoutId, String layoutName)
           at InvokeStub_InputLanguageTests.InputLanguage_FromCulture_SupplementalInputLanguages_Expected(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] 
```

This is likely infrastructure issue on CI machines

**Comment by gpetrou** [comment]
@lonitra are you tracking this internally? Maybe we could just open a separate issue and temporarily comment this test case to unblock pending PRs?

**Review by lonitra — APPROVED** [review]

**Pull request merged**
