### PR TITLE
Restore ToolboxSnapDragDropEventArgs implementation

### LINKED ISSUE #6919: ToolboxSnapDragDropEventArgs is not implemented.
### .NET version

6.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

no

### Issue description

While draging a toolbox item from an IToolboxService (implemented by myself) onto a custom control at design time, the corresponding designer's OnDragDrop() won't be hit. and an exception: NotImplementedException was thrown by the  constructor() of class ToolboxSnapDragDropEventArgs.

### Steps to reproduce

1、create an instance of DesignSurface.
2、add a custom IToolboxService impl.
3、add a custom control to IToolboxService.
4、drag the custom control onto the DesignFrame.
5、A NotImplementedException was thrown within Debug window.

### PR DESCRIPTION
**Pull request by RussKie**
Resolves #6919

 `ToolboxSnapDragDropEventArgs` is necessary to facilitate the "general purpose designer" experience as shown in [#6919](https://github.com/dotnet/winforms/issues/6919#issuecomment-1121000602).

## Proposed changes

- Restore `ToolboxSnapDragDropEventArgs` implementation. The type was ported in #122, but had no actual use until #4860, when `ToolboxItemSnapLineBehavior` was ported for .NET 6 Preview5. It looks like a genuine oversight, given the size of #4860.

## Customer Impact

- Without the implemented `ToolboxSnapDragDropEventArgs` it is not possible to provide the "general designer" experience, such as drag-and-drop a control or component from a toolbox.

## Regression? 

- Yes, from .NET Framework

## Risk

- Minimal

### Before

image

### After

image

## Test methodology 

- Manually using the provided sample in #6919: [DesignerSample.zip](https://github.com/dotnet/winforms/files/8651342/DesignerSample.zip)
- I have also reviewed another instances of NIE throughout the codebase, and there doesn't appear to be more issues of this kind. 
image
    * `ComponentDesigner` is largely implemented, and `InitializeExistingComponent` is expected to be implemented by developers of a "general purpose designer". 
    * We don't expect to provide implementations for `ComponentDocumentDesigner` unless there is a strong business justification. 
    * The same applies to `AxImporter`.
    * [`BindingContext.CollectionChanged` event](https://docs.microsoft.com/dotnet/api/system.windows.forms.bindingcontext.collectionchanged#remarks) is obsoleted in .NET Framework

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7184)

### CODE REVIEW

**Review by dreddy-work — DISMISSED** [review]
LGTM.

**Comment by kant2002** [comment]
Can we add integration test to this? Maybe as separate PR. This seems core functionality, and we do not have enough coverage for cases like this.

**Comment by RussKie** [comment]
> Can we add integration test to this? Maybe as separate PR. This seems core functionality, and we do not have enough coverage for cases like this.

Not fair, that's my line! :) 
Yes, I've been thinking about a test, it's kind of non trivial. I'll see if I can put something together.

**Review by JeremyKuhne — DISMISSED** [review]

**Pull request merged**
