### PR TITLE
move Microsoft.NETCore.App to toolset dependencies

### PR DESCRIPTION
**Pull request by zsd4yr**

### CODE REVIEW

**Comment by mmitche** [comment]
Do the corefx dependencies need to move too?

**Comment by zsd4yr** [comment]
> Do the corefx dependencies need to move too?

@mmitche which corefx dependenc(ies)?

**Comment by zsd4yr** [comment]
> > Do the corefx dependencies need to move too?
> 
> @mmitche which corefx dependenc(ies)?

spoke offline; all of them, circling back to discover if these are burned into the product

**Comment by ericstj** [comment]
WinForms only publishes a transport package.  This won't refer to the version of CoreFx packages it references, nor will it repack those dlls.  As such, I don't believe anything is burned in.

**Comment by mmitche** [comment]
Yay!

**Comment by zsd4yr** [comment]
thanks all!

**Pull request merged**
