### PR TITLE
Update SDK version

### PR DESCRIPTION
**Pull request by dreddy-work**
Update SDK version in main

This is usually expected via Arcade update but given the branch stabilization work is ongoing, manually updating to unblock the flow of WinForms into Installer.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/9951)

### CODE REVIEW

**Comment by dreddy-work** [comment]
@mmitche as FYI

**Review by JeremyKuhne — DISMISSED** [review]

**Comment by JeremyKuhne** [comment]
@dreddy-work is there an associated issue?

**Comment by dreddy-work** [comment]
> @dreddy-work is there an associated issue?

No. this is being done to unblock the dependency flow (https://github.com/dotnet/wpf/pull/8196) and generally should be done via Arcade update.

**Comment by RussKie** [comment]
Consider updating the SDK at regular intervals. E.g., dotnet/aspnetcore, dotnet/extensions, dotnet/efcore do that every week.

**Comment by dreddy-work** [comment]
> Consider updating the SDK at regular intervals. E.g., dotnet/aspnetcore, dotnet/extensions, dotnet/efcore do that every week.

Arcade is generally doing this every month.  I will monitor in the main how this goes and add a checklist based on it.

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
