### PR TITLE
Accessibility: Fixing Name property of "Description” pane and "ToolBar" pane in PropertyGrid

### LINKED ISSUE #1178: Accessibility: Name property of "Description” pane and "ToolBar" pane in PropertyGrid must not include the same text as its LocalizedControlType/ControlType properties
**Repro steps:**
1. Create .Net Core Winforms app
2. Add to app PropertyGrid control
3. Open the Inspect tool and take a look at the PropertyGrid tree

**Actual:**
1. For “Description” pane in PropertyGrid, Name property of “Description” pane in PropertyGrid includes the same text as its LocalizedControlType/ControlType properties
2. For “ToolBar” in PropertyGrid, Name property of Toolbar in PropertyGrid includes the same text as its ControlType property

   image

**Expected result:**
Name property of "Description” pane and  "ToolBar" pane in PropertyGrid must not include the same text as its LocalizedControlType/ControlType properties

### PR DESCRIPTION
**Pull request by vladimir-krestov**
Fixes #1178. 
It needs review translation.

### CODE REVIEW

**Comment by vladimir-krestov** [comment]
Now it looks like this:

image

**Comment by zsd4yr** [comment]
@janbaltus Could we get you all to give a pass on the translation files to ensure that they are appropriate for this fix?

**Comment by zsd4yr** [comment]
@vladimir-krestov 	did you ensure that the translations also match those in .NET FX or only the English / logical name?

**Comment by vladimir-krestov** [comment]
@zsd4yr Currently, only `<source>` names have been fixed. It is necessary to translate all names in different languages.

**Comment by janbaltus** [comment]
@zsd4yr the translation match and we will prepare PR soon

**Comment by janbaltus** [comment]
@zsd4yr when checking source in Netfx we can still see "Description Pane" and in Winforms we can see "Descrption". We cannot make them consistent as source is different.
ID both in Netfx and Winforms is 

PBRSDocCommentPaneTitle

obrazek

**Pull request merged**
