### PR TITLE
Add some ListView tests and more Control tests

### PR DESCRIPTION
**Pull request by hughbe**
## Proposed Changes
- Add more Control tests
- Add ListView construction tests

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/1925)

### CODE REVIEW

**Comment by hughbe** [comment]
Hmmm.. This seems to cause hangs

**Comment by RussKie** [comment]
> Hmmm.. This seems to cause hangs

Can you narrow it down to what the cause is?

**Comment by hughbe** [comment]
Would love to, except currently cannot due to https://github.com/dotnet/winforms/issues/1933

**Comment by hughbe** [comment]
> Can you narrow it down to what the cause is?

Bit more research. XUnit doesn't like it when a `ThreadStateException` is thrown asynchronously (i.e. somewhere between `CreateHandle` and the end of the test method). It hangs as it displays a little message box popup with the error. Fixed this test bug

**Pull request merged**
