### PR TITLE
Switch to using globalconfig instead of ruleset for analyzer configuration

### PR DESCRIPTION
**Pull request by gpetrou**
## Proposed changes

- Based on https://github.com/dotnet/runtime/pull/57144
- I converted the files by using Visual Studio UI as described in https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#convert-an-existing-ruleset-file-to-editorconfig-file

I used the following PowerShell script to verify that the conversion was successful.

```PowerShell
# Establish and enforce coding rules in expressions, scripts, and script blocks.
Set-StrictMode -Version Latest
$errorActionPreference = "Stop"

[xml]$xmlDocument = Get-Content "PATH_TO_Shipping.ruleset"
$globalConfigLines = [IO.File]::ReadAllLines("PATH_TO_CodeAnalysis.src.globalconfig")

$rules = $xmlDocument.RuleSet.Rules.Rule

foreach ($rule in $rules) {
    $ruleId = "." + ($rule.Id)
    $ruleAction = $rule.Action.ToLower()
    if ($ruleAction -eq "info") {
        $ruleAction = "suggestion"
    }

    $found = $false
    foreach ($line in $globalConfigLines) {
        if ($line.Contains($ruleId)) {
            if (!$line.Contains(" = $ruleAction")) {
                Write-Host "Different value for $ruleId!"
            }

            $found = $true

            break
        }
    }

    if (!$found) {
        Write-Host "$ruleId is missing!"
    }
}
```

After this is merged, we could update the analyzers package to take advantage of new features and bug fixes.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7000)

### CODE REVIEW

**Review by Tanya-Solyanik — APPROVED** [review]
Looks good

**Comment by gpetrou** [comment]
I see that this has been approved. Could we merge it?

**Review by RussKie — COMMENTED** [review]
How do the new files get referenced?

**Comment by gpetrou** [comment]
> How do the new files get referenced?
We still reference them in eng/CodeStyle.targets file.

**Comment by RussKie** [comment]
> We still reference them in eng/CodeStyle.targets file.

Thank you. For some strange reason I couldn't see that diff from the phone.

**Pull request merged**
