### PR TITLE
Remove Click Once code

### PR DESCRIPTION
**Pull request by hughbe**
I understand that this is not enabled in winforms and actually isn't supported in .NET Core

### CODE REVIEW

**Comment by danmosemsft** [comment]
@merriemcgaw or @OliaG can you confirm this is the case?

**Comment by hughbe** [comment]
Evidence: https://github.com/dotnet/corefx/blob/a6f76f4f620cbe74821c6445af3f13e048361658/src/System.Configuration.ConfigurationManager/src/System/Configuration/ApplicationSettingsBase.cs#L752-L765

**Comment by zsd4yr** [comment]
> @merriemcgaw or @OliaG can you confirm this is the case?

Can confirm. We have been pointing folks to [Microsoft MSIX](https://docs.microsoft.com/en-us/windows/msix/overview) for packaging, deployments, and updating

**Comment by hughbe** [comment]
Awesome!

**Comment by zsd4yr** [comment]
> Awesome!

@hughbe how confident are you that this is all of the Click Once code that needs to be removed. @merriemcgaw please advise on this one before we decide whether or not to take it

**Comment by merriemcgaw** [comment]
@danmosemsft and @zsd4yr it is correct that we are not supporting ClickOnce on Core. So this is something we can certainly take.

**Comment by softboy99** [comment]
bad, MSIX only support win10, so many win7 PCs cannot use it. If you decide to use MSIX, please extend it to win7 platform. Otherwise, Please keep clickonce in net core. Thanks a lot!!!!!

**Comment by merriemcgaw** [comment]
@rconard, have you been looking into this lately?

**Comment by rconard** [comment]
@merriemcgaw, you may say l want to reach out to @nakarnam. She's taking point.

**Comment by merriemcgaw** [comment]
@rconard - so sorry! Yes @nakarnam is looking into this issue and may be able to give you some updates.

**Pull request merged**
