### PR TITLE
correct defaultValue of ListView.HideSelection

### PR DESCRIPTION
**Pull request by trivalik**
Fixes #
correct defaultValue of ListView.HideSelection

## Proposed changes

- 
- 
- 

## Customer Impact

- Designer for ListView.HideSelection serialize correct
- 

## Regression? 

- No

## Risk

- 0

## Test methodology 

- 
- 
- 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/4968)

### CODE REVIEW

**Comment by RussKie** [comment]
Please refer to [the docs](https://docs.microsoft.com/dotnet/api/system.windows.forms.listview.hideselection#property-value)

**Comment by weltkante** [comment]
To be fair, the docs state the default value is supposed to be `false`. I've only taken a quick look but it may be possible that .NET 4.8 and/or .NET Core port has been breaking the designer metadata by changing the runtime default without replacing the `[DefaultValue]` attribute with a proper `ShouldSerialize` callback usually used for these scenarios.

@trivalik if you want to follow up on this and there is indeed a bug then you should follow the usual procedure of opening an issue describing the problem, so it can be analyzed and discussed what the best way to fix it is

**Comment by RussKie** [comment]
My apologies, had a long day yesterday, and totally misread it. Thank you for straightening things out @weltkante.

**Comment by weltkante** [comment]
Note that changing `[DefaultValue]` is certainly not a "Risk 0" change without having done a thorough analysis because it changes how the designer interprets serialized code. Depending how broken this currently is it may be acceptable, but I think the scenario should first be examined in an issue.

(The alternative to `[DefaultValue]` would be switching to a `ShouldSerializeHideSelection` + `ResetHideSelection` method pair.)

**Comment by dreddy-work** [comment]
@trivalik , I second what @weltkante  said above. We should follow process of opening a bug describing the scenario and impact of the change. If this is not a regressions, we should also consider how this impact the applications being migrated from .NET framework. 'ShouldSerialize***' and default values should be in sync.

**Comment by trivalik** [comment]
https://github.com/dotnet/winforms/issues/4984

**Comment by dreddy-work** [comment]
@trivalik, Can you please update the template in this PR too?

**Review by dreddy-work — APPROVED** [review]
LGTM.

**Comment by dreddy-work** [comment]
@Tanya-Solyanik, do you anticipate any issue with this in the designer/serialization?

**Comment by Tanya-Solyanik** [comment]
In .NET Framework 4.7.2 and earlier, default value was `true`.
In .NET Framework 4.8 default value attribute still says `true` -  https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ListView.cs,0ceaaf8a1f820b56 in order to avoid VS designer updating .designer.cs files and the runtime interpreting the previous default incorrectly *unconditionally*, but control is conditionally initialized to `false` to support the preferred accessibility default at runtime. https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ListView.cs,236

In .NET Core we have a chance to implement a cleaner fix, i.e. introduce a breaking change for designer serialization but remove the "silent" correction of the value in the constructor (already done).

I would go with this change but document it as breaking for apps ported from 4.7.2 because their default value will be interpreted differently. BUT the new default value will be accessible.

**Pull request merged**
