### PR TITLE
Fix exception dialog handling.

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Test fixtures do not run on the same thread the test method executes on when marked with `[WinFormsFact]` or `[StaFact]`. This change removes the test fixture and adds a new context switch to throw thread exceptions.

Initialization of the switch is done programmatically via a module initializer. The module initializer will also set the starting cursor position to avoid spurious errors in tests due to cursor positioning.

The Cursor tests were the ones modifying the cursor position and causing intermittent errors in other tests. Moved them to their own collection and forced them to run sequentially.

Cleaned up WindowsFormsSynchronizationContext.

Simplified checks in LocalAppContextSwitches. We shouldn't be conditioning on supported OS beyond checking for API availability. We don't support Windows 7, but we won't deliberately cause WinForms apps to crash on Windows by calling later APIs without checking for support. We will not add additional complexity to the code beyond that for unsupported OS platforms.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8695)

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
Fixes: #8657

**Review by lonitra — APPROVED** [review]
🥳

**Comment by Tanya-Solyanik** [comment]
>We shouldn't be conditioning on supported OS beyond checking for API availability. 

This is pretty much the case of API availability. PMv2 is not available on these OSs, if the user app follows that path, hits the unavailable API, we don't have a way to handle it cleanly.

I would rather  factor this change out of this PR and investigate it more.

**Comment by JeremyKuhne** [comment]
> This is pretty much the case of API availability. PMv2 is not available on these OSs, if the user app follows that path, hits the unavailable API, we don't have a way to handle it cleanly.

It should be done at the consuming site or clearly documented here ("this feature uses APINAME which requires OS blah").

**Comment by JeremyKuhne** [comment]
> I would rather factor this change out of this PR and investigate it more.

I'm out for a week and this is needed for additional test work so I'm not going to pull it out.

**Comment by RussKie** [comment]
Nice!

**Pull request merged**
