### PR TITLE
Rename tests

### PR DESCRIPTION
**Pull request by RussKie**
* Ensure all tests have "Tests" suffix (tests/System.Windows.Forms)
* Fix selected namespaces (tests/System.Windows.Forms)

### CODE REVIEW

**Comment by Tanya-Solyanik** [comment]
@bryukov and @M-Lipin  - Please be aware of this rename.

**Comment by zsd4yr** [comment]
@RussKie can we ensure this fix applies after #439 is in and that you've had a chance to look over the tests added in that PR as well?

**Comment by RussKie** [comment]
I'm a bit unsure what to do about the integration tests yet.
I think they should be renamed too, but I'm having troubles building the solution atm and can't check


> we ensure this fix applies after #439 is in and that you've had a chance to look over the tests added in that PR as well?

Sure, np

**Comment by zsd4yr** [comment]
@RussKie #439 is in, so just double check this and then I am satisfied to take it :)

**Comment by RussKie** [comment]
Rebased.

Validated by running the following script:
```powershell
PS C:\winforms\src\System.Windows.Forms\tests> 

Get-ChildItem -Path .\ -Include *.cs -Exclude *Tests.cs -Recurse | ForEach-Object {
    $_.FullName
}


C:\winforms\src\System.Windows.Forms\tests\Common\TestHelper.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\System.Windows.Forms.IntegrationTests\ExternalTestHelpers.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\System.Windows.Forms.IntegrationTests\IFunctionalPathTest.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\System.Windows.Forms.IntegrationTests\TestHelpers.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\System.Windows.Forms.IntegrationTests\WinformsControlsTest.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\Buttons.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\Buttons.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\Calendar.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\Calendar.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\ComboBoxes.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\ComboBoxes.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\CurrentDPILabel.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\DataGridViewHeaders.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\DataGridViewHeaders.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\DateTimePicker.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\DateTimePicker.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\DesignTimeAligned.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\DesignTimeAligned.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\ListViewTest.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\ListViewTest.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MainForm.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MainForm.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MdiChild.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MdiChild.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MDIParent.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MDIParent.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MenuStripAndCheckedListBox.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MenuStripAndCheckedListBox.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MultipleControls.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MultipleControls.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\Panels.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\Panels.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\Program.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\PropertyGrid.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\PropertyGrid.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\ScalingBeforeChanges.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\ScalingBeforeChanges.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\Splitter.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\Splitter.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\TreeViewTest.cs
C:\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\TreeViewTest.Designer.cs
C:\winforms\src\System.Windows.Forms\tests\UnitTests\TestHelper.cs

PS C:\winforms\src\System.Windows.Forms\tests> 
```

Until I can build integration tests I'm not renaming them (related #508).

**Comment by zsd4yr** [comment]
LGTM

**Comment by zsd4yr** [comment]
Thank you @RussKie 😄 :shipit:

**Comment by RussKie** [comment]
No worries 😉 

I see you "squash-merged" my changes. Is that a preferred practice in this repo?

**Comment by zsd4yr** [comment]
@RussKie we usually squash merge unless asked otherwise; then we consider not squashing, but the history of the repo is ultimately a code-owner decision. We try to respect PR owner's decisions when they are indicated, but may take some liberties

**Comment by RussKie** [comment]
Sure, I'm just trying to establish the inhouse rules.

We had similar discussions at https://github.com/gitextensions/gitextensions/ repo few years ago, and more or less reached a conclusion that it is up to the author to present a PR in a meaningful state (without "fix a typo" or "addressed feedback" commits). Otherwise squash-merge may result in an incomprehensible diff and becomes hard/impossible to blame or bisect in event of a regression.

**Comment by zsd4yr** [comment]
> Sure, I'm just trying to establish the inhouse rules.
 
Other repos in the dotnet space (example: Roslyn) follow the methodology you specified. Most of our branches and pull requests are worked on by a single individual (some notable exceptions like #439 and #224 come to mind) and are intended to be atomic changes, complete with tests -- so reverting a single one _should be_ "easy" in our case. 

That said, I can see how other repos who take lots of smaller changes much much faster than we do would benefit from the model of each contributor making their best effort to write useful, complete, and non-trivial history. I think this would be great, and so if a contributor wants to ask us not to squash their history on the way in, then I am happy to read over the commit messages and --if I am satisfied-- do as they ask. However, asking contributors to do this across the board is, in my opinion (not speaking for the whole team here), certainly a barrier to entry (possibly a small one sure, but still) and I think that this should not be the default expectation.

**Comment by RussKie** [comment]
Thanks, I'll keep that in mind
:+1:

**Pull request merged**
