### PR TITLE
Enable nullability in TableLayoutCellPaintEventArgs

### PR DESCRIPTION
**Pull request by gpetrou**
## Proposed changes

- Enable nullability in TableLayoutCellPaintEventArgs.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/4932)

### CODE REVIEW

**Comment by weltkante** [comment]
Making `Graphics` / `PaintEventArgs` not nullable seems inconsistent with the other PR (#4931) where classes were made nullable in the event object. Oversight or is this a case-by-case decision for which event object its made nullable and for which it isn't?

**Comment by RussKie** [comment]
All good. 
Could you please rebase on the latest main?

**Comment by RussKie** [comment]
> Making `Graphics` / `PaintEventArgs` not nullable seems inconsistent with the other PR (#4931) where similar arguments were made nullable in the event object. Is this an oversight or is it a case-by-case decision for which event object its made nullable and for which it isn't? It would be nice if e.g. the `Graphics` nullability were consistent across classes?

This PR is correct, whilst #4931 isn't - graphics/painting API must have a valid `Graphics` instance.

**Review by dreddy-work — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
