### PR TITLE
Update language format from ll_CC to LCID

### PR DESCRIPTION
**Pull request by dreddy-work**
Related to #9556

loc team says ll-CC format is not working for some reason and suggested to change the format to LCID.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/9566)

### CODE REVIEW

**Comment by elachlan** [comment]
CC: @DJm00n 

@dreddy-work aren't LCIDs deprecated?

**Comment by dreddy-work** [comment]
> @dreddy-work aren't LCIDs deprecated?

LCIDs in this PR are used for Loc translation by an internal tool. the way our pipeline setup, their tools were confused between `fr` and `fr-FR` and asked us to mention LCID to avoid it.

**Comment by elachlan** [comment]
This will be a pain to maintain in the future. Is it possible to raise an issue to change it back once the internal tool's issue is resolved?

**Comment by Tanya-Solyanik** [comment]
Please get an approval from the loc team

**Review by Tanya-Solyanik — DISMISSED** [review]

**Comment by dreddy-work** [comment]
> This will be a pain to maintain in the future. Is it possible to raise an issue to change it back once the internal tool's issue is resolved?

I don't expect these files to change except for adding new strings. And we do not use `Locked` attribute on new strings. Regarding the deprecation of LCIDs, where did you read it? LCIDs are used all over .NET (language specific URLs for documentation use them)

**Comment by elachlan** [comment]
It was mentioned in #8573.

It was under: https://learn.microsoft.com/en-us/globalization/locale/standard-locale-names#the-deprecation-of-lcids

But it looks like that was removed? I can't find it via wayback archive.org

**Comment by DJm00n** [comment]
@dreddy-work

>Regarding the deprecation of LCIDs, where did you read it? LCIDs are used all over .NET (language specific URLs for documentation or product download redirections use them)

Also https://github.com/dotnet/runtime/issues/82367#issuecomment-1436061801

**Review by crsuzukimsft — APPROVED** [review]

**Review by Tanya-Solyanik — APPROVED** [review]

**Pull request merged**
