### PR TITLE
Fix skipping TableLayoutSettings_Serialize_InvalidStringConverter_DeserializeThrowsSerializationException

### LINKED ISSUE #3046: Fix and re-enable tests disabled by #3045
https://github.com/dotnet/winforms/pull/3045 has disabled two tests. 

Some exception types seem to be thrown unwound - so instead of receiving `TargetInvocationExeption` the inner-exception type is directly observed. 

These tests need to be investigated, fixed and re-enabled. 

/cc @RussKie, @AdamYoblick, @merriemcgaw, @dotnet/dotnet-winforms

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #3046 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3217)

### CODE REVIEW

**Comment by weltkante** [comment]
This alone does not fix #3046, there's also `AxHost_GetIPictureDispFromPicture_InvokeEnhancedMetafile_Roundtrips` which had been disabled for this issue. Just mentioning it so it doesn't get missed.

**Comment by hughbe** [comment]
Oh yes, sorry. I have now renabled that test you mentioned. I think this should be enough, because the test doesn't seem to refer to `TargetInvocationException`

**Comment by weltkante** [comment]
It also does, see [here](https://github.com/dotnet/winforms/blob/89dcfb86aaf8d6fbb2345c35a639d5f96308a20b/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs#L1635)

**Comment by hughbe** [comment]
I think I am blind...

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
