### PR TITLE
Update branding for 5.0.10

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Review by RussKie — CHANGES_REQUESTED** [review]
@vseanreesermsft please provide the background for this PR.

**Comment by dreddy-work** [comment]
> @vseanreesermsft please provide the background for this PR.

As said in the email, seems they are trying to auto generate these for branding.  Are you expecting anything else?

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
Aye, saw the email. Thank you 👍

**Review by dreddy-work — APPROVED** [review]
Will be merged once we get 'Go ahead'

**Comment by wtgodbe** [comment]
@dreddy-work @RussKie any idea about the test failures?

**Comment by dreddy-work** [comment]
> @dreddy-work @RussKie any idea about the test failures?

that is a flaky test. i see they are being rerun.

**Pull request merged**
