### PR TITLE
Replace bitmap with Icon

### PR DESCRIPTION
**Pull request by dreddy-work**
related to #8358 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8370)

### CODE REVIEW

**Comment by Tanya-Solyanik** [comment]
How did you test it?

**Comment by dreddy-work** [comment]
> How did you test it?

This entire folder was replaced when we moved to Icons. Logical name is not changed. So, general `GetBitmap ` shouldn't have impact. I see Core designer is embedding resources separately..

**Comment by dreddy-work** [comment]
Also, linked PR is adding unit tests for basic bitmap loading functionality.

**Comment by elachlan** [comment]
Also, since its `System.Windows.Forms.Design.Behavior.MoverGlyph` can you place it in the `Behavior` subfolder?

**Comment by elachlan** [comment]
This PR can be closed as it has been implemented in #8358

**Comment by Tanya-Solyanik** [comment]
This change is already merged as https://github.com/dotnet/winforms/pull/8358

**Pull request closed without merging**
