### PR TITLE
[release/8.0] Correct TargetingPackVersion and RuntimeFrameworkVersion

### PR DESCRIPTION
**Pull request by dkurepa**
Fixes: https://dev.azure.com/dnceng/internal/_build/results?buildId=2264519&view=results. Detected during the .NET 8 Test build

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/9939)

### CODE REVIEW

**Comment by dreddy-work** [comment]
@dkurepa , why this new change now?  It was checked against `VSRedistCommonNetCoreSharedFrameworkx6480PackageVersion` always.

**Comment by dkurepa** [comment]
`VSRedistCommonNetCoreSharedFrameworkx6480PackageVersion` doesn't stabilize. Also, this is how release/7.0 is setup https://github.com/dotnet/winforms/blob/release/7.0/Directory.Build.targets

**Comment by dreddy-work** [comment]
what about other places? https://github.com/search?q=repo%3Adotnet%2Fwinforms%20VSRedistCommonNetCoreSharedFrameworkx6490PackageVersion%20&type=code

**Comment by dkurepa** [comment]
`global.json` has an unstable version reference in `release/7.0`, so that should be fine https://github.com/dotnet/winforms/blob/release/7.0/eng/Versions.props

**Comment by dreddy-work** [comment]
> `global.json` has an unstable version reference in `release/7.0`, so that should be fine https://github.com/dotnet/winforms/blob/release/7.0/eng/Versions.props

Should it be changed as well? I wanted to know if the reference to `VSRedistCommonNetCoreSharedFrameworkx6480PackageVersion` can be completely removed?  @mmitche

**Comment by dkurepa** [comment]
It should be referencing an unstable package coming from runtime, so we could change it to something like `MicrosoftNETCoreILDAsmPackageVersion`

**Comment by dreddy-work** [comment]
> It should be referencing an unstable package coming from runtime, so we could change it to something like `MicrosoftNETCoreILDAsmPackageVersion`

Any other repos doing this?  @mmitche  can this be done in main ( if not in this repo?) .. I am unblocking this PR for now and whatever the result of this discussion is later decided to be ported or not.

**Review by dreddy-work — APPROVED** [review]

**Comment by mmitche** [comment]
You can reference any package coming from runtime that:
- Ships every release
- Is non-stable

MicrosoftNETCoreILDasm is not non-stable in after RTM, and doesn't ship every release: https://www.nuget.org/packages/Microsoft.NETCore.ILDAsm/7.0.0

**Pull request merged**
