### PR TITLE
Enable IDE0074 Use compound assignment

### PR DESCRIPTION
**Pull request by elachlan**
Enables IDE0074 Use compound assignment

Related #7887

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7921)

### CODE REVIEW

**Comment by dreddy-work** [comment]
@elachlan build failures in release. 
src\System.Windows.Forms.Design\src\System\ComponentModel\Design\ReferenceService.cs#L375
src\System.Windows.Forms.Design\src\System\ComponentModel\Design\ReferenceService.cs(375,25): error IDE0074: (NETCORE_ENGINEERING_TELEMETRY=Build) Use compound assignment

**Comment by elachlan** [comment]
> @elachlan build failures in release. src\System.Windows.Forms.Design\src\System\ComponentModel\Design\ReferenceService.cs#L375 src\System.Windows.Forms.Design\src\System\ComponentModel\Design\ReferenceService.cs(375,25): error IDE0074: (NETCORE_ENGINEERING_TELEMETRY=Build) Use compound assignment

Refactored it a bit around that property since it had too many if statements.

**Comment by RussKie** [comment]
MC

**Review by RussKie — APPROVED** [review]
🎉

**Comment by elachlan** [comment]
@RussKie I think this is another flaky test.

**Review by dreddy-work — APPROVED** [review]

**Pull request merged**
