### PR TITLE
Fix index script

### PR DESCRIPTION
**Pull request by dreddy-work**
Fixing script in the github actions PR.

related #6678 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/6679)

### CODE REVIEW

**Comment by dreddy-work** [comment]
@RussKie correct script in this PR.

**Comment by RussKie** [comment]
That's better :)

**Comment by dreddy-work** [comment]
was corrected on fork but topic branch was not corrected earlier.

**Comment by dreddy-work** [comment]
testing.

**Comment by dreddy-work** [comment]
Again!

**Pull request merged**
