### PR TITLE
Fix menu arrow key navigation

### LINKED ISSUE #3272: MenuStrip arrow key navigation goes in the wrong direction
* .NET Core Version: 
At least current master (5.0.100-preview.5.20251.2), but I recall seeing the issue since at least .NET Framework 2.0

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**

With a populated MenuStrip, and focus on ToolStripMenuItem that is not top-level, focus shifts in the reverse direction to the arrow key (i.e. pressing the left arrow key causes focus to shift to the right, and pressing the right menu key causes focus to shift to the left). When the focus is on a top-level item, focus shifts in the correct direction.

**Expected behavior:**
Pressing an arrow key should move in the direction of the arrow

**Minimal repro:**
The problem is reproducible with the MenuStripAndCheckedListBox winforms test

### PR DESCRIPTION
**Pull request by jeremy-visionaid**
Fixes #3272 

## Proposed changes

Fix menu navigation

## Regression? 

- No

## Risk

-

## Test methodology 

Manual testing with MenuStripAndCheckedListBox 

## Test environment(s) 

.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.5.20262.6
 Commit:    9ad967d49e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.5.20262.6\

Host (useful for support):
  Version: 5.0.0-preview.6.20262.3
  Commit:  210a82a2e7

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.5.20262.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.5.20255.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20262.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20261.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3274)

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
Can you please add details to the commit that summarizes what the fix is and why it became necessary to change the code (i.e. briefly summarize your investigation). From my read the bug manifests after some version of Win10, but did not in Win7.  Did you validate that the behavior on Win7 is still ok after the fix?

Outside of those housekeeping tasks, the fix looks straight-forward and correct as far as I can tell.

**Comment by jeremy-visionaid** [comment]
@JeremyKuhne - AFAIK, this bug isn't related to Windows 7/10. It has been around for several years: https://stackoverflow.com/questions/16305454. I think I recall seeing it in .NET 2.0 and filed a bug at the time (which has long since been forgotten).

However, there also appear to be separate issues where menu drop-downs are displayed on the wrong side in some OS versions and APIs. My guess is that there are two other bugs which cause that - one in Windows 10 Win32 API, and another in WinForms.

I have validated that at least the menu arrow key direction is correct on both Windows 7 and 10 with this change. I don't think that it would need to be reverted if the display issues are fixed, since the keyboard navigation should behave the same - but it's hard to be certain without fixing those too. At least this gets us a step closer to the correct behavior.

**Comment by RussKie** [comment]
Thank you for the fix, it looks sensible. I've sent it off to our test team to verify we're not regressing in unexpected places.

**Comment by RussKie** [comment]
Thank you!

**Pull request merged**
