### PR TITLE
Update editorConfig with preferred C#/VB setting 1/3

### PR DESCRIPTION
**Pull request by paul1956**
This is a Draft that separates 3 preferences for VB from C# in .editorConfig

## Proposed changes

Separate 3 options where C# wants true:silent and I propose VB wants false:Suguestion
dotnet_style_coalesce_expression
dotnet_style_prefer_conditional_expression_over_assignment
dotnet_style_prefer_conditional_expression_over_return

Also VB only add
dotnet_separate_import_directive_groups = false:warning ' need to verify syntax

## Customer Impact
None this is just to establish Visual Basic specific style for Repo agreed upon by team working on VB

## Regression? 
- None, its to improve consistancy and easy of reading VB code by none VB Programmers.

## Risk
- None, it may just product some extra suguestions that I will fix in a follow on PR. 

## Test methodology 
No code changes

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/winforms/pull/11056)

### CODE REVIEW

**Comment by paul1956** [comment]
@KlausLoeffelmann @JeremyKuhne This is a place for you to discuss and comment on VB Style. I really don't care as long as everyone agrees I will update code to match.

**Comment by paul1956** [comment]
@JeremyKuhne  @KlausLoeffelmann @echalone Ping, can someone review its 9 lines and will stop a lot of Merge Conflicts as editorConfig is edited. C# functionality is unchanged., VB gets settings more in line with VB and Repo..

**Comment by paul1956** [comment]
Thanks.

**Comment by paul1956** [comment]
@KlausLoeffelmann  This needs to be merger first with anything Jeremy Kuhne is changing. That will eliminate conflicts.

Is there a GetTempSubdirectory? I need that to test the VB functions that fail if the tempFile is a directory, and create one if it doesn't exist plus some of the accessibility(permissions) paths. I just don't see a safe way to get to 100% coverage otherwise and it's these corner cases that will break existing code.

**Comment by echalone** [comment]
I feel honored being mentioned, but I don't know why since I'm not part of the dotnet or any microsoft repository :D

**Comment by paul1956** [comment]
> I feel honored being mentioned, but I don't know why since I'm not part of the dotnet or any microsoft repository :D

Sorry typo on my part.

**Pull request merged**
