### PR TITLE
Make DesignerActionHeaderItem public

### PR DESCRIPTION
**Pull request by hughbe**
This is public in System.Design.dll

### CODE REVIEW

**Comment by danmosemsft** [comment]
This would need removing from https://github.com/dotnet/winforms/blob/master/src/System.Design/src/ApiCompatBaseline.netcoreapp.txt#L9 (I don't think the build flags extra entries)

But there are plenty of others listed there -- @ericstj is there some reason for all these? Is it just incomplete work or by design?

**Comment by danmosemsft** [comment]
I am wondering whether we need a work item to clear out more of the baseline.

**Comment by hughbe** [comment]
#1059

**Comment by zsd4yr** [comment]
@ericstj any thoughts here? Sorry if you already chatted with @danmosemsft offline

**Comment by ericstj** [comment]
@danmosemsft these all represent types present in System.Design in desktop but not present in WindowsForm's version of the System.Design.dll facade.  Since System.Design contains designer related code for Drawing, WinForms, Data, and Web, not all of it will be surfaced by this repo, so I believe it's expected to see some difference in that file.  I think it makes sense to review the differences and file issues for any times which are needed for the WinForms scenarios.
.

**Comment by hughbe** [comment]
Is this good to merge anyway tho? I’ve opened an issue tracking some fixes and will go thru when I have time

**Comment by ericstj** [comment]
Absolutely, and thank you for the contribution.  Sorry that wasn't clear.

**Pull request merged**
