### PR TITLE
Refactor `WeakRefCollection` to replace `ArrayList` with `List<T>`

### PR DESCRIPTION
**Pull request by elachlan**
Related: #8140

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/10281)

### CODE REVIEW

**Comment by elachlan** [comment]
@halgab could you please give this a quick review?

**Review by halgab — APPROVED** [review]
Happy to help!
I just see a minor potential improvement.

I don;t know if you've noticed, but this type is also defined [here](https://github.com/dotnet/winforms/blob/ad0a844cca5e4fc02217dd585823531588356ff1/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/WeakRefCollection.cs#L6). I don't know if code consolidation between the winforms projects and System.Drawing.Common is something that should be considered, knowing that the latter targetting netfx makes it less profitable.

Other open questions I have about this type (but that are outside the scope of this PR):

- should this be made generic?
- if that's the case, should we be using `WeakReference<T>` under the hood? And more generally should we try and replace `WeakReference` with its generic counterpart across codebase?

**Comment by JeremyKuhne** [comment]
@elachlan I don't think there is any real difference between the two `WeakRefCollection` classes. Presuming they are the same, it would be worth merging to `Common` and linking into both projects.

It would also be worth looking at whether these can be typed. Can this be `WeakRefCollection<T>`? And more correctly: `WeakReferenceList<T> : IList<T>`??

**Comment by elachlan** [comment]
@JeremyKuhne what namespace do you want me to use if we merge them?

**Comment by elachlan** [comment]
Closing in favor of #10291

**Pull request closed without merging**
