### PR TITLE
Modernize folderdialog

### LINKED ISSUE #1: Modernize FolderBrowserDialog
The Windows Forms `FolderBrowserDialog` uses an old folder picker control. Starting in Windows Vista, there is a newer COM-based control available.

My proposal is to enhance the existing `FolderBrowserDialog` to use that newer control by default when running on Vista and higher.

The existing API can be used, but the newer API gives us a few new options:

1. The default location may be any folder, not just a known folder. The current API uses an enum for the [RootFolder](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/FolderBrowserDialog.cs,158). How should we take this forward to allow a user to set the path? One option could be to document that the property has no effect if the Vista style dialogs are used. This is what Ookii dialogs does.
2. [SelectedPath](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/FolderBrowserDialog.cs,123) has a setter, should we use that value as the default folder? Ookii uses this property as the default and then to retrieve the selection.
3. [ShowNewFolderButton](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/FolderBrowserDialog.cs,94) is always visible on the new dialog. The doc comments can be updated to reflect this.
4. The new dialog has a `Title` property. We can add that.
5. Presumably there should be a property to allow a user to choose the original dialog. What should we call it?

Does .NET Core 3 support pre-Vista operating systems? Do we need to consider that, or can Vista detection code be removed? How about CAS and Security Demand code? Does that need to remain or be added for net-new code or can that be removed & omitted for .NET Core?

### PR DESCRIPTION
**Pull request by onovotny**
This PR fixes #1 by implementing a Vista-style folder dialog.

Current dialog:
image

With this PR, the Vista-style dialog:
image

### CODE REVIEW

**Comment by shanselman** [comment]
:shipit:

**Comment by LanceMcCarthy** [comment]
This was an epic PR

**Comment by daniel-white** [comment]
Awesome to see this sort of transparency w/ Windows Forms!

**Comment by mattiascibien** [comment]
Been waiting for this since Windows Vista 👍

**Comment by orange-pig** [comment]
Epic update

**Comment by samuelGrahame** [comment]
This is amazing

**Comment by KevinAdams05** [comment]
Was the icon updated? The screenshot shows that it has the default form icon.

**Comment by samuelGrahame** [comment]
> Was the icon updated? The screenshot shows that it has the default form icon.

maybe it gets it from the running program, but good point.

**Comment by RussKie** [comment]
docs - https://github.com/dotnet/docs/issues/14153

**Pull request merged**
