### PR TITLE
Fix LocProject to fix Loc build failure in the internal pipeline.

### PR DESCRIPTION
**Pull request by dreddy-work**
Fix Loc build failure in the [pipeline](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D1969362%26view%3Dlogs%26j%3Dc2111129-d6a3-58de-e667-00e5a0966c99%26t%3D04624205-1088-500d-206a-392ceb108efa&data=05%7C01%7Cdreddy%40microsoft.com%7Cbf0da489396e43bcdd1508da8ad5db37%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637974948372288605%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NgG5EL%2BiI5Ct81cXX6xd1pmKJO9JhK2AeUJ9W%2FW6jdA%3D&reserved=0) that was introduced [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fpull%2F7604&data=05%7C01%7Cdreddy%40microsoft.com%7Cbf0da489396e43bcdd1508da8ad5db37%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637974948372288605%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kYLgePf5k6YdhjUqWAMn%2FbyU5jGXZoJ048EwONM1ZGk%3D&reserved=0)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7693)

### CODE REVIEW

**Comment by garath** [comment]
Just a note, it's possible to run the [generate-and-check portion](https://github.com/dotnet/arcade/blob/main/eng/common/generate-locproject.ps1) locally, without a PR, to double-check the change.

**Review by garath — APPROVED** [review]

**Comment by dreddy-work** [comment]
> Just a note, it's possible to run the [generate-and-check portion](https://github.com/dotnet/arcade/blob/main/eng/common/generate-locproject.ps1) locally, without a PR, to double-check the change.

@garath , what command you run? i tried following but it fails.

 c:\Repos\winforms\eng\common\generate-locproject.ps1 -SourcesDirectory c:\Repos\winforms -LanguageSet "VS_Main_Languages" -CreateNeutralXlfs -UseCheckedInLocProjectJson

C:\Repos\winforms\eng\common\generate-locproject.ps1 : The property '1' cannot be found on this object. Verify that
the property exists.

**Comment by garath** [comment]
> what command you run? i tried following but it fails.

I expected what you did to be right. I'll investigate further...

**Comment by garath** [comment]
> I expected what you did to be right. I'll investigate further...

Well, unhelpful, but it's working fine on my machine (though I get an error at the comparison). Maybe make sure there are no dirty files in the repo directory and that Arcade is up to date with the last dependency flow.

**Pull request merged**
