### PR TITLE
Fix Setting DataGridViewImageCell.ImageLayout to NotSet

### LINKED ISSUE #11927: Cannot get correct value 'NotSet' when setting the ImageLayout value of DataGridViewImage cell with 'NotSet' value
### .NET version

9.0.100-rc.2.24419.18 + private dlls built from winforms repo main branch

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works in .Net previous versions and 9.0.100-rc.2.24419.18 SDK build

### Issue description

When setting the ImageLayout value of DataGridViewImageLink cell with **NotSet** value, cannot get **NotSet** value, but **Normal** value. It causes our one automation case failed recently. 

Other ImageLayout values: Normal/Stretch/Zoom work well.

9.0.100-rc.2.24419.18 + private dlls built from winforms repo main branch:
image

9.0.100-rc.2.24419.18: 
image

### Steps to reproduce

Test app:
[WinFormsApp22.zip](https://github.com/user-attachments/files/16668567/WinFormsApp22.zip)

### PR DESCRIPTION
**Pull request by lonitra**
Fixes #11927

This regressed due to some property store work in .NET 10. `PropertyStore.AddOrRemoveValue` will remove the value from the property store if the value is the default value. 
When setting `DataGridViewImageCell.ImageLayout` we cannot remove the value in the property store even if the value being set is the default because our getter for ImageLayout had always returned `DataGridViewImageCellLayout.Normal` if the property had not been set, not the default value, which is `DataGridViewImageCellLayout.NotSet`. This means with the current code if the user sets the ImageLayout to `DataGridViewImageCellLayout.NotSet`, when retrieving ImageLayout we will receive `DataGridViewImageCellLayout.Normal` instead, which is not expected. 
Updated the code to never remove the property store value for ImageLayout. It will only update the value.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/winforms/pull/11961)

### CODE REVIEW

**Comment by lonitra** [comment]
fyi @elachlan this is a scenario we should be careful about as we continue to make changes to property store. When our default values and what we are returning "by default" do not match.

**Comment by Tanya-Solyanik** [comment]
>When what we have as our default value in the default value attribute and what we are returning "by default" do not match.

This sounds line our DefaultValue attribute is set incorrectly... As you experimented with this scenario, did you see any reason for that?

**Review by Tanya-Solyanik — APPROVED** [review]
Looks good

**Comment by lonitra** [comment]
> As you experimented with this scenario, did you see any reason for that?

No, unfortunately not. I agree that this is strange and seems incorrect. We should either have our default attribute as `DataGridViewImageCellLayout.Normal` or our getter should return `DataGridViewImageCellLayout.NotSet` when there is no value in the property store, but the code has been this way since Framework.. 🤔

**Comment by KlausLoeffelmann** [comment]
Late comment, but may be important:

Keep in mind, changing the Default value on a property has the potential to break Designer code, especially if folks derive later from that property. We should be always very mindful about this.

**Pull request merged**
