### PR TITLE
Add drag drop UI test from Explorer

### LINKED ISSUE #7700: Consider adding a drag and drop test from File Explorer
### Issue description

We currently have a handful of drag and drop UI test cases which drag data from and to the application, but we're missing the case when the users drags data from File Explorer to the application. To support the work being done in #5163, and as a regression test for #7518, I propose we add a drag and drop UI integration test which drags data from File Explorer and drops it to the application, in order to catch any potential issues that may result from work being done in that area.

### PR DESCRIPTION
**Pull request by willibrandon**
Fixes #7700 

## Proposed changes

- Add a UI integration test which drags and drops an RTF file from Explorer to the application.

## Customer Impact

- Supports the work being done in #5163 
- Regression test for #7518 

## Regression? 

- No

## Risk

- A possible risk of test instability due to my limited knowledge and experience with [`IUIAutomation`](https://docs.microsoft.com/en-us/windows/win32/api/uiautomationclient/nn-uiautomationclient-iuiautomation) and [`IUIAutomationElement`](https://docs.microsoft.com/en-us/windows/win32/api/uiautomationclient/nn-uiautomationclient-iuiautomationelement).

## Screenshots 

https://user-images.githubusercontent.com/5017479/187829782-db205dd5-a809-41e9-8854-f5a0fdf293db.mp4

## Test methodology 

- Ran unit and integration tests.
 
## Test environment(s) 

- 7.0.0-preview.1.22076.8

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7711)

### CODE REVIEW

**Review by RussKie — COMMENTED** [review]
👍  Just a quick cursory look. I'll set aside some time to pull it down and test locally.

I think we could abstract the interactions with Explorer in a helper class to make the maintenance a little easier. I don't have any immediate suggestions though.

**Comment by willibrandon** [comment]
Naturally the CI demo flops. I swear it works locally, and I have video!

I'll try to learn what I'm missing here, but I also don't want to spam the CI doing so. What I really wish is if I could record the test run and replay the video.

**Comment by dreddy-work** [comment]
@willibrandon , integration test fails with following.


Error message
Actual form.RichTextBoxDropTarget.Text:  \r\nExpected: False\r\nActual:   True


Stack trace
   at System.Windows.Forms.UITests.DragDropTests.<DragDrop_RTF_FromExplorer_ToRichTextBox_ReturnsExpected_Async>b__8_0(DragImageDropDescriptionForm dragDropForm) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs:line 161
   at System.Windows.Forms.UITests.ControlTestBase.<>c__DisplayClass29_0`1.<<RunFormWithoutControlAsync>b__0>d.MoveNext() in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 277
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.JoinableTask.JoinAsync(CancellationToken cancellationToken)
   at System.Windows.Forms.UITests.ControlTestBase.RunFormWithoutControlAsync[TForm](Func`1 createForm, Func`2 testDriverAsync) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 295
   at System.Windows.Forms.UITests.DragDropTests.RunTestAsync(Func`2 runTest) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs:line 407
   at System.Windows.Forms.UITests.DragDropTests.DragDrop_RTF_FromExplorer_ToRichTextBox_ReturnsExpected_Async() in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs:line 66
--- End of stack trace from previous location ---

**Comment by RussKie** [comment]
I confirm that running test locally passes:
```
PS D:\Development\dotnet-winforms> .\build.cmd -c Release -integrationtest
....
  Running tests: D:\Development\dotnet-winforms\artifacts\bin\System.Windows.Forms.IntegrationTests\Release\net7.0\System.Windows.Forms.IntegrationTests.dll [net7.0|x64]
  Running tests: D:\Development\dotnet-winforms\artifacts\bin\Microsoft.VisualBasic.IntegrationTests\Release\net7.0\Microsoft.VisualBasic.IntegrationTests.dll [net7.0|x64]
  Tests succeeded: D:\Development\dotnet-winforms\artifacts\bin\System.Windows.Forms.IntegrationTests\Release\net7.0\System.Windows.Forms.IntegrationTests.dll [net7.0|x64]
  Running tests: D:\Development\dotnet-winforms\artifacts\bin\System.Windows.Forms.UI.IntegrationTests\Release\net7.0\System.Windows.Forms.UI.IntegrationTests.dll [net7.0|x64]
  Tests succeeded: D:\Development\dotnet-winforms\artifacts\bin\Microsoft.VisualBasic.IntegrationTests\Release\net7.0\Microsoft.VisualBasic.IntegrationTests.dll [net7.0|x64]
  Tests succeeded: D:\Development\dotnet-winforms\artifacts\bin\System.Windows.Forms.UI.IntegrationTests\Release\net7.0\System.Windows.Forms.UI.IntegrationTests.dll [net7.0|x64]

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:01:43.61

```

**Comment by RussKie** [comment]
Here's the log from a build agent:
```
    System.Windows.Forms.UITests.DragDropTests.DragDrop_RTF_FromExplorer_ToRichTextBox_ReturnsExpected_Async [FAIL]
      Actual form.RichTextBoxDropTarget.Text:  
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs(161,0): at System.Windows.Forms.UITests.DragDropTests.<DragDrop_RTF_FromExplorer_ToRichTextBox_ReturnsExpected_Async>b__8_0(DragImageDropDescriptionForm dragDropForm)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs(277,0): at System.Windows.Forms.UITests.ControlTestBase.<>c__DisplayClass29_0`1.<<RunFormWithoutControlAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
           at Microsoft.VisualStudio.Threading.JoinableTask.JoinAsync(CancellationToken cancellationToken)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs(295,0): at System.Windows.Forms.UITests.ControlTestBase.RunFormWithoutControlAsync[TForm](Func`1 createForm, Func`2 testDriverAsync)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs(407,0): at System.Windows.Forms.UITests.DragDropTests.RunTestAsync(Func`2 runTest)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs(66,0): at System.Windows.Forms.UITests.DragDropTests.DragDrop_RTF_FromExplorer_ToRichTextBox_ReturnsExpected_Async()
        --- End of stack trace from previous location ---
      Output:
        Waiting for Explorer to open, wait 1
        Waiting for Explorer to open, wait 2
        Waiting for Explorer to open, wait 3
        Waiting for Explorer to open, wait 4
        Waiting for Explorer to open, wait 5
        Waiting for Explorer to open, wait 6
        Waiting for Explorer to open, wait 7
        Waiting for Explorer to open, wait 8
        Waiting for Explorer to open, wait 9
        Waiting for Explorer to open, wait 10
        Waiting for Explorer to open, wait 11
        Waiting for Explorer to open, wait 12
        Waiting for Explorer to open, wait 13
        Waiting for Explorer to open, wait 14
        Waiting for Explorer to open, wait 15
        Waiting for Explorer to open, wait 16
        Waiting for Explorer to open, wait 17
        Waiting for Explorer to open, wait 18
        gotClickable: True
        clickable: {X=770,Y=132}
        virtualPointStart: {X=49312,Y=11306}
        virtualPointEnd: {X=13792,Y=11562}
        Drag enter on target.
        Drag drop on target.
```

**Comment by RussKie** [comment]
It's kind of interesting... but it looks like the data gets mangled. Here're the enhanced outputs from a build agent:
```
    System.Windows.Forms.UITests.DragDropTests.DragDrop_RTF_FromExplorer_ToRichTextBox_ReturnsExpected_Async [FAIL]
      Actual form.RichTextBoxDropTarget.Text:  
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs(167,0): at System.Windows.Forms.UITests.DragDropTests.<DragDrop_RTF_FromExplorer_ToRichTextBox_ReturnsExpected_Async>b__8_0(DragImageDropDescriptionForm dragDropForm)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs(277,0): at System.Windows.Forms.UITests.ControlTestBase.<>c__DisplayClass29_0`1.<<RunFormWithoutControlAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
           at Microsoft.VisualStudio.Threading.JoinableTask.JoinAsync(CancellationToken cancellationToken)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs(295,0): at System.Windows.Forms.UITests.ControlTestBase.RunFormWithoutControlAsync[TForm](Func`1 createForm, Func`2 testDriverAsync)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs(414,0): at System.Windows.Forms.UITests.DragDropTests.RunTestAsync(Func`2 runTest)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs(66,0): at System.Windows.Forms.UITests.DragDropTests.DragDrop_RTF_FromExplorer_ToRichTextBox_ReturnsExpected_Async()
        --- End of stack trace from previous location ---
      Output:
        Waiting for Explorer to open, wait 1
        Waiting for Explorer to open, wait 2
        Waiting for Explorer to open, wait 3
        Waiting for Explorer to open, wait 4
        Waiting for Explorer to open, wait 5
        Waiting for Explorer to open, wait 6
        Waiting for Explorer to open, wait 7
        Waiting for Explorer to open, wait 8
        Waiting for Explorer to open, wait 9
        Waiting for Explorer to open, wait 10
        Waiting for Explorer to open, wait 11
        Waiting for Explorer to open, wait 12
        Waiting for Explorer to open, wait 13
        Waiting for Explorer to open, wait 14
        Waiting for Explorer to open, wait 15
        Waiting for Explorer to open, wait 16
        gotClickable: True
        clickable: {X=770,Y=132}
        virtualPointStart: {X=49312,Y=11306}
        virtualPointEnd: {X=13792,Y=11562}
        Drag enter on target.
        Drag drop on target.
        dragAcceptRtfContent: {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033\deflangfe1033{\fonttbl{\f0\fmodern\fprq1\fcharset0 Cascadia Mono;}}
        {\*\generator Riched20 10.0.17763}{\*\mmathPr\mnaryLim0\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        \pard\nowidctlpar\b\f0\fs28\lang9 DragAcceptFiles function (shellapi.h)\b0\fs22\par
        \par
        \fs20 Registers whether a window accepts dropped files.\par
        \fs22\par
        \b\fs24 Syntax\fs22\par
        \b0\par
        \fs20 void DragAcceptFiles(\par
          HWND hWnd,\par
          BOOL fAccept\par
        );\par
        \fs22\par
        \b\fs24 Parameters\fs22\par
        \b0\par
        \ul\fs20 hWnd\ulnone\par
        Type: HWND\par
        \par
        The identifier of the window that is registering whether it will accept dropped files.\par
        \par
        \ul fAccept\ulnone\par
        Type: BOOL\par
        \par
        A value that indicates if the window identified by the hWnd parameter accepts dropped files. This value is TRUE to accept dropped files or FALSE to discontinue accepting dropped files.\par
        \b\fs22\par
        \fs24 Return value\b0\fs22\par
        \par
        \fs20 None\par
        \fs22\par
        \b\fs24 Remarks\fs22\par
        \b0\par
        \fs20 An application that calls DragAcceptFiles with the fAccept parameter set to TRUE has identified itself as able to process the WM_DROPFILES message from File Manager.\par
        }
        
        RichTextBoxDropTarget.Rtf: {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil Segoe UI;}}
        {\*\generator Riched20 10.0.17763}\viewkind4\uc1 
        \pard\f0\fs18{\pict{\*\picprop{\sp{\sn wzDescription}{\sv 3dwarro.cur}}{\sp{\sn posv}{\sv 1}}
        }\pngblip\picw847\pich847\picwgoal480\pichgoal480 
        89504e470d0a1a0a0000000d4948445200000020000000200806000000737a7af4000000017352
        474200aece1ce90000000467414d410000b18f0bfc6105000000097048597300000ec300000ec3
        01c76fa864000000ab494441545847ed94410ec4200845692fa647d39be9c95abe09c64e337631
        1566c14bc474c5e39748cc8162c59e52c26d26b1a3945270994834016025d1044208edc342a227
        20684b74014901684adc1210b4242e02630a4043e26b02c272097e880e819ba1d1ecbc4e4fa0d6
        4a3146620f991a6c1fe7759a803467b69c73db05d52594e62816dca694bd1876621948c06cf229
        5a294cdf012ce76a9ee21f27ffcf5fe5388ee338bf4174026bbd5fb776440f2b0000000049454e
        44ae426082
        }\par
        }
        
        dragAcceptRtfTextContent: DragAcceptFiles function (shellapi.h)

Registers whether a window accepts dropped files.

Syntax

void DragAcceptFiles(
  HWND hWnd,
  BOOL fAccept
);

Parameters

hWnd
Type: HWND

The identifier of the window that is registering whether it will accept dropped files.

fAccept
Type: BOOL

A value that indicates if the window identified by the hWnd parameter accepts dropped files. This value is TRUE to accept dropped files or FALSE to discontinue accepting dropped files.

Return value

None

Remarks

An application that calls DragAcceptFiles with the fAccept parameter set to TRUE has identified itself as able to process the WM_DROPFILES message from File Manager.
        RichTextBoxDropTarget.Text:  

```

**Comment by RussKie** [comment]
@JeremyKuhne @AaronRobinsonMSFT any ideas why this corruption may be happening? When run locally all is good...

Here's the local output:
```
Standard Output: 
Waiting for Explorer to open, wait 1
Waiting for Explorer to open, wait 2
Waiting for Explorer to open, wait 3
Waiting for Explorer to open, wait 4
Waiting for Explorer to open, wait 5
Waiting for Explorer to open, wait 6
Waiting for Explorer to open, wait 7
gotClickable: True
clickable: {X=1063,Y=245}
virtualPointStart: {X=18149,Y=7448}
virtualPointEnd: {X=3677,Y=4111}
Drag enter on target.
Drag drop on target.
dragAcceptRtfContent: {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033\deflangfe1033{\fonttbl{\f0\fmodern\fprq1\fcharset0 Cascadia Mono;}}
{\*\generator Riched20 10.0.22000}{\*\mmathPr\mnaryLim0\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
\pard\nowidctlpar\b\f0\fs28\lang9 DragAcceptFiles function (shellapi.h)\b0\fs22\par
\par
\fs20 Registers whether a window accepts dropped files.\par
\fs22\par
\b\fs24 Syntax\fs22\par
\b0\par
\fs20 void DragAcceptFiles(\par
  HWND hWnd,\par
  BOOL fAccept\par
);\par
\fs22\par
\b\fs24 Parameters\fs22\par
\b0\par
\ul\fs20 hWnd\ulnone\par
Type: HWND\par
\par
The identifier of the window that is registering whether it will accept dropped files.\par
\par
\ul fAccept\ulnone\par
Type: BOOL\par
\par
A value that indicates if the window identified by the hWnd parameter accepts dropped files. This value is TRUE to accept dropped files or FALSE to discontinue accepting dropped files.\par
\b\fs22\par
\fs24 Return value\b0\fs22\par
\par
\fs20 None\par
\fs22\par
\b\fs24 Remarks\fs22\par
\b0\par
\fs20 An application that calls DragAcceptFiles with the fAccept parameter set to TRUE has identified itself as able to process the WM_DROPFILES message from File Manager.\par
}

RichTextBoxDropTarget.Rtf: {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033\deflangfe1033{\fonttbl{\f0\fmodern\fprq1\fcharset0 Cascadia Mono;}}
{\*\generator Riched20 10.0.22000}{\*\mmathPr\mnaryLim0\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
\pard\nowidctlpar\b\f0\fs28\lang9 DragAcceptFiles function (shellapi.h)\b0\fs22\par
\par
\fs20 Registers whether a window accepts dropped files.\par
\fs22\par
\b\fs24 Syntax\fs22\par
\b0\par
\fs20 void DragAcceptFiles(\par
  HWND hWnd,\par
  BOOL fAccept\par
);\par
\fs22\par
\b\fs24 Parameters\fs22\par
\b0\par
\ul\fs20 hWnd\ulnone\par
Type: HWND\par
\par
The identifier of the window that is registering whether it will accept dropped files.\par
\par
\ul fAccept\ulnone\par
Type: BOOL\par
\par
A value that indicates if the window identified by the hWnd parameter accepts dropped files. This value is TRUE to accept dropped files or FALSE to discontinue accepting dropped files.\par
\b\fs22\par
\fs24 Return value\b0\fs22\par
\par
\fs20 None\par
\fs22\par
\b\fs24 Remarks\fs22\par
\b0\par
\fs20 An application that calls DragAcceptFiles with the fAccept parameter set to TRUE has identified itself as able to process the WM_DROPFILES message from File Manager.\par
}

dragAcceptRtfTextContent: DragAcceptFiles function (shellapi.h)

Registers whether a window accepts dropped files.

Syntax

void DragAcceptFiles(
  HWND hWnd,
  BOOL fAccept
);

Parameters

hWnd
Type: HWND

The identifier of the window that is registering whether it will accept dropped files.

fAccept
Type: BOOL

A value that indicates if the window identified by the hWnd parameter accepts dropped files. This value is TRUE to accept dropped files or FALSE to discontinue accepting dropped files.

Return value

None

Remarks

An application that calls DragAcceptFiles with the fAccept parameter set to TRUE has identified itself as able to process the WM_DROPFILES message from File Manager.
RichTextBoxDropTarget.Text: DragAcceptFiles function (shellapi.h)

Registers whether a window accepts dropped files.

Syntax

void DragAcceptFiles(
  HWND hWnd,
  BOOL fAccept
);

Parameters

hWnd
Type: HWND

The identifier of the window that is registering whether it will accept dropped files.

fAccept
Type: BOOL

A value that indicates if the window identified by the hWnd parameter accepts dropped files. This value is TRUE to accept dropped files or FALSE to discontinue accepting dropped files.

Return value

None

Remarks

An application that calls DragAcceptFiles with the fAccept parameter set to TRUE has identified itself as able to process the WM_DROPFILES message from File Manager.
```

**Comment by RussKie** [comment]
It looks like on a build agent instead of an RTF document the richtextbox receives/acceps the cursor🤯 

image

Here's the RTF spec: http://www.biblioscape.com/rtf15_spec.htm#Heading49

**Comment by willibrandon** [comment]
@RussKie - Thank you very much for looking into this. I was having a hard time making sense of it.

I wonder if this is limited to the RichTextBox only? Should I check if dropping a .txt file to a textbox has a better result?

**Comment by RussKie** [comment]
I don't know :) I'm quite bewildered just much as you are....

**Comment by RussKie** [comment]
I'm still scratching my head, but I _think_ on the build agent the test is not picking DragAccept.rtf but is picking 3dwarro.cur - you can see it in the highlighted portion of the screenshot avove. 
I'm speculating here, but the location of the file can be different due to OS version or OS configuration...

**Comment by willibrandon** [comment]
Okay, if that is the case, the starting point isn't even close. That's 3 files away!?

**Comment by RussKie** [comment]
Could be different sort order perhaps?

**Comment by willibrandon** [comment]
After launching explorer, lets see what the focused element name is according to ui automation.

**Comment by willibrandon** [comment]
There's the difference.

On the the build agent.

`Focused element name: 3dwarro`

On my local machine.

`Focused element name: DragAccept.rtf`

**Comment by willibrandon** [comment]
Lets see what the rtf file path looks like. That might be messing up the `explorer.exe /select` command line option.

**Comment by willibrandon** [comment]
`dragAcceptRtfPath: D:\a\_work\1\s\artifacts\bin\System.Windows.Forms.UI.IntegrationTests\Debug\net7.0\Resources\DragAccept.rtf`

**Comment by willibrandon** [comment]
If we can't rely on `explorer.exe /select`, I'll see if I can locate the ui automation element in another way.

**Comment by RussKie** [comment]
Maybe you could create a new folder that contains only a single file?

**Comment by willibrandon** [comment]
> Maybe you could create a new folder that contains only a single file?

That seems good enough to do the trick.

**Comment by RussKie** [comment]
I should have been more clear with my suggestion, sorry. What I had in mind was we create a temporary folder for the test duration and copy the necessary file in it. This way the logic remains with the test (with comments as required), and we don't need to know/remember that a specific file can't be moved and the reason it's placed on its own in a specific folder. Hope this makes sense.

**Comment by willibrandon** [comment]
> I should have been more clear with my suggestion, sorry. What I had in mind was we create a temporary folder for the test duration and copy the necessary file in it. This way the logic remains with the test (with comments as required), and we don't need to know/remember that a specific file can't be moved and the reason it's placed on its own in a specific folder. Hope this makes sense.

That makes sense.

**Comment by willibrandon** [comment]
I'm happy with this approach. If it turns out to be unreliable for some reason then we can explore other ways to find ui elements.

[How to Find UI Elements](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-howto-find-ui-elements)

**Comment by willibrandon** [comment]
I'm not sure if that is a transient build failure, or something I need to fix?

**Comment by willibrandon** [comment]
Awesome!

**Review by RussKie — APPROVED** [review]
This is some exquisite piece of engineering! 🚀

**Comment by willibrandon** [comment]
Such a good learning opportunity and crazy fun. Thank you everyone for the help.

**Pull request merged**
