### PR TITLE
Consolidate HandleCollector code

### PR DESCRIPTION
**Pull request by hughbe**
- Move duplicate code to `Common/src/Interop/Interop.HandleCollector` (matching .NET Core interop guidelines)
- Consolidate `CommonHandles`
- Update namespaces as a result
- Preparation for consolidating code between `SafeNativeMethods`, `UnsafeNativeMethods`, `IntSafeNativeMethods`, `IntUnsafeNativeMethods`, `NativeMethods` etc etc

### CODE REVIEW

**Comment by zsd4yr** [comment]
Why was DebugHandleTracker.cs completely deleted?

**Comment by zsd4yr** [comment]
> * Move duplicate code to `Common/src/Interop/Interop.HandleCollector` (matching .NET Core interop guidelines)

What duplicate code?

Please link to guidelines

**Comment by hughbe** [comment]
DebugHandleTracker wasn’t being used and was dead code, so I removed it.

In terms of duplicate code, there are two exact (excluding formatting changes) versions of HandleCollector.cs so I moved them to a common folder.

According to the Interop guidelines of .net core (https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/interop-guidelines.md) this stuff belongs in a folder called interop in a class called Interop

That’s part of .net core moving away from NativeMethods.cs stuff which is gross

**Comment by zsd4yr** [comment]
> According to the Interop guidelines of .net core (https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/interop-guidelines.md) this stuff belongs in a folder called interop in a class called Interop

@JeremyKuhne please advise

**Comment by JeremyKuhne** [comment]
> According to the Interop guidelines of .net core (https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/interop-guidelines.md) this stuff belongs in a folder called interop in a class called Interop

Yes, this is the right way to do this. We can, in theory, start getting WinForms consuming the shared interop code in CoreCLR/CoreFX.

**Comment by zsd4yr** [comment]
> We can, in theory, start getting WinForms consuming the shared interop code in CoreCLR/CoreFX.

I would love to start that process so that we can get all the benefits from the work being done there 😄

**Comment by zsd4yr** [comment]
@hughbe lemme know when this is ready to be looked at again -- I see you force pushed awhile ago.

**Comment by JeremyKuhne** [comment]
> I would love to start that process so that we can get all the benefits from the work being done there 😄

Sync up with @Anipik about this.

**Comment by Anipik** [comment]
> We can, in theory, start getting WinForms consuming the shared interop code in CoreCLR/CoreFX.

we can easily setup a one way Mirror i.e. All the commits in the Interop shared folder of the CoreClr/CoreFx will automatically ported in the winforms repo. let me know if you have any specific requirements and if you want me to set this up 

cc @danmosemsft

**Comment by zsd4yr** [comment]
> we can easily setup a one way Mirror i.e. All the commits in the Interop shared folder of the CoreClr/CoreFx will automatically ported in the winforms repo. let me know if you have any specific requirements and if you want me to set this up
> 
> cc @danmosemsft

@JeremyKuhne @Anipik if there are public hooks in the CoreFX / CoreCLR APIs, then we shouldn't need to mirror the source. Perhaps I misunderstand?

**Comment by Anipik** [comment]
> @JeremyKuhne @Anipik if there are public hooks in the CoreFX / CoreCLR APIs, 

Hooks are setup in corefx and coreclr but i am not sure if they are exposed publicly. Currently we go thr

> then we shouldn't need to mirror the source. Perhaps I misunderstand?

do you want write your own version or just copy the files ?

**Comment by danmosemsft** [comment]
Thanks @hughbe, one small suggestion, it seems there are several logical steps to this change, if you could keep separate commits where possible that would make it possible to review more quickly.

**Comment by hughbe** [comment]
Rebased and separated into multiple commits

**Comment by hughbe** [comment]
@zsd4yr good to merge? I've learnt a lot from these PRs (in terms of splitting up PRs, presenting commits etc) but do hate fixing merge conflicts ;)

**Comment by zsd4yr** [comment]
yes!

**Pull request merged**
