### PR TITLE
comment out including resource dlls in pkg

### PR DESCRIPTION
**Pull request by zsd4yr**
...until we decide to use them in the WindowsDesktop package

### CODE REVIEW

**Comment by raffaeler** [comment]
@zsd4yr while rebasing my fork, I got this file too and now I can't compile anymore:
```
1>------ Build started: Project: Microsoft.Private.Winforms, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\3.0.100-preview-009812\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(125,5): error NETSDK1007: Cannot find project info for 'H:\dev.forked\winforms\src\System.Windows.Forms.Design.Editors\ref\System.Windows.Forms.Design.Editors.Ref.csproj'. This can indicate a missing project reference.
1>Done building project "Microsoft.Private.Winforms.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 8 up-to-date, 0 skipped ==========
```

Suggestions?

**Comment by AdamYoblick** [comment]
This happens to me occasionally when building through visual studio 2019. Does this repro in 2017? Can you also try build.cmd from the command line?


________________________________

**Comment by AdamYoblick** [comment]
I think it’s a difference in how VS builds from the command line. I usually use the console to build so I don’t hit this, but I’ve seen it in VS before.

Please use the console for now and I will reach out to the VS team on Monday to try and troubleshoot this. Sorry for the inconvenience.


________________________________

**Comment by AdamYoblick** [comment]
@raffaeler I got a fix from the VS team and it worked for me locally when building from both VS2017 and VS2019. It's in a PR now. See https://github.com/dotnet/winforms/pull/223

**Comment by raffaeler** [comment]
Great news, thanks @AdamYoblick !

**Comment by AdamYoblick** [comment]
This has been merged into master. Please merge from master into your branch and do a clean build and let me know if the problem is resolved. Thanks!

**Pull request merged**
