### PR TITLE
Enable and fix CA2229 warning

### PR DESCRIPTION
**Pull request by gpetrou**
## Proposed changes

- Enable and fix CA2229 warning.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3697)

### CODE REVIEW

**Comment by RussKie** [comment]
LGTM

@dotnet/dotnet-winforms would this cause any issues for the designer?

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik , @KlausLoeffelmann - can you take a quick look?

**Comment by KlausLoeffelmann** [comment]
I don't see any particular issue with the designer.
But what is the context here? I am always cautious with a change from Info to Warning for projects which treat warning as errors. Are we gonna break things with this?

**Comment by KlausLoeffelmann** [comment]
For the scope change of `TableLayoutSettings`, I think @dreddy-work is the right person to ask?

**Comment by dreddy-work** [comment]
As we are enabling it just for this repo, i do not see any concerns. And it seems this was the only method here. We had 'Internalvisibleto' attribute but i do not think we were using this method in that context.

**Pull request merged**
