### PR TITLE
fix: Restore missing TF for `System.Windows.Forms.HighDpiMode`

### LINKED ISSUE #2925: System.MissingMethodException at System.Windows.Forms.Application.SetHighDpiMode(System.Windows.Forms.HighDpiMode) in GreenShot unit tests
* .NET Core Version: 

.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.1.20125.9
 Commit:    12e88ed2e5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.1.20125.9\

Host (useful for support):
  Version: 5.0.0-preview.1.20120.5
  Commit:  3c523a6a7a

.NET Core SDKs installed:
  5.0.100-preview.1.20125.9 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.1.20124.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.1.20120.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.1.20122.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

Repro steps:

On the repo machine (could be found at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1075435)

1) On CMD, go to C:\Repro\GreenshotTest09
2)run command "dotnet vstest Greenshot.Tests.dll"

Expected Result:

Tests should pass

Actual Result:

Total tests: 21
     Passed: 16
     Failed: 5

Findings :

Tests return this exception :

   System.MissingMethodException : Method not found: 'Boolean System.Windows.Forms.Application.SetHighDpiMode(System.Windows.Forms.HighDpiMode)'.

When we create/build winforms app with .net core sdk 3.1 and run it against .net core 5.0, we get this issue. It is fine when we run against 3.1.

This issue does not repro if we build the same with code .net core 5.0 SDK.

This line in program.cs causes this issue : 

Application.SetHighDpiMode(HighDpiMode.SystemAware);

**Expected behavior:**
All unites passed.

App Source on GitHub link: https://github.com/greenshot/greenshot

**Minimal repro:**
1. create winforms app ===> dotnet new winforms on machine has .NET Core 3.1 SDK installed.
2. dotnet build
3. Run the app only have .NET 5 installed.

@dotnet-actwx-bot  FYI

### PR DESCRIPTION
**Pull request by RussKie**
Resolves #2925

`System.Windows.Forms.HighDpiMode` was accidentally placed under `Internal` namespace, which caused a missing type-forward decoration.
This resulted in users receiving the following error when attempting to roll forward from .NET Core 3.x to .NET 5:

```
System.MissingMethodException : Method not found: 'Boolean System.Windows.Forms.Application.SetHighDpiMode(System.Windows.Forms.HighDpiMode)'.
```

## Proposed changes

- Move the type into the correct location and add the missing `TypeForward` decoration.

## Customer Impact

- User can now roll forward from .NET Core 3.x and use `Boolean System.Windows.Forms.Application.SetHighDpiMode(System.Windows.Forms.HighDpiMode)`

## Regression? 

- Yes

## Risk

- Minimal

## Test methodology
* [Use the repro app](https://github.com/RussKie/Test-TypeForwards/commit/c5f76dca248dee7fd69d95fc9b5af0f76c32578e) or generate a new Windows Forms app targeting .NET Core 3.0 (or 3.1) and set it to rollforward:
  ```json
  {
    "sdk": {
      "rollForward": "major"
    }
  }
  ```
* Ensure no .NET Core 3.x runtime is installed. Best to run a VM with only .NET5 Preview1 installed
* Run the app, observe the failure:
  image
* Build the current commit with `pack` option:
  ```powershell
  PS> .\build.ps1 -pack
  ```
* Copy and replace `System.Windows.Forms.dll` and `System.Windows.Forms.Primitives.dll`
	- from .\artifacts\packages\Debug\NonShipping\Microsoft.Private.Winforms.5.0.0-dev.nupkg\lib\netcoreapp5.0 --> C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.0-preview.2.20119.5
	- from .\artifacts\packages\Debug\NonShipping\Microsoft.Private.Winforms.5.0.0-dev.nupkg\ref\netcoreapp5.0 --> C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\5.0.0-preview.2.20119.5\ref\netcoreapp5.0
* Re-run the app, observe the app start
  image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/2932)

### CODE REVIEW

**Comment by Shyam-Gupta** [comment]
@RussKie I seems at present `HighDpiMode` is in `System.Windows.Forms` namespace and is a public type: https://github.com/dotnet/winforms/blob/31bca2bbe81ee8b368cbe3fdb19bbed2ceca5835/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/HighDpiMode.cs#L5

Please let me know if I am missing something. I also noticed that this file is under `Internals` folder. Is that somehow forcing it to be an `Internal` type ? Had it been an internal type then why does it not creating a problem for projects targeting .NET Core 5.0 ?

Are there other such types which need to be made public ?

**Comment by RussKie** [comment]
> Please let me know if I am missing something. I also noticed that this file is under `Internals` folder. Is that somehow forcing it to be an `Internal` type ? If it is an internal type then why does it not creating a problem for projects targeting .NET Core 5.0 ?

No, it is a simple convention with no enforcement - all `public` types to be places as per their namespace, `internal`s to into `Internal` folder.
This makes it easier to see which types must be type-forwarded.

> Are there other such types which need to be made public ?

I have double-checked all others, all good.
I have also thought of some sort of a test that could check the correctness, but the TFs are in System.Windows.Forms, and the types in System.Windows.Forms.Primitives... Without some horrible hard linking I couldn't come up with a test... 
If you have any suggestions please let me know.

**Comment by Shyam-Gupta** [comment]
Would it be better to move `HighDpiMode` type back to S.W.F ?

**Comment by Tanya-Solyanik** [comment]
Is it possible to dump all public type names from System.Windows.Forms v3.1, then add a test that dumps out the same from the current version of this assembly and compare the lists? Then get 
 all TypeForwardAttributes from  the current assembly, do attribute.Destination.FullName and confirm that list of full names is the same as the diff between v3.1 and 5.0? What am I missing?
This test would be useful regardless of how this bug is fixed, with type forwarding or by returning the  enum to system.windows.forms

**Comment by RussKie** [comment]
> Would it be better to move `HighDpiMode` type back to S.W.F ?

We can't do that. It is used by types residing in System.Windows.Forms.Primitives.
All types in System.Windows.Forms.Primitives are there out of necessity.


> Is it possible to dump all public type names from System.Windows.Forms v3.1, then add a test that dumps out the same from the current version of this assembly and compare the lists? 

I think what you're proposing falls under the [API Compat story](https://github.com/dotnet/winforms/pull/2112) (which we've been neglecting).
I'm not sure comparing like-for-like will work without additional efforts, the API surface is different between the two, and may further erode going into the future.

We can work on this separately, once we get over the hump. There is a significant value in automating the verification.

**Comment by Shyam-Gupta** [comment]
> We can't do that. It is used by types residing in System.Windows.Forms.Primitives.
> All types in System.Windows.Forms.Primitives are there out of necessity.

Ok. TF seems fine then.

**Comment by RussKie** [comment]
I run tests and verified the fix. Added test methodology section to the description.

**Pull request merged**
