### PR TITLE
Rev build SDK version

### LINKED ISSUE #531: WinForms is testing against a very old shared framework
Observe https://github.com/dotnet/winforms/blob/7276127fafb6283beaa188a411ad2a43371641d3/global.json#L3

This hasn't been changed in 2 months.  This is determining what version of .NETCore APP that you build against and run your tests against, since you aren't setting RuntimeFrameworkVersion.

You should either set this to update regularly (eg: ingest the CLI as a tool dependency) or use RuntimeFrameworkVersion instead and do something like ASP.NET does to make that easier on folks using VS.

### PR DESCRIPTION
**Pull request by zsd4yr**
fixes #531

### CODE REVIEW

**Comment by ericstj** [comment]
It looks to me like the exclusion of System.Drawing.dll has been broken.  I suspect this is due to the SDK changing how it brings in NETCoreApp references.  Looking closer.

**Comment by ericstj** [comment]
Here's what was trying to remove System.Drawing before: https://github.com/dotnet/winforms/blob/c228cecdbfff920d3917f43b1571a68d74455d1b/eng/FacadeAssemblies.props#L30-L31

**Comment by ericstj** [comment]
Yep, the SDK resolves this differently now.  Before it was a package reference and come in with other NuGetPackages in ResolvePackageDependenciesForBuild.  Now its a ref pack and is resolved later during ResolveTargetingPacks.  I'll change the sequencing so that is should stay after both of these.

**Comment by ericstj** [comment]
Looks like I don't have push permissions, I've pushed to a fork, you can cherry-pick: https://github.com/ericstj/winforms/commit/e78b6ddc5f15884ee22a477e62717a7a01ae45cf

**Comment by zsd4yr** [comment]
Thanks Eric, that seemed to fix the issue 😄 perhaps offline we can sync about what exactly the change here is as I'm a little confused.

**Comment by ericstj** [comment]
Gist of the change is that we don't want to pass corefx's System.Drawing into GenFacades as it will get confused since it's trying to produce a new System.Drawing.  CoreFx's System.Drawing is part of .NETCoreApp shared framework, so we try to remove it in a target after the SDK adds it.  The SDK changed how they added it (it went from being a nuget package referenced by the project to a special ref-pack package added on the side) and that meant that the target we were running after didn't yet have the reference added.  By moving the target later, to right before the references were read, we were able to successfully remove it.  @dreddy-work should be able to fill in more here.

**Comment by zsd4yr** [comment]
> The SDK changed how they added it (it went from being a nuget package referenced by the project to a special ref-pack package added on the side

Is there a way we can become more resistant to these kinds of changes? I suppose the simplest resolution would be to update these core (dotnet) sdk values in dotnet/winforms/global.json more often?

**Pull request merged**
