### PR TITLE
Release/6.0

### PR DESCRIPTION
**Pull request by 74971030177**
jerryrice8881@gmail.com

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/5768)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=5768) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=5768) before we can accept your contribution.<br/><br/>:x: 74971030177 [sign now](https://cla.dotnetfoundation.org/dotnet/winforms?pullRequest=5768)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/winforms?pullRequest=5768) it.</sub>

**Comment by dreddy-work** [comment]
What is the purpose of this @74971030177 ? I do not expect to merge release branch into main. 

@mmitche  do you know anything about this PR?

**Comment by mmitche** [comment]
I don't. Looks automated but not by us.

**Comment by mmitche** [comment]
Also it's not a good idea to not use an intermediate branch to do such merges, as resolving in the UI makes changes in ways you don't expect.

**Pull request closed without merging**
