### PR TITLE
use new intellisense blob, change package composition logic

### LINKED ISSUE #3998: Update intellisense package
Intellisense package needs to be updated for winforms and wpf. Doing winforms first, then will work with the wpf team.

### PR DESCRIPTION
**Pull request by AdamYoblick**
Fixes #3998

There are two main changes going on in this PR:

1. Consume the new dotnet-api-docs_net5.0 blob, which has already been uploaded to Azure storage
2. Make our package ALWAYS use the xml from this blob instead of our locally generated xml.
   - If we build a non-facade assembly, and the blob does NOT contain xml for this assembly, this is an error

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/3999)

### CODE REVIEW

**Comment by merriemcgaw** [comment]
@AdamYoblick , @RussKie note that we will also need to port this to GA branch as well.

**Comment by AdamYoblick** [comment]
Yeah the plan is to cherry pick this to release/5.0-rc2 once this gets in. I could have gone right into rc2 but I think my local branch was based off master, so this is just less work than rebasing.

**Comment by vatsan-madhavan** [comment]
Looks good to me. You did make sure (for e.g., through a dir-diff) that the intellisense zip-bundle has all of the WinForms + WPF XML files so that both repos could use the same zip from the blob-source, right ?

**Review by vatsan-madhavan — APPROVED** [review]

**Comment by AdamYoblick** [comment]
I didn’t diff it, I just took all the intellisense files and put them in the blob. I just assumed all the winforms and wpf files would be there.

I’ll diff against the 3.0 blob to make sure files aren’t missing and report back :)

________________________________

**Review by RussKie — APPROVED** [review]
❤️ the comments!

**Comment by AdamYoblick** [comment]
Ok so I diffed the following two intellisense blobs:
  - https://netcorenativeassets.blob.core.windows.net/resource-packages/external/windows/dotnet-api-docs_netcoreapp3.0/dotnet-api-docs_netcoreapp3.0-0.0.0.2-win64-x64.zip
  - https://netcorenativeassets.blob.core.windows.net/resource-packages/external/windows/dotnet-api-docs_net5.0/dotnet-api-docs_net5.0-0.0.0.1-win64-x64.zip

There are some files missing, and some files added. @RussKie @ryalanms - please take a look at the list below and let me know if you think we need to reach out to the intellisense team. I'm not sure if the missing ones are supposed to be missing because of a move to .net50:

Missing from .net50
- System.Buffers.xml
- System.Diagnostics.Debug.xml
- System.Diagnostics.Tools.xml
- System.Security.Principal.xml
- System.Resources.ResourceManager.xml
- System.Runtime.Extensions.xml
- System.Runtime.InteropServices.WindowsRuntime.xml
- System.Security.Princopal.xml
- System.Threading.Tasks.xml
- System.Threading.Timer.xml
- `System.Windows.Forms.Design.Editors.xml`

Added to .net50
- `Microsoft.VisualBasic.Forms.xml`
- `PresentationUI.xml`
- System.Formats.Asn1.xml
- System.Net.Http.Json.xml
- `System.Windows.Forms.Primitives.xml`

**Comment by AdamYoblick** [comment]
This change needs to go in even if we discover that the intellisense blob needs to be updated, so I'm going to merge it in. Then I'll cherry pick to release/5.0-rc2 branch.

**Comment by vatsan-madhavan** [comment]
What public surface was added in PresentationUI that generated this XML? /cc @SamBent, @fabiant3 @ryalanms

**Comment by RussKie** [comment]
> Missing from .net50
> 
> * `System.Windows.Forms.Design.Editors.xml`

We removed System.Windows.Forms.Design.Editors in https://github.com/dotnet/winforms/pull/2781, so that's expected

> Added to .net50
> 
> * `Microsoft.VisualBasic.Forms.xml`

This we added in .NET 5.0 timeframe, so I suppose this is expected.

> * `System.Windows.Forms.Primitives.xml`

We created System.Windows.Forms.Primitives.xml in https://github.com/dotnet/winforms/pull/2518, so I suppose it is also expected.

**Pull request merged**
