### PR TITLE
Properly add and remove reflect children

### LINKED ISSUE #1311: ComboBox.SelectedIndexChanged not firing if SelectedIndex is set before OnHandleCreated
Setting ComboBox.SelectedIndex in a form's constructor disables further firing of the SelectedIndexChanged event, in .NET Core. It seems it has to do with the availability of the window and control handles. It works OK in the full framework, but it fails in .NET Core. Looks like a breaking change.

### LINKED ISSUE #1520: WinForm RichTextBox LinkClicked event fails to fire when control loaded with RTF containing a friendly name hyperlink
* .NET Core Version: .Net Core 3.0.100-preview8-013587 build from master branch
* Have you experienced this same bug with .NET Framework?: Yes

**More info:**
There is a blocked GitHub issue [33714](https://github.com/dotnet/corefx/issues/33714) when use Test2.rtf
[Test2_Doc.zip](https://github.com/dotnet/winforms/files/3440865/Test2_Doc.zip)(just add more words than Test.rtf ). Please see the following screenshot:
image

**Problem description:**

1. Open attached app in VS and run it. 
[RichTextBoxCoreApp.zip](https://github.com/dotnet/winforms/files/3440825/RichTextBoxCoreApp.zip)

2. Click the “Click here”, then observe the behavior of browser. 

**Actual behavior:** 
There  is no response after clicking the “Click here”.

**Expected behavior:**
It opens the browser and navigates to the page of Google after clicking the “Click here”.

### LINKED ISSUE #1607: `ListView.AutoResizeColumns` prevents control from firing events
_From @PeterPann23 on Sunday, August 11, 2019 5:19:35 PM_

### Describe the bug
Created a new project in .net Core 3.0
Added a ListView to the form that I populate based on user actions (button click works just fine)
The events on the listview however do not get firred.

### To Reproduce
1. Visual Studio 2019, Core 3.0 Release 3.0.100-preview7-012821
2. Run this the File New  _Windows Forms App(.Net Core)_ Project 
My project looks like this
```XML
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.7.0-preview7.19362.9" />
    <PackageReference Include="System.Windows.Forms.DataVisualization" Version="1.0.0-prerelease.19218.1" />
  </ItemGroup>
</Project>
```
The form uses the "normal" template
```C#
partial class Form1
{
	/// <summary>
	/// Required designer variable.
	/// </summary>
	private System.ComponentModel.IContainer components = null;

	/// <summary>
	/// Clean up any resources being used.
	/// </summary>
	/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	protected override void Dispose(bool disposing)
	{
		if (disposing && (components != null))
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	#region Windows Form Designer generated code

	/// <summary>
	/// Required method for Designer support - do not modify
	/// the contents of this method with the code editor.
	/// </summary>
	private void InitializeComponent()
	{
	// controls before ...
	this.ListViewControlItems = new System.Windows.Forms.ListView();
	// other controls after ...
	
	
	// 
	// ListViewControlItems
	// 
	this.ListViewControlItems.Dock = System.Windows.Forms.DockStyle.Fill;
	this.ListViewControlItems.FullRowSelect = true;
	this.ListViewControlItems.HideSelection = false;
	this.ListViewControlItems.Location = new System.Drawing.Point(0, 37);
	this.ListViewControlItems.MultiSelect = false;
	this.ListViewControlItems.Name = "ListViewControlItems";
	this.ListViewControlItems.Size = new System.Drawing.Size(464, 413);
	this.ListViewControlItems.TabIndex = 2;
	this.ListViewControlItems.UseCompatibleStateImageBehavior = false;
	this.ListViewControlItems.View = System.Windows.Forms.View.Details;
	this.ListViewControlItems.SelectedIndexChanged += new System.EventHandler(this.OnSelectedTrainingFileChanged);
	
	
	}
}
```

the "Code Behind" part of the form is like this:

```CSharp
public partial class Form1 : Form
{
	public Form1()
	{
		InitializeComponent();
		ListViewControlItems.Click += ListViewControlItems_Click;
	}
	
	private void ListViewControlItems_Click( object sender, EventArgs e)
	{
		throw new NotImplementedException();
	}
}
```

4. neither the **Click** event or the **SelectedIndexChanged** event ever get invoked

### Expected behavior
The button click event's get invoked without any problem, I'd expect the Listview to invoke as well. I now add a button to trigger the SelectedIndex change event and works just fine, also knows if any items are selected
```C#
private void OnSelectedTrainingFileChanged(object sender, EventArgs e)
{
	if (ListViewControlItems.SelectedItems.Count > 0)
	{
		ConfigPropGrid.SelectedObject = ListViewControlItems.SelectedItems[0].Tag as NativeConfig;
	}
	else
		ConfigPropGrid.SelectedObject = null;

}
```
### Screenshots

Capture

### Additional context
Build output:
```
● Started at 19:17:54
1>------ Build started: Project: CATS.ML.Interfaces, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
1>CATS.ML.Interfaces -> D:\Source\Cats.ML\CATS.ML.Interfaces\bin\Debug\netstandard2.1\CATS.ML.Interfaces.dll
2>------ Build started: Project: Cats.Deepbook.IBApi, Configuration: Debug Any CPU ------
3>------ Build started: Project: Cats.ML.Core, Configuration: Debug Any CPU ------
4>------ Build started: Project: CATS.ML.Data, Configuration: Debug Any CPU ------
4>You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
3>You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
2>Cats.Deepbook.IBApi -> D:\Source\Deepbook\Cats.Deepbook.IBApi\bin\Debug\netcoreapp3.0\Cats.Deepbook.IBApi.dll
3>ML\Data\Versatile\VersatileMLDataSet.cs(103,64,103,89): warning CS0067: The event 'VersatileMLDataSet.OnColumnsWithNoAddedValue' is never used
3>Cats.ML.Core -> D:\Source\Cats.ML\cats.ml.core\bin\Debug\netstandard2.1\Cats.ML.Core.dll
3>Done building project "Cats.ML.Core.csproj".
4>CATS.ML.Data -> D:\Source\Cats.ML\CATS.ML.Data\bin\Debug\netstandard2.1\CATS.ML.Data.dll
5>------ Build started: Project: Cats.Deepbook.Shared, Configuration: Debug Any CPU ------
5>DeeBookNativeBarBuffer.cs(42,81,42,96): warning CS0067: The event 'DeeBookNativeBarBuffer.OnCrazyMovement' is never used
5>Cats.Deepbook.Shared -> D:\Source\Deepbook\Cats.Deepbook.Shared\bin\Debug\netcoreapp3.0\Cats.Deepbook.Shared.dll
5>Done building project "Cats.Deepbook.Shared.csproj".
6>------ Build started: Project: CATS.Deepbook.NetworkTrader, Configuration: Debug Any CPU ------
6>CATS.Deepbook.NetworkTrader -> D:\Source\Deepbook\CATS.Deepbook.NetworkTrader\bin\Debug\netcoreapp3.0\CATS.Deepbook.NetworkTrader.dll
========== Build: 6 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
● Finished at 19:17:56 (total time 2.34s)
```

`dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.400-preview-010195 [C:\Program Files\dotnet\sdk]
  2.2.400-preview-010219 [C:\Program Files\dotnet\sdk]
  2.2.400 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

_Copied from original issue: aspnet/AspNetCore#13035_

### LINKED ISSUE #1644: RichTextBox link handling is broken
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

`RitchTextBox` does not react to `LinkClicked` events at all.

**Actual behavior:** 
Created two apps - .NET 4.6.1 and .NET Core side-by-side targeting msftedit.dll (not the old riched20.dll), loaded the same rtf:
rtb-link-issue

**Expected behavior:**

.NET Core reacts to the events like .NET Fx did.

**Minimal repro:**

https://github.com/RussKie/Test-RichTextBox-links

### PR DESCRIPTION
**Pull request by JeremyKuhne**
The bug was introduced as part of refactoring in #1034 - ordering got flipped with switching `as` to `is`.
The confusion was likely caused by the fact that the property setter called its own getter.

Update the code to be more explicit in terminology to hopefully avoid this from happening again.

Fixes #1311
Fixes #1520
Fixes #1607
Fixes #1644

## Proposed changes

- Properly add message reflect children

## Customer Impact

- Without this NO messages will be sent to child controls- this impacts a huge swath of functionality

## Regression? 

- Yes : #1034

## Risk

- Low

## Test methodology

- Extensive debugging, ran automated and manual tests

## Test environment(s)

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/1661)

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
I'll look to see what sort of automated tests can be added for this when I recover from investigating the issue. 😴

**Comment by RussKie** [comment]
Thank you Jereme!

#1034 in commit 462c242a074b16c90da77f43975955b5b552c7e4 made the following change:
```diff
@@ -3803,9 +3801,8 @@ namespace System.Windows.Forms
                     value.AddReflectChild();
                 }
 
-                Control c = ReflectParent as Control;
                 reflectParent = value;
-                if (c != null)
+                if (ReflectParent is Control c)
                 {
                     c.RemoveReflectChild();
                 }
```

The orginal code that come from .NET Fx:
```cs
                Control c = ReflectParent as Control;
                reflectParent = value;
                if (c != null) {
                    c.RemoveReflectChild();
                }
```

A significance of the order of instructions isn't particularly obvious.
The fact that a backing field and the property are liberally interchanged without any obiovus reason is concerning.

Here's another snip where the use of the property looks unjustified (line 3274):
https://github.com/dotnet/winforms/blob/abd5a3d167ef57ee478912e97f194ff3a21d14b2/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L3263-L3279

**Comment by RussKie** [comment]
I've enhanced our manual integration tests and reworded the commit message (hope you don't mind).

I wonder if we can enhance our integration tests to perform actions (like change selected item in a combo) and assert a label has the expected text?
No sure how we can deal with message boxes though, probably remove them altogether...

**Comment by RussKie** [comment]
Added more manual tests for richtextboxes

**Comment by weltkante** [comment]
Does this actually fix #1520 as claimed in PR description? There was a stackoverflow article linked in #1631 (resolved duplicate of #1520) which explains "friendly name hyperlinks" as a feature being added in RTF 5.0 and WinForms never being updated to support it. From that description it doesn't sound like being cause by this particular regression, since it already regressed in Desktop Framework long before.

**Comment by RussKie** [comment]
> Does this actually fix #1520 as claimed in PR description?

It does.
Please see WinformsControlsTest/RichTextBoxes test example.

**Comment by weltkante** [comment]
I see, I'd recommend to reopen #1631 then because it probably doesn't get fixed by this PR (can't test easily at the moment, but I added an example to the issue)

**Comment by leecow** [comment]
tactics approved - preview 9

**Pull request merged**
