### PR TITLE
Fix PropertyGrid.RemoveTabType method

### LINKED ISSUE #10574: PropertyGrid.RemoveTabType does not effectively remove tab
### .NET version

8.0.100

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works in 5.0

### Issue description

The PropertyGrid.RemoveTabType method does not effectively remove the PropertyTab. Calling this method with a previously added tab does not suppress the tab. It looks like the check on type is wrong in the method RemoveTabType  since the commit https://github.com/dotnet/winforms/pull/6108

The type check is not consistent between AddTabType and RemoveTabType method:
In AddTabType: https://github.com/dotnet/winforms/blob/39c1cfba04f0682ae79e6629188eb291bc0d203e/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs#L1480

In RemoveTabType:
https://github.com/dotnet/winforms/blob/39c1cfba04f0682ae79e6629188eb291bc0d203e/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs#L3565

### Steps to reproduce

1. Create a new form with a PropertyGrid
2. Create a class MyPropertyTab which inherits from PropertyTab
3. Properly implement MyPropertyTab 
4. Call propertyGrid.AddTabType(typeof(MyPropertyTab))
5. Call propertyGrid.RemoveTabType(typeof(MyPropertyTab))

In .net50, MyPropertyTab is removed
in .net80, MyPropertyTab is not removed

### PR DESCRIPTION
**Pull request by thomasnaletsg**
Tab removal wasn't matching the tab type so it wouldn't remove tabs.

Fixes #10574

### CODE REVIEW

**Comment by thomasnaletsg** [comment]
Related to issue https://github.com/dotnet/winforms/issues/10574

**Comment by Tanya-Solyanik** [comment]
@thomasnaletsg the fix looks good, could you please add a unit test that removes tabs?

**Comment by thomasnaletsg** [comment]
> @thomasnaletsg the fix looks good, could you please add a unit test that removes tabs?

@JeremyKuhne as an author of the initial refactoring, could you please add a UT covering this use case? Thanks in advance.

**Comment by lonitra** [comment]
@thomasnaletsg I've gone ahead and added a unit test. Please read CLA above.

**Review by Tanya-Solyanik — APPROVED** [review]

**Comment by kirsan31** [comment]
@lonitra 
> /backport to release/8.0

And what will be with 6.0 and 7.0?

**Comment by lonitra** [comment]
> And what will be with 6.0 and 7.0?

We think that servicing this to 8.0 will be enough, but if there is a customer request we can bring this to shiproom.

**Comment by lonitra** [comment]
@thomasnaletsg gentle ping. Could you please accept CLA so this can be merged?

**Comment by thomasnaletsg** [comment]
@dotnet-policy-service agree

**Pull request merged**
