### PR TITLE
Merge main into feature/win32

### PR DESCRIPTION
**Pull request by JeremyKuhne**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7498)

### CODE REVIEW

**Review by Tanya-Solyanik — COMMENTED** [review]
You are merging from branch names `mergemain`, not the main from upstream, is this intentional?

**Comment by JeremyKuhne** [comment]
You are merging from branch names mergemain, not the main from upstream, is this intentional?

@Tanya-Solyanik, I couldn't get this to work without merging locally (to resolve conflicts).

**Review by Tanya-Solyanik — APPROVED** [review]

**Comment by RussKie** [comment]
Why not rebase cleanly on top of the latest main and then f-push?

**Comment by RussKie** [comment]
```
git fetch --all
git checkout remote/main -B main
git checkout upstream/feature/win32 -B feature/win32
git -c rebase.autoSquash=false rebase main
```

There are two simple merge-conflicts to deal with, otherwise it's all very straight forward.

**Comment by JeremyKuhne** [comment]
Reopening a new one based on @RussKie's steps.

**Comment by RussKie** [comment]
Please let me know If you're having troubles, I can guide you through. I can rebase and push too :)

**Pull request closed without merging**
