### PR TITLE
Loc checkin

### PR DESCRIPTION
**Pull request by cristianosuzuki77**
Localization of the json files.
German files were reviewed by translators and modifications were made.
Attached the translator comments:

[deutranslationfromcore_Commented.xlsx](https://github.com/dotnet/winforms/files/5387860/deutranslationfromcore_Commented.xlsx)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/4118)

### CODE REVIEW

**Comment by cristianosuzuki77** [comment]
@KlausLoeffelmann FYI. Please the comments about German translations.

**Comment by dreddy-work** [comment]
@KlausLoeffelmann , I am not confident with some of the changes made in this PR. Can you take a look?

**Review by KlausLoeffelmann — COMMENTED** [review]
@dreddy-work: There are a couple of language entries for the first template, which had the wrong titel/descriptions (Control Libraries instead of Application) as placeholder texts, so the translation seems wrong on first sight. But that's not the case: The English template is the lead here, and I checked the translations, they are OK.

For German: I agree with every suggestion, except the term "_in_ .NET". You can have an App written in C# or in VB but not in .NET. .NET is not a programming language. It's either "für .NET" or "unter .NET" - but the latter does sound a bit odd. I chose to use .NET as a prefix, which is grammatically correct and easiest to understand.

I will now build and test this PR on a German and a French system, before I approve.

**Comment by KlausLoeffelmann** [comment]
image

The German localization is working. The English originals are unchanged.
Umlauts are all in place.

@cristianosuzuki77: If you're fine with the suggested changes, I'd take the PR (if @merriemcgaw, @Pilchie (M.2) and @SteveCarrollMSFT (QB) approve.

**Review by KlausLoeffelmann — APPROVED** [review]
Decided to take the German suggestions now due to time constraints.
Tested the strings in a German and English VS version, everything looks good.

**Review by merriemcgaw — APPROVED** [review]

**Pull request merged**
