### PR TITLE
Replace MD5 with SHA256

### LINKED ISSUE #10930: Remove use of MD5 in tests and switch them to SHA256
There are 2 test files using MD5 that need to switch to use SHA256:

1. System.Drawing.Tests.DrawingTest
2. MonoTests.System.Drawing.BitmapTests

### PR DESCRIPTION
**Pull request by LeafShi1**
Fixes #10930 

Remove use of MD5 in tests and switch them to SHA256 and remove related suppression information

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/winforms/pull/10939)

### CODE REVIEW

**Comment by LeafShi1** [comment]
Draft PR: This is only a partial modification

**Review by Tanya-Solyanik — APPROVED** [review]
Thank you!

Had you reviewed if this is the only instances of MD5 in tests?

**Review by ricardobossan — DISMISSED** [review]
All LGTM

**Review by ricardobossan — APPROVED** [review]
Dismissed previous review by mistake. All LGTM.

**Comment by LeafShi1** [comment]
> Thank you!
> 
> Had you reviewed if this is the only instances of MD5 in tests?

Yes, I searched the entire Solution for MD5 and replaced it

**Review by lonitra — APPROVED** [review]

**Pull request merged**
