### PR TITLE
WIP: Add tests to enumerate all attribute decorations

### PR DESCRIPTION
**Pull request by RussKie**
To better reason about refactors and code cleanup capture API attribute decorations.

Pre-req for https://github.com/dotnet/winforms/pull/2892

/cc: @hughbe 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/2966)

### CODE REVIEW

**Comment by Tanya-Solyanik** [comment]
Had you sync'd up with Eric or @JuditRose if Runtime have test like this one in the binary compat suite already?
What FX version was used to generate the baseline?

**Comment by RussKie** [comment]
> if Runtime have test like this one in the binary compat suite already?

The API compat story is lagging behind, waiting for it would mean we'll be blocking incoming changes.
If the API compat provides the same functionality we can remove these tests.

> What FX version was used to generate the baseline?

I captured what we have in the master.


> How will this test handle public surface changes?

Tests will fail, like they are now, and will need to be fixed by whoever introduced the change.

**Comment by Tanya-Solyanik** [comment]
>The API compat story is lagging behind, waiting for it would mean we'll be blocking incoming changes.
This depends on how much we have to wait. Eric sounded like it's a matter of opting in into their infra.

**Comment by RussKie** [comment]
The tests are failing for no apparent reason on build agents. Feels like the approved file is somehow either missing or blanked out. I performed a series of tests locally and on VMs and was unable to reproduce the failure observed on the CI.

I've raised https://github.com/approvals/ApprovalTests.Net/issues/331 but not having high hopes.

**Comment by RussKie** [comment]
Re-opened to test a hypothesis from https://github.com/approvals/ApprovalTests.Net/issues/335

**Pull request closed without merging**
