### PR TITLE
 Add BindingContext tests and fix validation

### LINKED ISSUE #576: BindingContext.UpdateBinding(new BindingContext(), null) throws NRE
Should be ANE

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #576

### CODE REVIEW

**Comment by hughbe** [comment]
Is the following dead code?
```cs
public static void UpdateBinding(BindingContext newBindingContext, Binding binding)
{
    if (binding == null)
    {
        throw new ArgumentNullException(nameof(binding));
    }

    BindingManagerBase oldManager = binding.BindingManagerBase;
    if (oldManager != null)
    {
        oldManager.Bindings.Remove(binding);
    }

    if (newBindingContext != null)
    {
        // we need to first check for cycles before adding this binding to the collection
        // of bindings.
        if (binding.BindToObject.BindingManagerBase is PropertyManager) // <-- HERE
        {
            CheckPropertyBindingCycles(newBindingContext, binding);
        }

        BindToObject bindTo = binding.BindToObject;
        BindingManagerBase newManager = newBindingContext.EnsureListManager(bindTo.DataSource, bindTo.BindingMemberInfo.BindingPath);
        newManager.Bindings.Add(binding);
    }
}
```

Its my understanding that calling `oldManager.Bindings.Remove(binding)` would set the `BindingManagerBase` to null, so `binding.BindToObject.BindingManagerBase is PropertyManager` is always false?

**Comment by zsd4yr** [comment]
> Is the following dead code?

@Tanya-Solyanik knows more about binding than I do. It may not light up in our repo, but the designer may use it?

**Comment by zsd4yr** [comment]
Looks like you left the lines from your question in. I think that's the safer option unless Tanya gets back to us with an A-OK to remove them 😄

**Comment by Tanya-Solyanik** [comment]
@zsd4yr  - it's safer to not remove this code. I don't know if BindingManagerBase  is guaranteed to be in sync between the binding and the bindtoobject

**Comment by hughbe** [comment]
Ok then, we’re agreed to keep it. I’ll do some more research and see if we can refactor out the synchronisation if they are indeed in sync

**Comment by zsd4yr** [comment]
> Ok then, we’re agreed to keep it. I’ll do some more research and see if we can refactor out the synchronisation if they are indeed in sync

Sounds good. In the meantime, I'll close the PR

**Comment by hughbe** [comment]
Sorry, could we actually merge this PR - its in a state where it can be merged!

**Pull request closed without merging**
