### PR TITLE
Save files as utf-8-bom

### LINKED ISSUE #198: Strange Encoding Issues
When cloning and opening the code base for the first time, on macOS 10.14.1, strange encoding issues appear. A few were fixed in another PR, but here's a list of the others I found.

screen shot 2018-12-06 at 9 56 24 am

#155 @Tanya-Solyanik

### PR DESCRIPTION
**Pull request by sharwell**
This encoding is already configured in .editorconfig:

https://github.com/dotnet/winforms/blob/a7ca739d35a6369a10d50fb3d7e39c2aeb9dd620/.editorconfig#L18

Changes are separated into files that did not have character encoding mistakes, and those that did.

related to #482
fixes #198

### CODE REVIEW

**Comment by zsd4yr** [comment]
@sharwell can you point out to me the 1-3 files that have more than just that one line change at the top?

**Comment by sharwell** [comment]
@zsd4yr I recommend you review commit-by-commit for this one

**Comment by zsd4yr** [comment]
> @zsd4yr I recommend you review commit-by-commit for this one

Ah I see. Thank you

**Comment by sharwell** [comment]
@zsd4yr This is a case where all the work I did to make this change reviewable was undone because of a squash merge.

**Pull request merged**
