### PR TITLE
Update public pool names

### PR DESCRIPTION
**Pull request by alexperovich**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/7733)

### CODE REVIEW

**Review by Shyam-Gupta — APPROVED** [review]

**Comment by alexperovich** [comment]
It looks like there are some warnings in the build that are becoming errors, but this change didn't cause them.

**Review by lonitra — APPROVED** [review]

**Comment by JeremyKuhne** [comment]
@dreddy-work This should not have been merged with a build break. Investigating.

**Comment by JeremyKuhne** [comment]
Sorry, the problem was on my end. I read this wrong. Apologies and disregard.

**Comment by dreddy-work** [comment]
np. I made sure build was successful before merging.

**Pull request merged**
