### PR TITLE
LOC CHECKIN | dotnet/winforms master | 20190902

### PR DESCRIPTION
**Pull request by v-zbsail**
Fixes #

## Proposed changes

- Localization update
- 
- 

## Customer Impact

- 
- 

## Regression? 

- Yes / No

## Risk

-

## Test methodology 

- 
- 
- 

## Test environment(s) 

- 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/1743)

### CODE REVIEW

**Comment by RussKie** [comment]
Is this change targeting .NET Core 3.0 or .NET 5.0?

**Comment by janbaltus** [comment]
@AdamYoblick  please answer this question. The PR is fixing the Policheck issue "oriental"

**Comment by AdamYoblick** [comment]
I think it's fine to go into master and target 5.0. None of these are urgent bugs (that I'm aware of). @janbaltus Can you please confirm that none of these are critical?

**Comment by RussKie** [comment]
Thank you

**Pull request merged**
