### PR TITLE
use new intellisense blob, change package composition logic (#3999)

### PR DESCRIPTION
**Pull request by AdamYoblick**
Cherry pick https://github.com/dotnet/winforms/commit/4bdf29eef947200c946ca7f295b47fe829bed41f from master

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/4004)

### CODE REVIEW

**Comment by RussKie** [comment]
@AdamYoblick looks like this change has broken VS:
```
6>C:\Development\winforms.5x\eng\packageContent.targets(29,5): error MSB4184: The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.
6>Done building project "System.Windows.Forms.csproj" -- FAILED.
9>C:\Development\winforms.5x\eng\packageContent.targets(29,5): error MSB4184: The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.
9>Done building project "System.Windows.Forms.Design.csproj" -- FAILED.
6>C:\Development\winforms.5x\eng\packageContent.targets(29,5): error MSB4184: The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.
6>Done building project "Accessibility.ilproj" -- FAILED.
6>C:\Development\winforms.5x\eng\packageContent.targets(29,5): error MSB4184: The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.
6>Done building project "System.Windows.Forms.Primitives.csproj" -- FAILED.
Build has been canceled.
Projects build report:
  Status    | Project [Config|platform]
 -----------|---------------------------------------------------------------------------------------------------
  Succeeded | pkg\Microsoft.Dotnet.WinForms.ProjectTemplates\Microsoft.Dotnet.Winforms.ProjectTemplates.csproj [Debug|Any CPU]
  Failed    | src\System.Drawing.Design\src\System.Drawing.Design.Facade.csproj [Debug|Any CPU]
  Failed    | src\System.Windows.Forms\tests\AccessibilityTests\AccessibilityTests.csproj [Debug|Any CPU]
  Failed    | src\System.Windows.Forms\tests\InteropTests\System.Windows.Forms.Interop.Tests.csproj [Debug|x86]
  Failed    | src\System.Drawing\src\System.Drawing.Facade.csproj [Debug|Any CPU]
  Failed    | src\System.Windows.Forms.Design.Editors\src\System.Windows.Forms.Design.Editors.Facade3x.csproj [Debug|Any CPU]
  Failed    | src\System.Windows.Forms\tests\IntegrationTests\System.Windows.Forms.IntegrationTests.Common\System.Windows.Forms.IntegrationTests.Common.csproj [Debug|Any CPU]
  Failed    | src\Accessibility\ver\Accessibility-version.csproj [Debug|Any CPU]
  Failed    | src\System.Design\src\System.Design.Facade.csproj [Debug|Any CPU]
  Failed    | src\Microsoft.VisualBasic\src\Microsoft.VisualBasic.Facade.csproj [Debug|Any CPU]
  Failed    | src\System.Windows.Forms.Primitives\tests\TestUtilities\System.Windows.Forms.Primitives.TestUtilities.csproj [Debug|Any CPU]

```

**Comment by AdamYoblick** [comment]
Ah crap. All my testing was done via command line. I will look at this first thing tomorrow morning.

________________________________

**Comment by AdamYoblick** [comment]
@Fabian Toader<mailto:Fabian.Toader@microsoft.com>  looks like there will likely be another fix for the intellisense stuff. I’ll look at it ASAP.

________________________________

**Comment by RussKie** [comment]
Raised https://github.com/dotnet/winforms/pull/4007, please have a look

**Pull request merged**
