### PR TITLE
Remove deprecated API

### PR DESCRIPTION
**Pull request by RussKie**
As identified in https://github.com/dotnet/winforms/issues/2476#issuecomment-568494860

Relates to #2091

## Proposed changes

- Remove the following API because they have been obsolete since .NET 2.0:
	* `StatusBar`
	* `StatusBarDrawItemEventArgs`
	* `StatusBarDrawItemEventHandler`
	* `StatusBarPanel`
	* `StatusBarPanelAutoSize`
	* `StatusBarPanelBorderStyle`
	* `StatusBarPanelClickEventArgs`
	* `StatusBarPanelClickEventHandler`
	* `StatusBarPanelStyle`

## Customer Impact

- Removed controls no longer available to customers and will cause builds to break
- Customers will need to replace the removed controls with available alternatives.

## Regression? 

- ~Yes~ / No

## Risk

- Medium, the controls in questions have been deprecated in .NET 2.0 era, however there is a recorded use of those.

## Test methodology 

- TBD

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/2798)

### CODE REVIEW

**Comment by merriemcgaw** [comment]
Business case approved.

**Comment by RussKie** [comment]
@OliaG FYI

**Comment by RussKie** [comment]
@vatsan-madhavan FYI, I hope it doesn't affect WPF

**Comment by vatsan-madhavan** [comment]
>  FYI, I hope it doesn't affect WPF

You can just test for it instead and avoid breaking things *after* merging them, and then have to worry about reverting them or needing the next-repo to do stuff in a hurry etc. 

- build you repo locally to get `Microsoft.Private.Winforms.5.0.0-dev.nupkg` under, say `%winformsroot%\artifacts\packages\Debug\NonShipping`
- clear nuget cache (`nuget locals all -clear`)
- clone dotnet/wpf (`git clone https://github.com/dotnet/wpf`)
  - edit `NuGet.config` and add a new source pointing to `%winformsroot%\artifacts\packages\Debug\NonShipping`
  - `darc update-dependency -n Microsoft.Private.Winforms -v 5.0.0-dev`
  -  build wpf 
    - `build -pack -configuration Debug|Release -platform x86|x64` 

Or better yet, you can set up a couple of test branches on the internal Azure pipelines mirror repos to and use the build-pipelines to run the builds. For complex changes that _might_ break the next repo, we do this sort of stuff proactively all the time. See [this](https://dev.azure.com/dnceng/internal/_build/results?buildId=511057&view=results) for example.

**Comment by RussKie** [comment]
Yes, an after thought on my part.
Thank you for the instructions

**Comment by RussKie** [comment]
Docs: https://github.com/dotnet/docs/issues/17008

**Pull request merged**
