### PR TITLE
Moving units tests from AccessibleObjects folder

### LINKED ISSUE #5746: Move unit tests from "AccessibleObjects" folder
Unit tests from the folder `\winforms\src\System.Windows.Forms\tests\UnitTests\AccessibleObjects` (61 files) should be moved to the folder `C:\Projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms`  and their namespaces should be changed from `System.Windows.Forms.Tests.AccessibleObjects` to `System.Windows.Forms.Tests` . That way their location and namespaces will be consistent with the main complex of the tests.
image

### PR DESCRIPTION
**Pull request by ArtemTatarinov**
Fixes #5746

## Proposed changes

- Moving unit tests from `AccessibleObjects` folder to make them consistent with other unit tests.

## Customer Impact

- No

## Regression? 

- No

## Risk

- Minimal

## Test methodology 

- Manual testing
- Unit tests

## Test environment(s) 
Microsoft Windows [Version 10.0.19043.1165]
.NET SDK 7.0.0-alpha.1.21461.7

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/5748)

### CODE REVIEW

**Comment by ArtemTatarinov** [comment]
@dreddy-work could you please check it, I moved just 5 files for testing, if everything is ok, I'll move the rest.

**Review by dreddy-work — APPROVED** [review]
LGTM.

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
I'm a proponent of tests name/location mirroring the prod code. This way it is easy to see if there are tests for a given type and what kind of tests exist.

**Comment by ArtemTatarinov** [comment]
Moved the rest of the unit tests: https://github.com/dotnet/winforms/pull/5759

**Pull request merged**
