### PR TITLE
Fix ambiguous references in cref attributes

### PR DESCRIPTION
**Pull request by sharwell**
Restores build diagnostics which were disabled in #10525.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/10596)

### CODE REVIEW

**Review by JeremyKuhne — CHANGES_REQUESTED** [review]
I do not want this merged yet. I'm in the middle of more changes that this would conflict with. This is something we as a team will discuss further once we have more of the intended work finished.

**Review by JeremyKuhne — DISMISSED** [review]

**Comment by lonitra** [comment]
@sharwell Looks like there are CI failures, are you able to look into this?

**Comment by sharwell** [comment]
@JeremyKuhne this is now updated

**Review by JeremyKuhne — APPROVED** [review]

**Review by lonitra — APPROVED** [review]
Thank you

**Pull request merged**
