### PR TITLE
Redo of "Use system hand cursor"

### PR DESCRIPTION
**Pull request by AdamYoblick**
Redo of #138

### CODE REVIEW

**Comment by AdamYoblick** [comment]
@sylveon I had to revert #138 because the PR build was very old and was passing, but it failed after merging into master. Please see the test failures for the PR build for this PR and fix them.

Thank you :)

**Comment by zsd4yr** [comment]
Thanks @AdamYoblick

**Comment by sylveon** [comment]
I'm not really sure of what's happening here, seems like some other test is disposing the system cursors.

**Comment by sylveon** [comment]
And I can't reproduce:


Command line testing just spits out a bunch of `The "ResolveFrameworkReferences" task was not given a value for the required parameter "RuntimeGraphPath".`

**Comment by AdamYoblick** [comment]
@sylveon I was not able to repro this locally either, all the tests pass for me. Does creating the cursors in the way that you do require anything UI related? The AzDO agents on the build machines do not currently run in interactive mode, which can cause UI tests to fail.

This is currently being changed, but the work is done by another team, and it probably wont be done until the end of this week at the earliest.

**Comment by sylveon** [comment]
Don't think it does.

**Comment by zsd4yr** [comment]
Have we made any progress here? @sylveon our Integration.Tests project runs in an interactive pool of machines, so if indeed that is the issue here --moving the tests and merging from master to get the pool changes should theoretically resolve these issues.

**Comment by sylveon** [comment]
Well, I can't do any changes on this PR by myself.

**Comment by merriemcgaw** [comment]
@AdamYoblick can you take a look?

**Comment by JuditRose** [comment]
Hi @sylveon, I believe you cannot add changes to this PR because the branch is owned by Adam and you would need permissions from him (he is on leave ATM). 
So to speed this up: Would you mind creating a new branch from this one (which you can actually make changes to), merging master on top, and open a new PR? And we can close this one then.

**Comment by sylveon** [comment]
I just opened #525 which is the same code as this but with master merged and everything seems to build & test fine now.

**Comment by zsd4yr** [comment]
Closing due to #525 reopen --thanks sylveon for your work here :)

**Pull request closed without merging**
