### PR TITLE
Cast InnerList to `IList`

### PR DESCRIPTION
**Pull request by Jericho**
as requested by @JeremyKuhne [here](https://github.com/dotnet/winforms/pull/8207#discussion_r1035150381).

Related to #8140 and #8143

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/8316)

### CODE REVIEW

**Review by JeremyKuhne — APPROVED** [review]
Thanks!

**Comment by JeremyKuhne** [comment]
Tests need updated

**Comment by JeremyKuhne** [comment]
I'll re-review once tests are working. Please tag me when that's done @Jericho

**Comment by Jericho** [comment]
@JeremyKuhne Fixed.

For some reason, some classed are designed to use `this` as their SyncRoot. Changing to `((IList)InnerList).SyncRoot` is what caused the tests to fail. 

Also some of these same classes are designed to be Fixed size and/or readonly despite the fact that their underlying list can be expended. That's why we cannot change some of their properties (such as `IsFixed` for example) to `((IList)InnerList).IsFixed`.

**Review by JeremyKuhne — APPROVED** [review]

**Pull request merged**
