### PR TITLE
Fix bugs in ResourceCodeDomSerializer.SerializationResourceManager

### PR DESCRIPTION
**Pull request by halgab**
As discussed in #9457.

#8332 introduced bugs in `ResourceCodeDomSerializer.SerializationResourceManager`, in method `GetResourceSet`. When we fail to get a resource reader, the original code used to return a resource set for the invariant culture, and null otherwise. After #8332,,

- we're returning `null` the first time we fill the `ResourceTable` cache
- for the non-invariant culture case, we started filling the `ResourceTable` cache with a static dictionary,  which looks like a pretty big issue

These bugs were introduced in .Net 8 and we still have a chance to fix them before the release

@dreddy-work, @elachlan 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/winforms/pull/9642)

### CODE REVIEW

**Comment by dreddy-work** [comment]
> * we started filling the `ResourceTable` cache with a static dictionary,  which looks like a pretty big issue

@halgab, i see original code before @elachlan's change was also doing this. Can you point me to the original code where it wasn't?

**Comment by halgab** [comment]
Before #8332, `s_resourceSetSentinel` was not a dictionary or a hashtable but an object (see line 21). Then on line 505, we checked that the content of `ResourceTable` was actually a `Hashtable`, which proved to be false when we were returning `s_resourceSetSentinel`

**Comment by Tanya-Solyanik** [comment]
@halgab - is it possible to add a unit test for this scenario?

**Comment by halgab** [comment]
I agree that would be ideal, but right now code coverage of serializers is so scarce I wouldn't really know where to start...

**Comment by dreddy-work** [comment]
We can track test debt under separate issue. @Tanya-Solyanik, you good with changes here?

**Comment by elachlan** [comment]
Related: #719, #966

**Review by lonitra — APPROVED** [review]
LGTM

**Pull request merged**
