### PR TITLE
Fixed broken link pointing to contributing.md

### PR DESCRIPTION
**Pull request by manuelvalenzuela**

### CODE REVIEW

**Comment by zsd4yr** [comment]
Hey @manuelvalenzuela thanks for the contribution here 😄 Is there a way to point to this document without requiring it be the blob on master? For instance, this link should point to the version of this document in whichever branch it is in, not always master.

**Comment by manuelvalenzuela** [comment]
> o

Hi @zsd4yr!! you're welcome!. I think the link is independent of the branch right now, is just a relative link (the only line I changed was 28)

**Comment by zsd4yr** [comment]
> Hi @zsd4yr!! you're welcome!. I think the link is independent of the branch right now, is just a relative link (the only line I changed was 28)

@manuelvalenzuela I think I would prefer if it was _dependent_ on the branch

**Comment by manuelvalenzuela** [comment]
You're right, I will do it now.

**Comment by merriemcgaw** [comment]
@manuelvalenzuela thanks for the contribution!

**Comment by manuelvalenzuela** [comment]
> @manuelvalenzuela thanks for the contribution!

@merriemcgaw glad to do it! this is just a preheating! :D

**Pull request merged**
