### PR TITLE
Adding the Core RT cases

### PR DESCRIPTION
**Pull request by Zheng-Li01**
Hi @AdamYoblick , @RussKie. Winforms CTI Team try to add some Core RT cases to the dotnet/winfoms repro, please have a review and give some guidance if there have something wrong.

Thanks

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/winforms/pull/2280)

### CODE REVIEW

**Comment by Tanya-Solyanik** [comment]
@Zheng-Li01  - some preliminary feedback - please review c[oding style](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md ) guidelines and try to apply them. This is a lot of work, so it could be done over multiple PRs. Perhaps you could start with some simple things, for example let VS apply some style rules( click the light bulb in the VS code view that suggests changes). Or right click in the code editor and do "sort and remove usings".
Could you please also describe how to run these new tests? What percentage of coverage do we get with them?

**Comment by AdamYoblick** [comment]
Also I’ll need to take a look at the directory structure tomorrow, I think it’s a bit off :)

________________________________

**Comment by Zheng-Li01** [comment]
@Tanya-Solyanik, thanks for your guidelines. i will modify the code style before the next apply, @AdamYoblick, could you please provide some guidance about how to run the cases automatically  when the new PR generated. 
And the Porting Maui test case to Xunit test case task is in progress, the percentage of coverage should be 100% after completed the all core cases migration.

**Comment by Zheng-Li01** [comment]
@AdamYoblick, thanks..

This is low priority.

**Comment by AdamYoblick** [comment]
I can, there’s a document I wrote that details how to do it. I will send the link tomorrow as I’m currently on my phone :)

________________________________

**Comment by RussKie** [comment]
Thank you @Zheng-Li01 but we can't meaningfully review or take the change in the current form.

I propose we structure the work as follows:
- take one test project, 
- follow @AdamYoblick's guides, and apply incoming feedback,
- get a PR into a mergeable state.
Repeat for other test projects.

This way changeset would be small and easy to review; any feedback could be applied easily. 
And I expect that after a few initial PRs, all new PRs will go in without any fuss.

**Comment by AdamYoblick** [comment]
Agree with Igor on all points :)

________________________________

**Comment by Zheng-Li01** [comment]
@AdamYoblick @RussKie. thanks for your advice, and we will following the **"steps"** provide by igor to complete the task that "Porting Maui test case to Xunit test case "

**Comment by AdamYoblick** [comment]
@Zheng-Li01 in case you need the doc for reference, it's at https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/readme.md

**Comment by Tanya-Solyanik** [comment]
>the percentage of coverage should be 100% after completed the all core cases migration.

Great!

**Pull request closed without merging**
