### PR TITLE
Cleanup Critical Exception Handling

### PR DESCRIPTION
**Pull request by hughbe**
## Proposed Changes
- Remove DbgUtil
- Turn `IsSecurityOrCriticalException` to `IsCriticalException`. Its my understanding that in .NET Core we shouldn't be expecting code assert failures etc./

I'd really love to see `IsCriticalException` killed off and us to do proper checking. I hate this pattern!

### CODE REVIEW

**Comment by hughbe** [comment]
Tests do need to be updated
```
Assert.Throws() Failure\r\nExpected: typeof(System.Security.SecurityException)\r\nActual: (No exception was thrown)


Stack trace
   at System.Windows.Forms.Tests.BindingTests.Binding_OnBindingComplete_ThrowsCriticalException_Rethrows(BindingCompleteEventArgs eventArgs, Exception exception) in F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\BindingTests.cs:line 399
```

What do we think?

**Comment by RussKie** [comment]
It looks like `Security.SecurityException` is still a thing in .NET5, why do you think we should stop checking for it? This will be a breaking change...

**Comment by hughbe** [comment]
Yes so my analysis is that SecurityException used to be thrown from CAS and things like that that have been removed.
Since we don’t expect this exception to be thrown really in .NET core we shouldn’t catch it

**Comment by RussKie** [comment]
We've discussed the issues at a triage meeting and concluded it was safe to remove.

Thank you.

**Pull request merged**
